### ISSUE TITLE
Add component labels to organize issues

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#112]
JupyterLab uses labels (pkg:component_name), but since GitHub has a separate "projects" category, maybe we could use it for packages insted.

**Comment by bollwyvl** [comment]
I've seen projects used effectively for big things that span milestones and/or repos which are hard to track without (real) inter-issue dependencies. A prefixed label set is probably just fine for the scale we are working. Though we _should_ make some projects,  e.g. `Propose to JupyterLab Core`, `World Domination`, etc.

**Comment by krassowski** [comment]
Added `feature:`, `package:` and `editor:` [labels](https://github.com/krassowski/jupyterlab-lsp/issues/labels). Colors up for discussion ;)
