### ISSUE TITLE
Allow lsp_message_listener to modify messeges?

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#113]
I looked into implementing the server-side shadow filesystem. I think that we need to modify the client messages to replace the filenames with paths to our shadow (tempory) files.

Side note: I read again through the docs of LSP, and the truth about the files should be read from the synced text after `initilialize` and `didOpen`, but the reality (as we discussed earlier) is that no server I know obeys the specification fully (especially R and Python, which are the servers I need the most) and all of them dip into the filesystem from time to time...

**Comment by krassowski** [comment]
Of course, the alternative would be to introduce a custom protocol to tell the frontend where the temporary shadow files will be stored... But I don't like this idea because:
1. This is more work in already complicated project
2. The shadow filesystem should be a temporary solution (until the language servers get properly implemented), not a permanent thing

**Comment by bollwyvl** [comment]
Right, we knew we had to do _something_. Can you concretely describe what we might have to change? I understand "make this URL I find actually exist" (though it scares me), but I'm still a bit fuzzy on what might be required if we start making changes to the message content. If we can _at all_ avoid it, that would be ideal, as thus far we've gotten by with trusting the servers to send us good JSON, but as soon as we start changing stuff, it's on us if it breaks.

Of course, the client _also_ has the ability to write to the ContentsManager, which is actually _more_ reliable than us monkeying about with files... long term, we'd like something that was more or less contents-agnostic, though who knows how we'll resolve that.

Either way, I think we'd need this to be opt-in, either as (at least) a configurable or an extra package, and with the behavior configured by pattern or something (e.g. `*.ipynb`). But if it turns into something that needs to be configured per kernel/ls... i dunno.

**Comment by krassowski** [comment]
I did some experiments and I agree that this would be too much effort (and be too prone to specification changes) to modify the URI in flight. I will experiment with another approach which does not require the modifications.
