### ISSUE TITLE
Third-party module type annotation support

### ISSUE THREAD

**Issue by simon-ritchie** [krassowski/jupyterlab-lsp#12]
Hi.

If possible, it would be nicer to support completion of the third-party module 's type annotated object(e.g., pandas.DataFrame) :D

- built-in object annotation completion -> Worked:

![20190825_2](https://user-images.githubusercontent.com/25178045/63647077-3b26ee00-c757-11e9-8ea8-27e9f2544d5d.png)

- Self-defined original class -> Worked:

![20190825_7](https://user-images.githubusercontent.com/25178045/63647256-57c42580-c759-11e9-9170-42812d44692f.png)

- Third-party class -> Not invoked:

![20190825_5](https://user-images.githubusercontent.com/25178045/63647190-7fff5480-c758-11e9-82c7-40a160329195.png)

![20190825_6](https://user-images.githubusercontent.com/25178045/63647196-986f6f00-c758-11e9-8574-08f892a7a6ac.png)

Maybe this is a issue with the `python-language-server` library, not this extension.
If so, I'll close this.

Thx.

**Comment by krassowski** [comment]
Thanks for reporting this. I am not sure why it happens (it might be the python server fault, it may be a bug in my extension), but I will definitely investigate it in detail soon.

PS. If you use annotations a lot, have a look at [mypy extension](https://github.com/tomv564/pyls-mypy) of `python-language-server`:

```bash
pip install pyls-mypy
```

While it does not work as good as the PyCharm's implementation, it does help sometimes:

![Screenshot from 2019-08-25 11-10-44](https://user-images.githubusercontent.com/5832902/63648554-4d8a3300-c729-11e9-925c-d4a142ff8d6b.png)
![Screenshot from 2019-08-25 11-10-48](https://user-images.githubusercontent.com/5832902/63648555-4e22c980-c729-11e9-94ba-536dd184f754.png)

**Comment by simon-ritchie** [comment]
Hi, @krassowski 

Thanks a lot for your contributions and information (as well as mypy information)!

**Comment by simon-ritchie** [comment]
Hi.
For some reason I tried this extension today and it worked fine :O  

I tried:

- Downgraded ipython version to 7.2.0 and restarted node.js and JupyterLab

I noticed that the console had an error similar to the next issue, so I downgraded ipython yesterday.

```
...
/site-packages/jedi/api/classes.py", line 345, in params
 raise AttributeError('There are no params defined on this.')
AttributeError: There are no params defined on this.
```
> https://github.com/jupyter/notebook/issues/4364

And the error disappeared but did not improve.

- Installed mypy extension

As you told me, I installed `pyls-mypy`.  

- And today, when I start node.js and JupyterLab again, it works fine...

The reason is not well understood. Sorry :'-(  
(Maybe it's ipython, mypy, or some other influence...)

Notes: `np.array` etc. are completed quickly. On the other hand, `pd.DataFrame` seems to take a lot of time or become unstable. Perhaps the large DataFrame code is influencing.

![20190826_3](https://user-images.githubusercontent.com/25178045/63689052-e7de9980-c843-11e9-85a6-3e8ccd29362c.png)

I'll close this issue because it seems to be an effect of other libraries.
Thanks very much!

**Comment by simon-ritchie** [comment]
I'm not familiar with mypy and typeshed, but maybe type information is loaded with typeshed via mypy, as well as mypy's lint execution.

![20190826_4](https://user-images.githubusercontent.com/25178045/63691113-5540f900-c849-11e9-8c89-908538770b6a.png)
