### ISSUE TITLE
errors on startup

### ISSUE THREAD

**Issue by thomasd3** [krassowski/jupyterlab-lsp#121]
I get this several errors on startup, on MacOS.

I get this error when loading the project:

<pre>
[I 23:47:02.581 LabApp] Adapting from protocol version 5.1 (kernel 9ba721b5-a0a2-42ca-b2b1-acc8b07f9232) to 5.3 (client).
2019-12-23 23:47:03,745 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification textDocument/didChange: {'textDocument':...
</pre>

the initialization log (using --debug) can be found below:

<pre>
[thomas:~] $ jupyter lab --debug
[D 23:44:47.071 LabApp] Searching ['/Users/thomas', '/Users/thomas/.jupyter', '/Library/Frameworks/Python.framework/Versions/3.7/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 23:44:47.071 LabApp] Looking for jupyter_config in /etc/jupyter
[D 23:44:47.071 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 23:44:47.071 LabApp] Looking for jupyter_config in /Library/Frameworks/Python.framework/Versions/3.7/etc/jupyter
[D 23:44:47.071 LabApp] Looking for jupyter_config in /Users/thomas/.jupyter
[D 23:44:47.072 LabApp] Looking for jupyter_config in /Users/thomas
[D 23:44:47.072 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 23:44:47.072 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 23:44:47.073 LabApp] Looking for jupyter_notebook_config in /Library/Frameworks/Python.framework/Versions/3.7/etc/jupyter
[D 23:44:47.073 LabApp] Looking for jupyter_notebook_config in /Users/thomas/.jupyter
[D 23:44:47.073 LabApp] Looking for jupyter_notebook_config in /Users/thomas
[D 23:44:47.078 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 23:44:47.079 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 23:44:47.079 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/Library/Frameworks/Python.framework/Versions/3.7/etc/jupyter/jupyter_notebook_config.d/jupyter-lsp-serverextension.json
    	/Library/Frameworks/Python.framework/Versions/3.7/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/Library/Frameworks/Python.framework/Versions/3.7/etc/jupyter/jupyter_notebook_config.json
[D 23:44:47.080 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/thomas/.jupyter/jupyter_notebook_config.json
[D 23:44:47.490 LabApp] Checking for /Users/thomas/node_modules/bash-language-server/bin/main.js
[D 23:44:47.490 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/bash-language-server/bin/main.js
[D 23:44:47.490 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/bash-language-server/bin/main.js
[D 23:44:47.490 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/bash-language-server/bin/main.js
[W 23:44:47.490 LabApp] Failed to fetch commands from language server spec finder`bash-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.494 LabApp] Checking for /Users/thomas/node_modules/dockerfile-language-server-nodejs/lib/server.js
[D 23:44:47.494 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/dockerfile-language-server-nodejs/lib/server.js
[D 23:44:47.494 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/dockerfile-language-server-nodejs/lib/server.js
[D 23:44:47.494 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/dockerfile-language-server-nodejs/lib/server.js
[W 23:44:47.494 LabApp] Failed to fetch commands from language server spec finder`dockerfile-language-server-nodejs`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.497 LabApp] Checking for /Users/thomas/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js
[D 23:44:47.497 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js
[D 23:44:47.498 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js
[D 23:44:47.498 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js
[W 23:44:47.498 LabApp] Failed to fetch commands from language server spec finder`javascript-typescript-langserver`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.508 LabApp] Checking for /Users/thomas/node_modules/unified-language-server/src/server.js
[D 23:44:47.508 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/unified-language-server/src/server.js
[D 23:44:47.509 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/unified-language-server/src/server.js
[D 23:44:47.509 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/unified-language-server/src/server.js
[W 23:44:47.509 LabApp] Failed to fetch commands from language server spec finder`unified-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.512 LabApp] Checking for /Users/thomas/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[D 23:44:47.513 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[D 23:44:47.513 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[D 23:44:47.513 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/vscode-css-languageserver-bin/cssServerMain.js
[W 23:44:47.513 LabApp] Failed to fetch commands from language server spec finder`vscode-css-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.517 LabApp] Checking for /Users/thomas/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[D 23:44:47.517 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[D 23:44:47.517 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[D 23:44:47.518 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/vscode-html-languageserver-bin/htmlServerMain.js
[W 23:44:47.518 LabApp] Failed to fetch commands from language server spec finder`vscode-html-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.521 LabApp] Checking for /Users/thomas/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[D 23:44:47.522 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[D 23:44:47.522 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[D 23:44:47.522 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/vscode-json-languageserver-bin/jsonServerMain.js
[W 23:44:47.522 LabApp] Failed to fetch commands from language server spec finder`vscode-json-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.526 LabApp] Checking for /Users/thomas/node_modules/yaml-language-server/bin/yaml-language-server
[D 23:44:47.526 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab/staging/node_modules/yaml-language-server/bin/yaml-language-server
[D 23:44:47.526 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/lib/node_modules/yaml-language-server/bin/yaml-language-server
[D 23:44:47.526 LabApp] Checking for /Library/Frameworks/Python.framework/Versions/3.7/node_modules/yaml-language-server/bin/yaml-language-server
[W 23:44:47.526 LabApp] Failed to fetch commands from language server spec finder`yaml-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[D 23:44:47.527 LabApp] The following Language Servers will be available: {
      "pyls": {
        "argv": [
          "/Library/Frameworks/Python.framework/Versions/3.7/bin/pyls"
        ],
        "languages": [
          "python"
        ]
      }
    }
[I 23:44:47.773 LabApp] JupyterLab extension loaded from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyterlab
[I 23:44:47.773 LabApp] JupyterLab application directory is /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/lab
[D 23:44:48.005 LabApp] Yarn configuration loaded.
[I 23:44:48.008 LabApp] Serving notebooks from local directory: /Users/thomas
[I 23:44:48.008 LabApp] The Jupyter Notebook is running at:
[I 23:44:48.009 LabApp] http://localhost:8888/?token=5b4d303ddf5677a996b703ec53c3d1ef73df360024d1ce9c
[I 23:44:48.009 LabApp]  or http://127.0.0.1:8888/?token=5b4d303ddf5677a996b703ec53c3d1ef73df360024d1ce9c
[I 23:44:48.009 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
</pre>

**Comment by krassowski** [comment]
Hi @thomasd3. Thanks for reporting this. Could you please edit your post so that it follows the "Bug report" template, especially the piece with version numbers? Thanks

**Comment by thomasd3** [comment]
@krassowski, I made it more clear

**Comment by bollwyvl** [comment]
There are (and will continue to be) a lot of moving pieces. For that reason, re-opening a Bug Report issue and fully filling out all the version information would help us a lot.

Since we've gotten this far:

- Does the python language server work?
  - We have known outstanding issues with how pyls integrates with the approach to supporting notebooks, so some of those errors will be unavoidable, though most things will still _work_
- Are you expecting/needing any of the node-based language servers to work?
  - You'll likely have to follow some of the approaches suggested in the [documentation, such as it is](https://github.com/krassowski/jupyterlab-lsp/blob/master/LANGUAGESERVERS.md), including adding wherever you install your node stuff to `extra_node_roots`.

**Comment by ecolbinado** [comment]
Me too encountered the same issue **_"...expected str, bytes or os.PathLike object, not tuple"_**

Inside _types.py_ from ._..anaconda3/lib/python3.6/site-packages/jupyter_lsp/_ , I did the below edit from **node_roots** and **extra_node_roots** to attempt to fix it but failed. How do you advice resolve this?

```
node_roots = List_(["/usr/local/lib/node_modules"], help=_("absolute paths in which to seek node_modules")).tag(
        config=True
    )

    extra_node_roots = List_(
        ['/usr/local/lib/node_modules/vscode-css-languageserver-bin',
        '/usr/local/lib/node_modules/dockerfile-language-server-nodejs']
        , help=_("additional absolute paths to seek node_modules first")
    ).tag(config=True)
```

**Comment by bollwyvl** [comment]
@ecolbinado Since you're in `anaconda` already, I highly recommend `conda install -c conda-forge nodejs`, as the code knows where to find that. Otherwise, we're kinda guessing (and obviously not well enough).

As per the [documentation](https://github.com/krassowski/jupyterlab-lsp/blob/master/LANGUAGESERVERS.md#jupyter-config-via-traitlets), the configuration goes in your `jupyter_notebook_config.json`, not directly in `site-packages`, and should _not_ include the `node_modules` part:

Perhaps something like this:
```
{
  "LanguageServerManager": {
    "extra_node_roots": ["/usr/local/lib"]
  }
}
```

**Comment by ecolbinado** [comment]
I did the following steps: 
1.) Run `conda install -c conda-forge nodejs`
2.) Changed `{}` to 
```
{
  "LanguageServerManager": {
    "extra_node_roots": ["/usr/local/lib"]
  }
}
```
from `/Users/emilolbinado/anaconda3/pkgs/jupyterlab-0.32.1-py36_0/etc/jupyter/`

Same errors are appearing...
```
[W 07:03:38.696 LabApp] Failed to fetch commands from language server spec finder`bash-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[W 07:03:38.702 LabApp] Failed to fetch commands from language server spec finder`javascript-typescript-langserver`:
    expected str, bytes or os.PathLike object, not tuple
[W 07:03:38.713 LabApp] Failed to fetch commands from language server spec finder`unified-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[W 07:03:38.719 LabApp] Failed to fetch commands from language server spec finder`vscode-html-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 07:03:38.722 LabApp] Failed to fetch commands from language server spec finder`vscode-json-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 07:03:38.726 LabApp] Failed to fetch commands from language server spec finder`yaml-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[I 07:03:38.780 LabApp] JupyterLab extension loaded from /Users/emilolbinado/anaconda3/lib/python3.6/site-packages/jupyterlab
```

**Comment by bollwyvl** [comment]
So i'm still not sure where the os.Pathlike issues are coming from, but the
frontend components will not definitely work with jupyterlab 0.32: it's
only tested with jupyterlab 1.1.x and 1.2.x (where x is the latest
published version_.

**Comment by ecolbinado** [comment]
I pasted the incorrect path... I updated it now... 

I am currently using 1.1.4v
```
[emilolbinado@EMILs-MacBook-Pro.local ~]$ jupyter lab --version
1.1.4
```

**Comment by ecolbinado** [comment]
I was able to resolve my issue by completely uninstalling/removing nodejs and then reinstalling using conda. 

If anyone has a better answer to it you may share here. Thank you. [https://stackoverflow.com/questions/59386899/language-server-spec-finder-errors-when-launching-jupyter-lab/59712389#59712389](https://stackoverflow.com/questions/59386899/language-server-spec-finder-errors-when-launching-jupyter-lab/59712389#59712389)

**Comment by krassowski** [comment]
Thank you for getting back with the SO link! Closing this as solved, now tracking related installation docs improvements in #169.
