### ISSUE TITLE
Writing robot tests changing editor's content - issues with reset script

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#122]
If during a robot test a file is changed in the editor, and the file is not saved afterwards, all subsequent tests fail due to `Reset Application State`'s `Lab Command | Close All Tabs` failing due to:

![image](https://user-images.githubusercontent.com/5832902/71534630-03dc6f80-28f8-11ea-8f4b-2e57f95b56c0.png).

```
1) ElementClickInterceptedException: Message: Element <input class="p-CommandPalette-input"> is not clickable at point (138,47) because another element <div class="p-Widget jp-Dialog"> obscures it
2) ElementNotInteractableException: Message: Element <input class="p-CommandPalette-input"> is not reachable by keyboard
```

I think that there are two ways to solve this:
1. save the file before:
   - using shortcuts may be problematic as those may differ between Mac and other OSs
   - using `Lab Command` is slightly problematic as it changes between notebook and filetype (e.g. `Save Python File`)
2. Implementing checker for the dialogue widget:
   - easy if just one file requires the check (we can use `If`), not sure how to write a universal script (I heard that Robot has no `While`)

IMO (2) would be preferable, but I do not know how to do this. @bollwyvl I would appreciate your input. I can provide a working example of rename tests (this came out when writing those) with (1) as a workaround for you to experiment with.

**Comment by bollwyvl** [comment]
Yeah, there are certainly some challenges around "unasked for" behavior
like the unsaved dialog.

Deleting the file usually works, but the right click can be fussy (e.g you
have to mouse over the selector first, _then_ right click to get it to
appear). But then it can be easy to "miss" the thing you want.

The top bar menu items (e.g. file -> save) behave poorly, for similar
reasons, especially when nested.

While finicky, the keyboard shortcuts seem to be pretty reliable, if you're
pretty sure focus is in the right place. We do know a priori which os we
are on, so `${ACCEL} =  Set Variable If "${OS}" == "Darwin"  CMD   CTRL`
should already be available someplace, if not we can hoist it, and then
just `Press Keys   ${ACCEL}+s  body` our something like that _should_ work.

I'll take a look when back at the keyboard!

**Comment by bollwyvl** [comment]
Yeah, here's the line that defines ACCEL:

https://github.com/krassowski/jupyterlab-lsp/blob/2cfd62023d08494b8269ba0ef40bc1d0d6fd7fb3/atest/Keywords.robot

And here's an example of using it:

https://github.com/krassowski/jupyterlab-lsp/blob/2cfd62023d08494b8269ba0ef40bc1d0d6fd7fb3/atest/Keywords.robot

A "Save Current Document" keyword, combined with an enumeration of the
things we want saved, e.g "Get WebElements" would probably do the trick
with a FOR loop.

**Comment by bollwyvl** [comment]
I copied some of our work from this repo, and made some additional changes on this other thing I've been working on:

https://github.com/deathbeds/jupyterlab-starters/blob/master/atest/Keywords.robot

Having a few places where we click `.jp-Dialog .jp-mod-accept` (if it exists) a few times, and just trying the whole thing a few times would probably clear things up. But it would very much help to have some concrete failures to hack on!

**Comment by krassowski** [comment]
Side note: https://github.com/jupyterlab/jupyterlab/blob/72d9e17dadbd8c9e9869c863949e44b57a80120d/testutils/src/index.ts#L342 defines `dismissDialog` test utility.

**Comment by krassowski** [comment]
I uploaded my WIP rename tests (the JS tests need some cleanup + maany more tests cases) here: https://github.com/krassowski/jupyterlab-lsp/compare/rename_for_notebooks...rename_tests. If you remove `Lab Command   Save Python File` you can get a concrete failure to hack on.

**Comment by bollwyvl** [comment]
Yeah, appropriating these from `jupyterlab-starters`:

```patch
diff --git a/atest/Keywords.robot b/atest/Keywords.robot
index 642282c..1f5a9a7 100644
--- a/atest/Keywords.robot
+++ b/atest/Keywords.robot
@@ -69,11 +69,17 @@ Close JupyterLab
 
 Reset Application State
     Lab Command   Close All Tabs
+    Accept Default Dialog Option
     Ensure All Kernels Are Shut Down
     Lab Command   Reset Application State
     Wait For Splash
     Lab Command   Close All Tabs
 
+Accept Default Dialog Option
+    [Documentation]    Accept a dialog, if it exists
+    ${el} =    Get WebElements    ${CSS DIALOG OK}
+    Run Keyword If    ${el.__len__()}    Click Element    ${CSS DIALOG OK}
+
 Ensure All Kernels Are Shut Down
     Enter Command Name   Shut Down All Kernels
     ${els} =  Get WebElements   ${CMD PALETTE ITEM ACTIVE}

```

```diff
diff --git a/atest/Variables.robot b/atest/Variables.robot
index 2f9879a..cbcad4c 100644
--- a/atest/Variables.robot
+++ b/atest/Variables.robot
@@ -16,3 +16,4 @@ ${JLAB XP TOP}            //div[@id='jp-top-panel']
 ${JLAB XP MENU ITEM LABEL}  //div[@class='p-Menu-itemLabel']
 ${JLAB XP MENU LABEL}       //div[@class='p-MenuBar-itemLabel']
 ${JLAB CSS VERSION}    css:.jp-About-version
+${CSS DIALOG OK}    css:.jp-Dialog .jp-mod-accept
```

Pretty much takes care of the dialog issue... I also ended up bringing in `CodeMirror.robot` from `robotframework-jupyterlibrary`: I see you discovered some of the dirty tricks necessary to work with it, but their command API is quite solid.

**Comment by bollwyvl** [comment]
> defines dismissDialog test utility.

Yeah, I'm really loathe to try to bring in such things into acceptance tests: if the (fake) (power) user can't do it with keyboard and mouse, it's usually not worth testing. Luckily, lab has a pretty robust CSS contract, and usually more than one way to achieve something if "the right way" is flaky. I kinda gave up on the lab version stuff, to be sure, as those windows menus just weren't working, for whatever reason!

**Comment by krassowski** [comment]
Thank you, I committed your diff as 0d7d00a1ff534a83fc65ea847ed1766fbeea5160. Not sure if it will work when there are more than one dialogue windows, but let's not over-engineer by worrying ahead about cases that may not happen.

I will close this, for now, let's reopen if this problem resurfaces in the future.
