### ISSUE TITLE
Turn off warning diagnostics

### ISSUE THREAD

**Issue by austinmw** [krassowski/jupyterlab-lsp#128]
## What I am trying to do...

How can I turn off the pycodestyle warning diagnostic underlines (or alternative, maybe disable only specific pycodestyle E#'s)? Some of these are a bit too verbose for me.

## How I would like to learn how to do it...

I don't see any documentation for this or how to modify any settings.

**Comment by krassowski** [comment]
Thanks for writing. We plan to provide a configuration GUI at some time, but in the meantime, you can use the instructions on the [pyls](https://github.com/palantir/python-language-server) website (see [configuration](https://github.com/palantir/python-language-server#configuration)). For me on linux it simply meant creating a file called `~/.config/pycodestyle`; for my personal use I have the following settings:
```
[pycodestyle]
ignore = E402, E703
max-line-length = 120
```

E402 is to allow imports which are not on the very top of the file, E703 allows terminating semicolon (useful for matplotlib plots to prevent the object representation string).

For more check the [configuration section of pycodestyle documentation](https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration). They describe where the configuration file should be created on different OS (e.g. Windows) and options and error codes are there.

Generally, it is a good idea to read-up on the language servers by visiting their GitHub pages as there may be useful information (such as configuration, tricks, and known limitations).

I will close this issue but feel free to post any additional questions or feedback here, or reopen this issue if any problems with the configuration appear.

**Comment by bollwyvl** [comment]
Diagnostics follow some _pretty_ predictable patterns, and we've talked
about having an All The Diagnostics view. it wouldn't be _crazy_ to have
this be an UI entry point to "hide Diagnostics like this", with some basic
field matching (e.g. type, code, source, message regex, path glob), which
get stored in the lab config.

What this points to architecturally: it's worth looking at how tightly our
transport model is tied to our view model. We may need to think about ways
for such messages to be _hidden_ and not _destroyed_, as in the above page,
you'd want to see (at least) how many Diagnostics are hidden total, even if
you don't know which filter hides what. We wouldn't want to have this be
implemented anywhere near the actual codemirror stuff.

But generally... the documentation burden is pretty large on language
servers, especially ones with plugins, and it is not viable for this
project to document all of them.

What is probably a good idea in the near time is to have an optional
"doc_url" field (or family of fields) in the language server launcher spec
that would link to the upstream docs, and offer it in the UI: by making
them commands, in addition to wherever we might put it, the same url could
populate main menu "help" as well as the command palette. It can either
open it in an iframe, or open a new browser tab.

I'm wagering most servers would need a restart after changing config, and
some might refuse to start if misconfigured, which further raises the need
for capturing stderr from the servers and propagating them to the lab log
viewer.
