### ISSUE TITLE
Diagnostics panel does not show up in 0.7.0 beta

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#133]
It seems that minimization of the source causes the class (feature) names to be lost so we cannot access features by the original class name. Need to add the Feature.name: string field to the abstract class.

This is manifested by:
```
TypeError: Cannot read property 'switchDiagnosticsPanelSource' of undefined
```

**Comment by bollwyvl** [comment]
Eek. Guess we need to ensure we're testing against prod assets in CI

https://github.com/krassowski/jupyterlab-lsp/blob/master/ci/job.test.yml

As well as in the demo:

https://github.com/krassowski/jupyterlab-lsp/blob/master/postBuild

Will PR.

**Comment by krassowski** [comment]
Though about it, fortunately errors like this are not common (I knew that there was a risk of it when writing the code). However if it will not cause prolong the CI time, I all for it.

**Comment by bollwyvl** [comment]
It definitely _will_ take more time. We _could_ just do this on _some_ of the runs (e.g. linux), but the assurance of the installability of the extension(s) without error, especially on peril-fraught windows, is worth its weight in future, under-described support issues.
