### ISSUE TITLE
Disable `.` completion invoking at comment and docstring block

### ISSUE THREAD

**Issue by simon-ritchie** [krassowski/jupyterlab-lsp#15]
Currently, it seems that completion is invoked when enter a `.` in a comment or docstring block.

Comment example:

![20190827_2](https://user-images.githubusercontent.com/25178045/63768235-a6fd8800-c90a-11e9-81cc-39f74b44949f.png)

Docstring example:

![20190827_3](https://user-images.githubusercontent.com/25178045/63768284-cb596480-c90a-11e9-952f-6b0c0756fbc6.png)

**Comment by krassowski** [comment]
Fixed in 0.5.0-beta.5. I will be aiming for a new (non-beta) release before October.

**Comment by simon-ritchie** [comment]
Wow, thx a lot!
