### ISSUE TITLE
How to run specific browser tests only

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#151]
## What I am trying to do...

1. Run robot test for one test suite (`.robot` file) only, but not the others (since this is now possible thanks to #150)
2. Run a specific test case from this suite only

## How I would like to learn how to do it...

For (1) I tried `python scripts/atest.py -t 05_Features/Completion.robot` but it does not work as intended, I get:

```
attempt 1 of 1...
[ ERROR ] Suite 'Linux38' contains no tests matching name '05_Features/Completion.robot'.
```

I also tried a few answers from [SO](https://stackoverflow.com/q/25005277/6646912), but I guess that the ordering of arguments in our `atest.py` script may affect the ability to simply select one suite/case.

**Comment by bollwyvl** [comment]
The tests match on the English name under ***test cases***, to my
knowledge. But I always prefer tags, and include, which I was just using a
fair amount. But yeah, should have a doc example.
