### ISSUE TITLE
Start the Diagnostic Panel docked to the bottom

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#157]
## Motivation
Currently, the user has to drag the diagnostics panel to side or bottom after opening it.

## Design idea
The diagnostic panel should - by default - open on the bottom of the main area. Ideally, the panel should remember its position when it's opened again (at least within the single session, but once we have settings system could be even between sessions).

## How to implement
A similar behaviour is already implemented by "Create Console for Editor" command, and the implementation can be tracked down from [here](https://github.com/jupyterlab/jupyterlab/blob/736503eba4ea5a835ffbbcc37e8f06eb9d7b08fd/packages/fileeditor-extension/src/commands.ts#L114).

Also see https://gitter.im/jupyterlab/jupyterlab?at=5e1b6b2b0e65654fa0d07ed7.

**Comment by bollwyvl** [comment]
it's relatively straightforward to create a tracker, etc. that will
survive being restored. ILayoutRestorer is the key search phrase for the
jlab repo to find examples. When adding for the first time, you can also
specify:

app.shell.add(w, "main", {mode: "split-bottom"})

Personally: for (some of) the same reasons I won't usually have the status
bar open, I generally wouldn't want to offer up even 10% screen height to
my linter. would also like it to be banish/restorable to a sidebar.

**Comment by krassowski** [comment]
Not sure if I should clarify, but I meant "when the user decides to open the Diagnostics Panel" and not "automatically". But I agree that respecting the user's preferences is important; if this is as simple with `ILayoutRestorer`, let's do this.

Re moving it to the sidebar: sure, why not as an option. The content of the panel is a separate widget already, should be easy to implement (but I guess this would be a separate issue).

**Comment by krassowski** [comment]
Cross-referencing https://github.com/jupyterlab/jupyterlab/issues/5133 (@fcollonval thanks for pointing me to it).
