### ISSUE TITLE
How to configure pyls?

### ISSUE THREAD

**Issue by dynobo** [krassowski/jupyterlab-lsp#171]
## What I am trying to do...

... is to configure pyls (pycodestyle) to ignore some errors. If possible, I would like to disable pycodestyle completely and go only with pyflakes. (I use black as formatter, which produces a lot of "false positives" in pycodestyle)

## How I would like to learn how to do it...

It would be great to see an example of a more extensive jupyter-lab configuration for jupyterlab-lsp. So far the only example I  found is this generic "dummy"-snippet [here](https://github.com/krassowski/jupyterlab-lsp/blob/master/LANGUAGESERVERS.md#installing-language-servers):
```json
{
  "LanguageServerManager": {
    "language_servers": {
      "a-language-server-implementation": {
        "argv": ["/absolute/path/to/a-language-server", "--stdio"],
        "languages": ["a-language"]
      }
    }
  }
}
```

I have found the necessary pyls configuration [in this schema file](https://github.com/krassowski/jupyterlab-lsp/blob/master/py_src/jupyter_lsp/specs/config/pyls.schema.json), but I don't know if/how this can be integrated/overwritten using jupyter labs extensions settings.

Thanks!

**Comment by bollwyvl** [comment]
Thanks for making the issue!

The most robust way to configure pyls in particular is via config file:

https://github.com/palantir/python-language-server/blob/develop/README.rst#configuration

You can choose to put it in your $HOME, or into the directory where you
start the notebook server. Many of the plugins have their own config files,
while some can be merged together in a well-known file, e.g setup.cfg.

The stuff you found in the Schema is for The Future, where we make all of
those things configurable from the front end... but we aren't there yet.

We've talked about making a link to that page available from within the UI
(#128), as every single language server has a different scheme for config.
If some actually require cli config, we'll have to do some... Exciting
stuff to make it easy to configure. Right now, that would probably require
the entry_points approach.

**Comment by krassowski** [comment]
In particular, please check this: https://github.com/krassowski/jupyterlab-lsp/issues/128#issuecomment-570894117 and let us know if it helped you.

**Comment by dynobo** [comment]
Thx, @krassowski , setting the ignore in setup.cfg like you described worked for me :-)

Is it also possible to use flake8 or [pyls-black](https://pypi.org/project/pyls-black/) instead of pycodestyle? Or is this not possible yet?

The pls docu mentions I would have to set `"pyls.configurationSource": ["flake8"]` but I don't know where and if this is possible already.

BTW: Thanks for this useful extension! Love the autocomplete!

**Comment by krassowski** [comment]
I _think_ that switching to flake8 will require the configuration GUI, not sure if this can be achieved straightaway. I will try to expose some of the settings in the 0.8 release.

**Comment by dynobo** [comment]
Perfect, thanks!

**Comment by krassowski** [comment]
And happy that you enjoy it! Please do not hesitate to share this extension and [contribute](https://github.com/krassowski/jupyterlab-lsp/blob/master/CONTRIBUTING.md) (even small documentation improvements help a lot!).

**Comment by RobertoMaurizzi** [comment]
@dynobo from past experiences with `pyls` the best way to avoid running the checkers you want is to NOT install the others: when you install pyls, use `pip install python-language-server` instead of `pip install python-language-server[all]` then install only the checkers you need/want (i.e `pip install rope pyls-black` etc.).
Right now you can probably `pip uninstall pycodestyle` and any other plugin you know it is doing extra checks or changes you don't want.
