### ISSUE TITLE
Plenty of messages on notebook save KeyError: 'contentChanges'

### ISSUE THREAD

**Issue by myrgy** [krassowski/jupyterlab-lsp#185]
## Description
[lsp] error in listener <function setup_shadow_filesystem.<locals>.shadow_virtual_documents at 0x7f6c1fbb1320> for message {'jsonrpc': '2.0', 'method': 'textDocument/didSave', 'params': {'textDocument': {'uri':
...
}
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/jupyter_lsp/types.py", line 93, in __call__
        scope=scope, message=message, languages=languages, manager=manager
      File "/usr/local/lib/python3.7/site-packages/jupyter_lsp/virtual_documents_shadow.py", line 139, in shadow_virtual_documents
        changes = message['params']['contentChanges']
    KeyError: 'contentChanges'

## Reproduce

1. Press save button on any notebook
2. observe plenty of messages in output

## Context

- Operating System and version: Fedora 30
- Browser and version: Firefox 71
jupyter-client         5.3.4     
jupyter-core           4.6.1     
jupyter-lsp            0.7.0b0   
jupyterlab             1.2.6     
jupyterlab-server      1.0.6   
 @krassowski/jupyterlab-lsp v0.7.1  

In general even simple clicks produce plenty of messages.
It might be great to have a way to suppress it - I'm using cout to observe logs from native python module - as a result I have mix of lsp and my application.

```
{"jsonrpc":"2.0","id":17,"result":null}
{"jsonrpc":"2.0","id":18,"result":{"contents":""}}
{"jsonrpc":"2.0","id":19,"result":{"contents":""}}
{"jsonrpc":"2.0","id":20,"result":{"contents":""}}
{"jsonrpc":"2.0","id":21,"result":[{"range":{"start":{"line":121,"character":16},"end":{"line":121,"character":19}},"kind":3},{"range":{"start":{"line":124,"character":25},"end":{"line":124,"character":28}},"kind":2},{"range":{"start":{"line":128,"character":23},"end":{"line":128,"character":26}},"kind":2},{"range":{"start":{"line":128,"character":37},"end":{"line":128,"character":40}},"kind":2},{"range":{"start":{"line":130,"character":30},"end":{"line":130,"character":33}},"kind":2},{"range":{"start":{"line":134,"character":18},"end":{"line":134,"character":21}},"kind":2}]}
{"jsonrpc":"2.0","id":22,"result":{"contents":""}}
{"jsonrpc":"2.0","id":23,"result":null}
{"jsonrpc":"2.0","id":24,"result":{"contents":""}}
{"jsonrpc":"2.0","id":25,"result":null}
{"jsonrpc":"2.0","id":26,"result":{"contents":""}}
{"jsonrpc":"2.0","id":27,"result":null}
{"jsonrpc":"2.0","id":28,"result":{"contents":""}}
{"jsonrpc":"2.0","id":29,"result":{"contents":""}}
{"jsonrpc":"2.0","id":30,"result":{"contents":""}}
{"jsonrpc":"2.0","id":31,"result":null}
{"jsonrpc":"2.0","id":32,"result":{"contents":""}}
{"jsonrpc":"2.0","id":33,"result":{"contents":""}}
{"jsonrpc":"2.0","id":34,"result":{"contents":""}}
{"jsonrpc":"2.0","id":35,"result":null}
{"jsonrpc":"2.0","id":36,"result":null}
{"jsonrpc":"2.0","id":37,"result":{"contents":""}}
{"jsonrpc":"2.0","id":38,"result":{"contents":""}}
{"jsonrpc":"2.0","id":39,"result":{"contents":""}}
```

Thanks!

**Comment by krassowski** [comment]
Thanks! I have noticed this issue before (but truly, it's just an annoying message, no real impact on the LSP), will fix it. The messages at the bottom though are a different issue and I am not sure why you are seeing them... Those should be hidden by default, unless a debug mode is enabled (which is always for me, so I may have missed then). Will check that.

Anyway, many thanks for testing the extension and providing detailed feedback!
Any additional details will be greatly appreciated.

**Comment by myrgy** [comment]
I haven't enabled debug mode.
Just simple sudo pip3 install ....
