### ISSUE TITLE
Why might non-python/r notebooks require language server to speak "plain"?

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#189]
https://github.com/robocorp/robotframework-lsp/issues/13#issuecomment-582626037 identified that a spec must define `plain` for "off-the-beaten path" languages. 

Not flagging this as a bug _per se_: it could well be that it's not getting declared properly in Lab (as opposed to CM) in the syntax provider:
https://github.com/robots-from-jupyter/robotkernel/blob/master/src/jupyterlab_robotmode/src/mode.ts#L619

**Comment by krassowski** [comment]
Seems plausible... the language deduction in https://github.com/krassowski/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/src/adapters/jupyterlab/notebook.ts seems ok now...

I will have another look tomorrow.

**Comment by bollwyvl** [comment]
Checking it out on binder: got merged upstream pointing at `0.7.0`:

https://mybinder.org/v2/gh/robocorp/robotframework-lsp/master?urlpath=lab

**Comment by bollwyvl** [comment]
oh, here's the hard-coded thing I remember:

https://github.com/krassowski/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts#L92

I'll make an issue to use the mime type from server status...

**Comment by bollwyvl** [comment]
Mystery solved: that kernel was reporting itself as `text/plain`. If it had declared `text/x-robotframework` it would probably have worked as expected. #190 is still a good idea, but I think we can close this for now.
