### ISSUE TITLE
Document positioning system

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#209]
I spent quite some time trying to recollect what is the difference between the virtual, source (and root) and editor positioning.

Another important take-away is that we cannot drop the "source" positioning (which sometimes feels redundant) as this would cause problems when editors are added/moved/non-discoverable and it is generally easier to keep it rather than use (editor, editor position) tuple which often seems to be a nice alternative.

**Comment by bollwyvl** [comment]
:scream: this is why I let you handle this kind of stuff.

Do we need a type that we can hand around that encapsulates the combination of the two? Imaging `T` is the type of editor,

```
export interface IPosition<T> {
  source: <T>
  virtual: {line: number, col: number}
}
```

or am i overthinking it?

I've recently been digging into codemirror (embedded in prosemirror) yielding a document in prosemirror and trying to get line numbers/selections/scrolling to line up... and i'm not even imagining multiple languages... yet.

**Comment by krassowski** [comment]
Here we go:

![Screenshot from 2020-03-12 19-21-40](https://user-images.githubusercontent.com/5832902/76559262-c0c17f80-6496-11ea-8e9c-ac46973dfa78.png)

I will upload an svg version another time.

**Comment by krassowski** [comment]
And if one prefers code, we can refer to:

https://github.com/krassowski/jupyterlab-lsp/blob/21333276c7b16a9331c4e559ea6dbc39fbd998f8/packages/jupyterlab-lsp/src/virtual/document.spec.ts#L85-L210
