### ISSUE TITLE
Statusbar stuck in "Connecting..." state

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#214]
## Description

This might be why our Linux/Mac tests are failing - the status bar which we rely on for tests to go ahead seems to have an issue...

![Screenshot from 2020-03-12 15-50-41](https://user-images.githubusercontent.com/5832902/76539940-5ea65180-6479-11ea-979c-04657320d230.png)

## Reproduce

1. Open a Python notebook
2. LSP works great, but the status is stuck at "Connecting..."

## Expected behavior

Should change to "Fully initialized"

## Context

This might be a pyls issue?

The recently failing tests (on CI) are:
![Screenshot from 2020-03-12 15-55-33](https://user-images.githubusercontent.com/5832902/76540369-f99f2b80-6479-11ea-9190-c8235f107bfd.png)

- Operating System and version: Ubuntu 19.10
- JupyterLab version: 1.2.5
- `jupyter-lsp` version: 0.8.0
- `@krassowski/jupyterlab-lsp` version: 0.8.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by krassowski** [comment]
They had a release in Feb, maybe we should try pinning to the previous version?

Side note: there is now a spyder fork which might be of our interest: https://github.com/spyder-ide/spyder-pyls

**Comment by krassowski** [comment]
Warnings to be investigated:

![Screenshot from 2020-03-12 21-24-17](https://user-images.githubusercontent.com/5832902/76567994-e1460580-64a7-11ea-9fa8-8cc4996e137e.png)

![Screenshot from 2020-03-12 21-24-47](https://user-images.githubusercontent.com/5832902/76568033-f458d580-64a7-11ea-9221-a5b23d6e5c9e.png)

![Screenshot from 2020-03-12 21-24-47](https://user-images.githubusercontent.com/5832902/76568046-f884f300-64a7-11ea-99f5-78d65d9d92f9.png)

**Comment by bollwyvl** [comment]
Just did a clean install locally and a full run-through for #204, and everything looked fine... the "not in cell_line_map" is one of those things i had been chalking up to "we just catch with `console.warn`" when in fact it might be more serious. It's pretty hard to tell

In working #216 against master, i'll might uncover more stuff...

<details>
<summary><code>pip freeze</code>(as installed by conda)</summary>
<pre>
alabaster==0.7.12
appdirs==1.4.3
argh==0.26.2
astroid==2.3.3
attrs==19.3.0
autopep8==1.5
Babel==2.8.0
backcall==0.1.0
black==19.10b0
bleach==3.1.1
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
commonmark==0.9.1
coverage==5.0.3
cryptography==2.8
decorator==4.4.2
defusedxml==0.6.0
docutils==0.16
entrypoints==0.3
flake8==3.7.9
future==0.18.2
graphviz==0.13.2
html5lib==1.0.1
idna==2.9
imagesize==1.2.0
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.2
Jinja2==2.11.1
json5==0.9.0
jsonschema==3.2.0
jupyter-client==6.0.0
jupyter-core==4.6.3
-e git+git@github.com:bollwyvl/jupyterlab-lsp.git@ca4f288fec3b70765618acb7707966dc5a1578ee#egg=jupyter_lsp&subdirectory=../../jupyterlab-lsp
jupyterlab==2.0.1
jupyterlab-server==1.0.7
lazy-object-proxy==1.4.3
livereload==2.6.1
Markdown==3.0.1
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.2.0
mypy==0.770
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.0.4
nbsphinx==0.5.1
notebook==6.0.3
numpy==1.18.1
packaging==20.1
pandas==1.0.2
pandocfilters==1.4.2
parso==0.6.2
pathspec==0.7.0
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.12.0
port-for==0.4
prometheus-client==0.7.1
prompt-toolkit==3.0.4
psutil==5.7.0
ptyprocess==0.6.0
py==1.8.1
pycodestyle==2.5.0
pycparser==2.20
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.6.1
pylint==2.4.4
pyls-black==0.4.4
pyls-isort==0.1.1
pyls-mypy==0.1.8
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
pytest==5.3.5
pytest-asyncio==0.10.0
pytest-check-links==0.3.0
pytest-cov==2.8.1
pytest-flake8==1.0.4
pytest-runner==5.2
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
pytz==2019.3
PyYAML==5.3
pyzmq==19.0.0
recommonmark==0.6.0
regex==2020.2.20
requests==2.23.0
robotframework==3.1.2
robotframework-lint==1.0
robotframework-seleniumlibrary==4.3.0
rope==0.16.0
rpy2==3.1.0
ruamel-yaml==0.15.80
selenium==3.141.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.14.0
snowballstemmer==2.0.0
Sphinx==2.4.4
sphinx-autobuild==0.7.1
sphinx-autodoc-typehints==1.10.3
sphinx-copybutton==0.2.8
sphinx-markdown-tables==0.0.12
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
terminado==0.8.3
testpath==0.4.4
toml==0.10.0
tornado==6.0.4
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.1
tzlocal==2.0.0
ujson==1.35
urllib3==1.25.7
watchdog==0.10.2
wcwidth==0.1.8
webencodings==0.5.1
wrapt==1.12.1
yapf==0.29.0
zipp==3.1.0

</pre>
</details>

**Comment by krassowski** [comment]
Just been looking at this: https://github.com/palantir/python-language-server/issues/744 there is some Windows condition, so might be relevant..

**Comment by krassowski** [comment]
Just thinking that maybe we should remove `--quiet` from conda install?
