### ISSUE TITLE
Publish docs on readthedocs

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#216]
## Elevator Pitch

Publish the built docs on Read the Docs.

## Motivation

The current state of the docs is _meant_ to be built and published, but it just isn't yet. Even if we can't get everything they offer working, it's better than where we are: #211.

## Design Ideas

I'll do a test setup in a temporary project, get it working, and then we can make a new one that won't have all the "fix this, fix that" commits/builds, and hopefully it will work the first tiem.

Of late I've been running into more limitations when using conda there, which might limit the approach of "only document what works"... and their apt-provided nodejs (8) has been EOLed. Basically I've been using the (also old, but not compatible with our deps) nodejs from anaconda, and then doing everything with pip, but all of the r stuff is _right_ out.

So we might have to cheat, a bit, to get the data out without the servers actually _working_: definitely better to have the docs generated from the code that we test than to maintain it in both places, the whole motivation behind only checking in sources.

**Comment by bollwyvl** [comment]
Initial build at least installed and built in just over 2 minutes:
https://jlsptest.readthedocs.io

Unsurprisingly, it didn't find any servers:
https://jlsptest.readthedocs.io/en/latest/Language%20Servers.html

**Comment by bollwyvl** [comment]
graphviz worked, too: 
https://jlsptest.readthedocs.io/en/latest/Architecture.html

**Comment by bollwyvl** [comment]
got the node stuff to installed, but still errored, now getting some rate limiting... am also trying more aggressive cleaning locally regarding #214...

**Comment by bollwyvl** [comment]
oh wait, it did kind of work:
![Screenshot from 2020-03-12 21-03-16](https://user-images.githubusercontent.com/45380/76580066-ebb2d000-64a4-11ea-8cee-3341c09fa29d.png)

missed pyls (and obviously r-langauge-server...)

**Comment by krassowski** [comment]
I would say those are crucial ;)

**Comment by krassowski** [comment]
No sure if this is what limits you here, bu r lang server is going to drop some dependencies in the next release and reduce install size by 75% - should be easier to get it

**Comment by bollwyvl** [comment]
yeah, i know it's important to get the r stuff, but it's a _docs_ server, not a test server... i might need to throw in a `JUST_BUILDING_DOCS_DONT_CHECK_ERRORS_THANKS`, or hook at some other level than the manager.

**Comment by bollwyvl** [comment]
pyls is no problem, just waiting a bit before pushing

**Comment by bollwyvl** [comment]
ick:

```
    You can disable this feature by configuring > `autodetect <./Configuring.ipynb#autodetect>`__

```

**Comment by krassowski** [comment]
Yeah, might be easier to hardcode `R` instructions if its the only outlier

**Comment by bollwyvl** [comment]
Seems not unreasonable:

```diff
diff --git a/py_src/jupyter_lsp/specs/utils.py b/py_src/jupyter_lsp/specs/utils.py
index bf7b369..171f361 100644
--- a/py_src/jupyter_lsp/specs/utils.py
+++ b/py_src/jupyter_lsp/specs/utils.py
@@ -12,6 +12,9 @@ from ..types import (
 # helper scripts for known tricky language servers
 HELPERS = Path(__file__).parent / "helpers"
 
+# when building docs, let all specs go through
+BUILDING_DOCS = os.environ.get("JUPYTER_LSP_BUILDING_DOCS") is not None
+
 
 class SpecBase:
     """ Base for a spec finder that returns a spec for starting a language server
@@ -41,7 +44,7 @@ class ShellSpec(SpecBase):
             if cmd:
                 break
 
-        if not cmd:  # pragma: no cover
+        if not (cmd or BUILDING_DOCS):  # pragma: no cover
             return {}
 
         return {
@@ -65,7 +68,7 @@ class NodeModuleSpec(SpecBase):
     def __call__(self, mgr: LanguageServerManagerAPI) -> KeyedLanguageServerSpecs:
         node_module = mgr.find_node_module(self.node_module, *self.script)
 
-        if not node_module:  # pragma: no cover
+        if not (node_module or BUILDING_DOCS):  # pragma: no cover
             return {}
 
         return {

```

![Screenshot from 2020-03-12 21-14-38](https://user-images.githubusercontent.com/45380/76580626-fa9a8200-64a6-11ea-8a13-f544d5212f95.png)

**Comment by bollwyvl** [comment]
ha, defense in depth:
```
[IPKernelApp] WARNING | Failed to validate commands from language server spec finder`r-languageserver`:
[<ValidationError: "None is not of type 'string'">]
reading sources... [ 80%] Releasing

```

**Comment by bollwyvl** [comment]
![Screenshot from 2020-03-12 21-44-51](https://user-images.githubusercontent.com/45380/76581742-d2148700-64aa-11ea-83aa-aa684f698ade.png)

Taking another look through (blockquotes with links basically all seem broken) but pretty close to a PR: i think it will play out like:
- pr
- merge
- configure, build
- add links to master, maybe push a version of front end pointing at it
  - if so, cut a tag
- build
- call that `stable`

I don't know how i feel about `latest` pointing at `master`... i'd almost want to introduce a `dev` branch, but I find that kind hides where the "action" is from potential contributors, and we've gotten this far with just `master`. strategies welcome!

**Comment by bollwyvl** [comment]
Buh, indented lists broken? sad.

![Screenshot from 2020-03-12 21-50-28](https://user-images.githubusercontent.com/45380/76582026-89110280-64ab-11ea-9b48-fe7194c094f4.png)

**Comment by krassowski** [comment]
Let's point stick to latest = master + tag releases for now. Simpler is better.
