### ISSUE TITLE
Failing to install the extension

### ISSUE THREAD

**Issue by andreamoro** [krassowski/jupyterlab-lsp#234]
## Reproduce

Can't get the installation installed. Se log below if of any help

jupyter labextension install "@krassowski/jupyterlab-lsp" --debug                                                                                ✘
Searching ['/Applications/MEGAcmd.app/Contents/MacOS', '/Users/andreamoro/.jupyter', '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/etc/jupyter
Looking for jupyter_config in /Users/andreamoro/.jupyter
Looking for jupyter_config in /Applications/MEGAcmd.app/Contents/MacOS
Node v13.12.0

> /usr/local/bin/npm pack @krassowski/jupyterlab-lsp
\npm notice
npm notice 📦  @krassowski/jupyterlab-lsp@1.0.0
npm notice === Tarball Contents ===
npm notice 3.5kB  package.json
npm notice 1.5kB  LICENSE
npm notice 886B   lib/adapters/codemirror/cm_adapter.d.ts
npm notice 2.6kB  lib/adapters/codemirror/cm_adapter.js
npm notice 2.4kB  lib/adapters/codemirror/cm_adapter.js.map
npm notice 11B    lib/adapters/codemirror/cm_adapter.spec.d.ts
npm notice 2.1kB  lib/adapters/codemirror/cm_adapter.spec.js
npm notice 1.9kB  lib/adapters/codemirror/cm_adapter.spec.js.map
npm notice 5.0kB  lib/adapters/codemirror/feature.d.ts
npm notice 14.1kB lib/adapters/codemirror/feature.js
npm notice 11.1kB lib/adapters/codemirror/feature.js.map
npm notice 11B    lib/adapters/codemirror/feature.spec.d.ts
npm notice 10.4kB lib/adapters/codemirror/feature.spec.js
npm notice 8.0kB  lib/adapters/codemirror/feature.spec.js.map
npm notice 309B   lib/adapters/codemirror/features/completion.d.ts
npm notice 1.3kB  lib/adapters/codemirror/features/completion.js
npm notice 903B   lib/adapters/codemirror/features/completion.js.map
npm notice 2.6kB  lib/adapters/codemirror/features/diagnostics_listing.d.ts
npm notice 9.4kB  lib/adapters/codemirror/features/diagnostics_listing.js
npm notice 9.2kB  lib/adapters/codemirror/features/diagnostics_listing.js.map
npm notice 1.8kB  lib/adapters/codemirror/features/diagnostics.d.ts
npm notice 14.9kB lib/adapters/codemirror/features/diagnostics.js
npm notice 10.4kB lib/adapters/codemirror/features/diagnostics.js.map
npm notice 11B    lib/adapters/codemirror/features/diagnostics.spec.d.ts
npm notice 10.3kB lib/adapters/codemirror/features/diagnostics.spec.js
npm notice 8.7kB  lib/adapters/codemirror/features/diagnostics.spec.js.map
npm notice 591B   lib/adapters/codemirror/features/highlights.d.ts
npm notice 3.6kB  lib/adapters/codemirror/features/highlights.js
npm notice 2.9kB  lib/adapters/codemirror/features/highlights.js.map
npm notice 1.3kB  lib/adapters/codemirror/features/hover.d.ts
npm notice 7.9kB  lib/adapters/codemirror/features/hover.js
npm notice 5.8kB  lib/adapters/codemirror/features/hover.js.map
npm notice 599B   lib/adapters/codemirror/features/jump_to.d.ts
npm notice 4.9kB  lib/adapters/codemirror/features/jump_to.js
npm notice 3.5kB  lib/adapters/codemirror/features/jump_to.js.map
npm notice 350B   lib/adapters/codemirror/features/rename.d.ts
npm notice 4.3kB  lib/adapters/codemirror/features/rename.js
npm notice 3.4kB  lib/adapters/codemirror/features/rename.js.map
npm notice 11B    lib/adapters/codemirror/features/rename.spec.d.ts
npm notice 1.5kB  lib/adapters/codemirror/features/rename.spec.js
npm notice 1.6kB  lib/adapters/codemirror/features/rename.spec.js.map
npm notice 934B   lib/adapters/codemirror/features/signature.d.ts
npm notice 4.4kB  lib/adapters/codemirror/features/signature.js
npm notice 3.4kB  lib/adapters/codemirror/features/signature.js.map
npm notice 3.4kB  lib/adapters/codemirror/testutils.d.ts
npm notice 6.2kB  lib/adapters/codemirror/testutils.js
npm notice 5.6kB  lib/adapters/codemirror/testutils.js.map
npm notice 2.6kB  lib/adapters/jupyterlab/components/completion.d.ts
npm notice 12.2kB lib/adapters/jupyterlab/components/completion.js
npm notice 8.6kB  lib/adapters/jupyterlab/components/completion.js.map
npm notice 785B   lib/adapters/jupyterlab/components/free_tooltip.d.ts
npm notice 2.1kB  lib/adapters/jupyterlab/components/free_tooltip.js
npm notice 1.8kB  lib/adapters/jupyterlab/components/free_tooltip.js.map
npm notice 2.8kB  lib/adapters/jupyterlab/components/statusbar.d.ts
npm notice 16.6kB lib/adapters/jupyterlab/components/statusbar.js
npm notice 12.4kB lib/adapters/jupyterlab/components/statusbar.js.map
npm notice 1.6kB  lib/adapters/jupyterlab/file_editor.d.ts
npm notice 2.2kB  lib/adapters/jupyterlab/file_editor.js
npm notice 2.0kB  lib/adapters/jupyterlab/file_editor.js.map
npm notice 6.5kB  lib/adapters/jupyterlab/jl_adapter.d.ts
npm notice 16.7kB lib/adapters/jupyterlab/jl_adapter.js
npm notice 11.3kB lib/adapters/jupyterlab/jl_adapter.js.map
npm notice 2.2kB  lib/adapters/jupyterlab/notebook.d.ts
npm notice 5.6kB  lib/adapters/jupyterlab/notebook.js
npm notice 4.8kB  lib/adapters/jupyterlab/notebook.js.map
npm notice 3.6kB  lib/command_manager.d.ts
npm notice 6.7kB  lib/command_manager.js
npm notice 5.5kB  lib/command_manager.js.map
npm notice 11B    lib/command_manager.spec.d.ts
npm notice 1.8kB  lib/command_manager.spec.js
npm notice 1.9kB  lib/command_manager.spec.js.map
npm notice 3.4kB  lib/connection_manager.d.ts
npm notice 10.5kB lib/connection_manager.js
npm notice 7.9kB  lib/connection_manager.js.map
npm notice 962B   lib/connection.d.ts
npm notice 2.8kB  lib/connection.js
npm notice 2.6kB  lib/connection.js.map
npm notice 497B   lib/converter.d.ts
npm notice 480B   lib/converter.js
npm notice 629B   lib/converter.js.map
npm notice 134B   lib/extractors/defaults.d.ts
npm notice 4.2kB  lib/extractors/defaults.js
npm notice 2.9kB  lib/extractors/defaults.js.map
npm notice 11B    lib/extractors/defaults.spec.d.ts
npm notice 4.0kB  lib/extractors/defaults.spec.js
npm notice 3.8kB  lib/extractors/defaults.spec.js.map
npm notice 2.6kB  lib/extractors/regexp.d.ts
npm notice 3.4kB  lib/extractors/regexp.js
npm notice 2.8kB  lib/extractors/regexp.js.map
npm notice 11B    lib/extractors/regexp.spec.d.ts
npm notice 7.6kB  lib/extractors/regexp.spec.js
npm notice 7.0kB  lib/extractors/regexp.spec.js.map
npm notice 2.3kB  lib/extractors/types.d.ts
npm notice 33B    lib/extractors/types.js
npm notice 116B   lib/extractors/types.js.map
npm notice 257B   lib/index.d.ts
npm notice 8.5kB  lib/index.js
npm notice 6.1kB  lib/index.js.map
npm notice 1.7kB  lib/lsp.d.ts
npm notice 2.8kB  lib/lsp.js
npm notice 1.8kB  lib/lsp.js.map
npm notice 581B   lib/magics/defaults.d.ts
npm notice 5.1kB  lib/magics/defaults.js
npm notice 3.2kB  lib/magics/defaults.js.map
npm notice 11B    lib/magics/defaults.spec.d.ts
npm notice 4.2kB  lib/magics/defaults.spec.js
npm notice 3.4kB  lib/magics/defaults.spec.js.map
npm notice 1.1kB  lib/magics/maps.d.ts
npm notice 1.7kB  lib/magics/maps.js
npm notice 1.8kB  lib/magics/maps.js.map
npm notice 532B   lib/magics/overrides.d.ts
npm notice 37B    lib/magics/overrides.js
npm notice 120B   lib/magics/overrides.js.map
npm notice 707B   lib/magics/rpy2.d.ts
npm notice 2.7kB  lib/magics/rpy2.js
npm notice 2.9kB  lib/magics/rpy2.js.map
npm notice 11B    lib/magics/rpy2.spec.d.ts
npm notice 3.9kB  lib/magics/rpy2.spec.js
npm notice 3.4kB  lib/magics/rpy2.spec.js.map
npm notice 642B   lib/manager.d.ts
npm notice 2.1kB  lib/manager.js
npm notice 2.2kB  lib/manager.js.map
npm notice 856B   lib/positioning.d.ts
npm notice 1.1kB  lib/positioning.js
npm notice 1.1kB  lib/positioning.js.map
npm notice 11B    lib/positioning.spec.d.ts
npm notice 2.8kB  lib/positioning.spec.js
npm notice 3.8kB  lib/positioning.spec.js.map
npm notice 879B   lib/tokens.d.ts
npm notice 210B   lib/tokens.js
npm notice 220B   lib/tokens.js.map
npm notice 1.3kB  lib/utils.d.ts
npm notice 3.4kB  lib/utils.js
npm notice 2.8kB  lib/utils.js.map
npm notice 734B   lib/virtual/console.d.ts
npm notice 1.4kB  lib/virtual/console.js
npm notice 1.7kB  lib/virtual/console.js.map
npm notice 8.0kB  lib/virtual/document.d.ts
npm notice 21.2kB lib/virtual/document.js
npm notice 15.9kB lib/virtual/document.js.map
npm notice 11B    lib/virtual/document.spec.d.ts
npm notice 8.1kB  lib/virtual/document.spec.js
npm notice 6.4kB  lib/virtual/document.spec.js.map
npm notice 4.4kB  lib/virtual/editor.d.ts
npm notice 6.7kB  lib/virtual/editor.js
npm notice 4.6kB  lib/virtual/editor.js.map
npm notice 11B    lib/virtual/editor.spec.d.ts
npm notice 5.6kB  lib/virtual/editor.spec.js
npm notice 4.9kB  lib/virtual/editor.spec.js.map
npm notice 946B   lib/virtual/editors/file_editor.d.ts
npm notice 1.7kB  lib/virtual/editors/file_editor.js
npm notice 1.5kB  lib/virtual/editors/file_editor.js.map
npm notice 3.7kB  lib/virtual/editors/notebook.d.ts
npm notice 9.3kB  lib/virtual/editors/notebook.js
npm notice 8.2kB  lib/virtual/editors/notebook.js.map
npm notice 678B   schema/plugin.json
npm notice 7.0kB  src/_schema.d.ts
npm notice 2.3kB  src/adapters/codemirror/cm_adapter.spec.ts
npm notice 2.8kB  src/adapters/codemirror/cm_adapter.ts
npm notice 9.6kB  src/adapters/codemirror/feature.spec.ts
npm notice 16.4kB src/adapters/codemirror/feature.ts
npm notice 1.3kB  src/adapters/codemirror/features/completion.ts
npm notice 10.0kB src/adapters/codemirror/features/diagnostics_listing.tsx
npm notice 9.0kB  src/adapters/codemirror/features/diagnostics.spec.ts
npm notice 14.8kB src/adapters/codemirror/features/diagnostics.ts
npm notice 3.4kB  src/adapters/codemirror/features/highlights.ts
npm notice 8.1kB  src/adapters/codemirror/features/hover.ts
npm notice 4.6kB  src/adapters/codemirror/features/jump_to.ts
npm notice 1.4kB  src/adapters/codemirror/features/rename.spec.ts
npm notice 4.4kB  src/adapters/codemirror/features/rename.ts
npm notice 4.4kB  src/adapters/codemirror/features/signature.ts
npm notice 7.4kB  src/adapters/codemirror/testutils.ts
npm notice 13.6kB src/adapters/jupyterlab/components/completion.ts
npm notice 2.4kB  src/adapters/jupyterlab/components/free_tooltip.ts
npm notice 16.2kB src/adapters/jupyterlab/components/statusbar.tsx
npm notice 3.1kB  src/adapters/jupyterlab/file_editor.ts
npm notice 18.6kB src/adapters/jupyterlab/jl_adapter.ts
npm notice 6.6kB  src/adapters/jupyterlab/notebook.ts
npm notice 68B    src/babel.config.js
npm notice 1.9kB  src/command_manager.spec.ts
npm notice 7.7kB  src/command_manager.ts
npm notice 11.9kB src/connection_manager.ts
npm notice 3.5kB  src/connection.ts
npm notice 743B   src/converter.ts
npm notice 3.9kB  src/extractors/defaults.spec.ts
npm notice 3.8kB  src/extractors/defaults.ts
npm notice 6.8kB  src/extractors/regexp.spec.ts
npm notice 5.5kB  src/extractors/regexp.ts
npm notice 2.3kB  src/extractors/types.ts
npm notice 8.6kB  src/index.ts
npm notice 2.2kB  src/lsp.ts
npm notice 4.0kB  src/magics/defaults.spec.ts
npm notice 4.5kB  src/magics/defaults.ts
npm notice 2.1kB  src/magics/maps.ts
npm notice 516B   src/magics/overrides.ts
npm notice 3.6kB  src/magics/rpy2.spec.ts
npm notice 2.5kB  src/magics/rpy2.ts
npm notice 2.2kB  src/manager.ts
npm notice 2.6kB  src/positioning.spec.ts
npm notice 1.6kB  src/positioning.ts
npm notice 845B   src/tokens.ts
npm notice 166B   src/typings.d.ts
npm notice 3.3kB  src/utils.ts
npm notice 1.7kB  src/virtual/console.ts
npm notice 8.0kB  src/virtual/document.spec.ts
npm notice 24.3kB src/virtual/document.ts
npm notice 6.0kB  src/virtual/editor.spec.ts
npm notice 8.4kB  src/virtual/editor.ts
npm notice 2.2kB  src/virtual/editors/file_editor.ts
npm notice 11.2kB src/virtual/editors/notebook.ts
npm notice 423B   style/console.css
npm notice 1.7kB  style/diagnostics_listing.css
npm notice 1.1kB  style/index.css
npm notice 1.9kB  style/statusbar.css
npm notice === Tarball Details ===
npm notice name:          @krassowski/jupyterlab-lsp
npm notice version:       1.0.0
npm notice filename:      krassowski-jupyterlab-lsp-1.0.0.tgz
npm notice package size:  207.0 kB
npm notice unpacked size: 919.2 kB
npm notice shasum:        299d41ee2fd4a0d19138e88338de6e500e25b374
npm notice integrity:     sha512-mk7JN8Vn33s7s[...]JJ/t8DersTnJQ==
npm notice total files:   214
npm notice
krassowski-jupyterlab-lsp-1.0.0.tgz

Node v13.12.0

Building jupyterlab assets (build:prod:minimize)
> node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
|yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
[4/5] Linking dependencies...
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/application@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/apputils@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/cells@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/codeeditor@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/codemirror@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/completer@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/coreutils@~4.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/docmanager@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/docregistry@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/fileeditor@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/notebook@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/rendermime@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/services@~5.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/statusbar@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency "@jupyterlab/tooltip@~2.0.0".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has unmet peer dependency "@lumino/algorithm@*".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has unmet peer dependency "@lumino/widgets@*".
warning " > @krassowski/jupyterlab-lsp@1.0.0" has unmet peer dependency "codemirror@*".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/application@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/apputils@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/codeeditor@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/codemirror@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/coreutils@~4.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/docmanager@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/docregistry@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/fileeditor@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/notebook@~2.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/observables@~3.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has incorrect peer dependency "@jupyterlab/services@~5.0.0".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has unmet peer dependency "@lumino/algorithm@*".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition@1.0.0" has unmet peer dependency "codemirror@*".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 5.05s.

> node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
-yarn run v1.15.2
$ /usr/local/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 1.24s.

> node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
|yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/settingregistry' in '/usr/local/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib'
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /usr/local/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /usr/local/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
resolve '@jupyterlab/settingregistry' in '/usr/local/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib'
  Parsed request is a module
  using description file: /usr/local/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /usr/local/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/node_modules doesn't exist or is not a directory
      /usr/local/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules doesn't exist or is not a directory
      /usr/local/share/jupyter/lab/staging/node_modules/@krassowski/node_modules doesn't exist or is not a directory
      /usr/local/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /usr/local/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /usr/local/share/jupyter/node_modules doesn't exist or is not a directory
      /usr/local/share/node_modules doesn't exist or is not a directory
      /usr/local/node_modules doesn't exist or is not a directory
      /usr/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /usr/local/share/jupyter/lab/staging/node_modules
        using description file: /usr/local/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /usr/local/share/jupyter/lab/staging/package.json (relative path: ./node_modules/@jupyterlab/settingregistry)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry.json doesn't exist
            as directory
              /usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/settingregistry doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    core_config=self.core_config)

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 583, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/0d/hg55dgvx1t9g8vqv9vc4sl9c0000gn/T/jupyterlab-debug-4f9v2sky.log
Exiting application: jupyter

**Comment by krassowski** [comment]
Dear @andreamoro, thank you for opening this issue. Guessing from the logs:

```
 warning " > @krassowski/jupyterlab-lsp@1.0.0" has incorrect peer dependency
"@jupyterlab/application@~2.0.0".
```

I would say that you attempt to install the version of this extension dedicated for JupyterLab 2.0 on a different version of JupyterLab. However, as you did not follow the issue template, I cannot say more at this point. Please follow the instructions from the template to provide all the information that we need in order to answer this query.

**Comment by krassowski** [comment]
If you use JupyterLab 1.0 please install the older version as specified in the README:

![Screenshot from 2020-03-29 13-56-08](https://user-images.githubusercontent.com/5832902/77849711-8ad60800-71c5-11ea-8a0d-bb7f86b02362.png)

**Comment by andreamoro** [comment]
I'm using Jupiter lab 2.0. where did you get 1.0?
I wonder if there's some clash around

**Comment by andreamoro** [comment]
Ok, it ended up to be a problem of mine, as I believe that system was up to date but it was not. Everything seems to work as intended.
