### ISSUE TITLE
Auto-complete issue related to file paths

### ISSUE THREAD

**Issue by ProblemFactory** [krassowski/jupyterlab-lsp#241]
## Description

When using jupyterlab-lsp, the file path autocomplete in str stops working. Also, sometimes it will automatically add useless .ipynb_checkpoints.

## Reproduce

Issue 1:
1. type `'/'` (including quote)  in any notebook's code cell 
2. then press TAB after `/`.
3. Nothing happens.

Issue 2:
1. Go to any cell, type in the following code:
```
from scipy.io import loadmat
data = loadmat('/path/to/some/.mat/file')[0]
```
2. type `.` after `[0]`
3. `ipynb_checkpoints` will be appended after `.` symbol.

## Expected behavior

Issue 1:
A list of files/folders should pop out for selection.

Issue 2:
Nothing should happen or a valid completion.

## Context

- Operating System and version: Windows 10 Pro x64 Version 1909
- Browser and version: Chrome 80.0.3987.149
- JupyterLab version: 2.0.1
- `jupyter-lsp` version: 0.8.0
- `@krassowski/jupyterlab-lsp` version: 1.0.0

**Comment by antonwnk** [comment]
I second both these. While the first one didn't strike me as an issue necessarily (don't know whether I should expect some path completion to begin or not), the second issue is very annoying.
It happens when I type `.` on an empty line and whenever I put square brackets _for indexing_. 
I.e. 
```
[].   # no completion
existing_or_undefined_variable[].  # completes with .ipynb_checkpoints/
existing_or_undefined_variable[.]  # completes with .ipynb_checkpoints/ even if dot is typed inside
```

**Comment by krassowski** [comment]
Thank you @ProblemFactory for reporting and thanks @antonwnk for providing additional examples - it was useful for creating a test case!

I started working on that, and most of the annoying behaviour should be gone in the next release; most likely ETA in two weeks time.

**Comment by antonwnk** [comment]
Seems you have it covered! Thanks a lot.

**Comment by krassowski** [comment]
This has been fixed upstream in JupyterLab. If there will be JupyterLab 2.2 release, it will likely be included in it. Otherwise it will be in JupyterLab 3.0
