### ISSUE TITLE
Conda recipe creation

### ISSUE THREAD

**Issue by fcollonval** [krassowski/jupyterlab-lsp#242]
I would like to create a conda recipe on conda-forge to distribute this extension.

Would you like to be added as maintainer of the package?
If the dependencies do not change, this should mean only accepting automatic PR as soon as a new version lands on pypi.org.
 
This will probably ease the installation process for conda users.

**Comment by krassowski** [comment]
Great idea, sure!

**Comment by bollwyvl** [comment]
Go ahead, add me, too. I've been intending to do this for a while.

I think we're going to want some custom outputs, e.g
jupyterlab-lsp-with-python, jupyterlab-lsp-with-r that pin to versions of
pyls/r-language server that we know work.

I haven't gotten around to trying to sanely package the nodejs-based ones,
but they are also a particularly obnoxious thing to get right
cross-platform, and conda would be great for, but npm is bad. Ideally, we'd
figure out how to use webpack or something and make each one of them a
single script, a la yarn.

Let's _not_ put the labextension directly in place in the conda package as
e.g jupyterlab-git does... If anything, we'd want a jupyterlab-lsp-prebuilt
that shipped all built assets as an alternate command or configurable.

**Comment by krassowski** [comment]
@fcollonval thank you for the work on this, greatly appreciated! I think that we should add a note in our docs that it is now possible to install from conda and then we close this issue?

**Comment by fcollonval** [comment]
You're welcome. Yes it is on my to-do list 😉
