### ISSUE TITLE
JDK installation 

### ISSUE THREAD

**Issue by JTebeka** [krassowski/jupyterlab-lsp#252]
After installing lsp and when I launch jupyterLab 2.1.1 from Anaconda, I have a message that ask me to install a JDK to use Java. JupyterLab is launching and seems to work fine and when I close the little window asking me to install JDK, everything is ok. 

1. Go to anaconda 
2. Click on Jupyterlab 2.1.1
3. See message about JDK 
- Operating System and version: macOS Catalina 10.15.4
- Browser and version:
- JupyterLab version: 2.1.1
- `jupyter-lsp` version: 0.8.0
- `@krassowski/jupyterlab-lsp` version: 

<img width="1260" alt="Capture d’écran 2020-04-24 à 18 03 34" src="https://user-images.githubusercontent.com/49912455/80233047-29834680-8656-11ea-9df1-f8e9d29f3202.png">

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by krassowski** [comment]
@fcollonval, could this JDK message be coming from conda-forge for jupyterlab-lsp?

**Comment by fcollonval** [comment]
jupyter-lsp has not yet been published to conda-forge.

@JTebeka could you launch JupyterLab from the Anaconda prompt to get log messages.

**Comment by JTebeka** [comment]
I launched jupyterLab from Terminal from Anaconda (is it what you asked me ?). 
First when I did it, I again get the previous message that asked me to install the JDK to use java and on the terminal I had this :

Last login: Fri Apr 24 18:15:51 on ttys001
. /Users/jacques/opt/anaconda3/bin/activate && conda activate /Users/jacques/opt/anaconda3/envs/DataAnalysis; 
(base) jacques@MBP-de-Jacques ~ % . /Users/jacques/opt/anaconda3/bin/activate && conda activate /Users/jacques/opt/anaconda3/envs/DataAnalysis; 
(DataAnalysis) jacques@x86_64-apple-darwin13 ~ % jupyter lab
[I 15:01:38.399 LabApp] The port 8888 is already in use, trying another port.
[I 15:01:38.400 LabApp] The port 8889 is already in use, trying another port.
[I 15:01:38.400 LabApp] The port 8890 is already in use, trying another port.
[I 15:01:38.401 LabApp] The port 8891 is already in use, trying another port.
[I 15:01:38.401 LabApp] The port 8892 is already in use, trying another port.
[I 15:01:39.073 LabApp] JupyterLab extension loaded from /Users/jacques/opt/anaconda3/envs/DataAnalysis/lib/python3.7/site-packages/jupyterlab
[I 15:01:39.073 LabApp] JupyterLab application directory is /Users/jacques/opt/anaconda3/envs/DataAnalysis/share/jupyter/lab
Installing jupyterlab_autoversion handler on path /autoversion
Installing jupyterlab_autoversion handler on path /autoversion
Installing jupyterlab_autoversion handler on path /autoversion
Installing jupyterlab_autoversion handler on path /autoversion
[I 15:01:39.364 LabApp] Serving notebooks from local directory: /Users/jacques/Projets
[I 15:01:39.364 LabApp] The Jupyter Notebook is running at:
[I 15:01:39.364 LabApp] http://localhost:8959/?token=457c48b53baaa7022541e8553e035eda130e1907708ab069
[I 15:01:39.364 LabApp]  or http://127.0.0.1:8959/?token=457c48b53baaa7022541e8553e035eda130e1907708ab069
[I 15:01:39.364 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:01:39.374 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jacques/Library/Jupyter/runtime/nbserver-97974-open.html
    Or copy and paste one of these URLs:
        http://localhost:8959/?token=457c48b53baaa7022541e8553e035eda130e1907708ab069
     or http://127.0.0.1:8959/?token=457c48b53baaa7022541e8553e035eda130e1907708ab069
[I 15:01:42.650 LabApp] Build is up to date
[I 15:01:43.076 LabApp] Kernel started: 8b8edbe6-b497-46fa-a54a-9eb0cf6f5171
[W 15:01:43.531 LabApp] Got events for closed stream None
\

**Comment by JTebeka** [comment]
What is strange is that on other terminal from an other environment I have :
(Analysis) jacques@MBP-de-Jacques ~ % 
whereas with this special environment with Jupyterlab2 and LSP I have : 
(DataAnalysis) jacques@x86_64-apple-darwin13 ~ % 

I did nothing to have this. Isn't it the origin of the problem ?

**Comment by fcollonval** [comment]
Thanks for the log trace. There is unfortunately nothing useful in it 😞 

Indeed the hostname should not be changed... And if I understand correctly, MacOS is prompting with the message when activating the environment or is it when executing `jupyter lab`?

**Comment by JTebeka** [comment]
Yes. Correct. I have an error message in that case. 
I created a new environment and I do not have anymore this message on this new one. 
I can't find the origin of the previous error message. 
What I did with the previous environment was to create it from an other one (where everything was fine).

**Comment by fcollonval** [comment]
It seems to be related to conda environment creation and activation rather than this extension.

I'm glad to hear that you succeed to get around it.

**Comment by JTebeka** [comment]
Thanks.
