### ISSUE TITLE
Minimal function descriptions

### ISSUE THREAD

**Issue by msmicker** [krassowski/jupyterlab-lsp#253]
## Description

After installation, I am getting minimal function descriptions. e.g. For pandas read_csv - I get this : FunctionType(*args: Any, **kwargs: Any). There also seems to be a delay - e.g. can take several seconds.

This was basically a fresh install of jupyter lab I made yesterday.
conda create -p jupyterlab
conda activate jupyterlab
conda install -c conda-forge -y jupyterlab nodejs dask dask-jobqueue dask-labextension fastparquet pyarrow python-snappy qgrid
\# tried from conda and pip - currently using pip install of these
\# conda install -c conda-forge -y python-language-server r-languageserver
conda install -c anaconda -y cx_oracle pivottablejs scipy
conda install -c bioconda -y pronto
pip install pronto jupyter-lsp ontoma python-language-server[all]
jupyter labextension install dask-labextension
jupyter labextension install @krassowski/jupyterlab-lsp
R -e 'install.packages("languageserver")'

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: Windows 10 & Centos 7
- Browser and version: Chrome 81
- JupyterLab version: jupyterlab                2.1.1                      py_0    conda-forge
- `jupyter-lsp` version: jupyter-lsp               0.8.0                    pypi_0    pypi
- `@krassowski/jupyterlab-lsp` version: @krassowski/jupyterlab-lsp v1.0.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
{kind: "markdown", value: "```ipython↵FunctionType(*args: Any, **kwargs: Any) -> Any↵```"}
kind: "markdown"
value: "```ipython↵FunctionType(*args: Any, **kwargs: Any) -> Any↵```"
</pre>
</details>

**Comment by krassowski** [comment]
Thanks for the feedback @msmicker. Could you please include a screenshot, or ideally a gif demonstrating this behaviour?

**Comment by krassowski** [comment]
I think that you meant this:

![Screenshot from 2020-04-26 19-22-56](https://user-images.githubusercontent.com/5832902/80316084-9d0e8a80-87f3-11ea-9ea4-90cbeae36497.png)

What is displayed is not decided by this extension but by the server that you use. You could try a different server for Python (Microsoft has two), or open an issue in pyls repository.

**Comment by krassowski** [comment]
As a sanity check, it works ok for other objects from pandas:

![Screenshot from 2020-04-26 19-31-18](https://user-images.githubusercontent.com/5832902/80316265-b82dca00-87f4-11ea-94d7-dd514e6daf94.png)

I am closing it for now, as this is an upstream issue. Again, thank you for reporting it and carefully describing the problem - please feel free to add comments if you manage to narrow down the problem with pyls or succeed with another LSP server - this might be useful insight for other users.

**Comment by msmicker** [comment]
Thanks, I assumed something was off since also the df.aggregate( produced a similarly minimal function signature:
MethodType(*args: Any, **kwargs: Any) -> Any

But in the docs/screenshot it shows more (axis param, etc).

Somehow I was not even aware that shift-tab should also show function signatures? At one point I had a detailed read_csv function signature but now I can't reproduce! In any case, I may find some time to explore and will post back if I find anything relevant.

**Comment by msmicker** [comment]
fyi, this is what I was seeing previously - and had somehow been unaware of. It is not using lsp, but I understand core functionality? I was restarting the server multiple times previously and I believe this relies on the kernel being activates.

![image](https://user-images.githubusercontent.com/15576857/80320066-2d43d400-87e2-11ea-820f-a1d11fab10e9.png)

**Comment by krassowski** [comment]
Yes, <kbd>shift</kbd>+<kbd>tab</kbd> does not use static analysis, but objects living in the kernel and is a core (not LSP) function.
