### ISSUE TITLE
/docs/LANGUAGESERVERS.md missing

### ISSUE THREAD

**Issue by jhgoebbert** [krassowski/jupyterlab-lsp#254]
Hi, 
thank you for this great extension.

When you click on the status bar where one can see the language servers, this includes a Link called"Documentation: Language Server".  

This link is dead, as it points to  
https://github.com/krassowski/jupyterlab-lsp/blob/master/docs/LANGUAGESERVERS.md  
which does not exist.

Best regards,
Jens Henrik

**Comment by krassowski** [comment]
Hi Jens,

Thanks for highlighting this. I think that we should point to https://jupyterlab-lsp.readthedocs.io/en/latest/Language%20Servers.html
