### ISSUE TITLE
changing shortcuts

### ISSUE THREAD

**Issue by LukaPitamic** [krassowski/jupyterlab-lsp#267]
How do I change default **F2** and **CMD + B** keybindings? Especially **CMD + B** is by default used by Jupyter Lab to toggle left side-bar.

Thank you,
and great job!
I'm loving it!

**Comment by krassowski** [comment]
`Settings` → `Advanced Settings Editor` → choose `Keyboard Shortcuts` pane → search for `lsp:` prefix. If you do not know how to use the advanced settings editor, have a look in the jupyterlab documentation or install shortcuts UI extension.

**Comment by krassowski** [comment]
Please re-open if it does not work and thanks enjoy the extension!
