### ISSUE TITLE
How to set pyls.configurationSources for flake8

### ISSUE THREAD

**Issue by mborsetti** [krassowski/jupyterlab-lsp#280]
The `[python-language-server](https://github.com/palantir/python-language-server)` says:

> The default configuration source is pycodestyle. Change the pyls.configurationSources setting to ['flake8'] in order to respect flake8 configuration instead.

How do you set pyls.configurationSources in `jupyterlab-lsp`?

**Comment by krassowski** [comment]
Hi @mborsetti, thanks for checking our extension. This will be supported once #245 is merged (I would like to say "soon", but probably it will not happen this weekend yet).
