### ISSUE TITLE
Installation docs show two diff versions of jupyterlab

### ISSUE THREAD

**Issue by choldgraf** [krassowski/jupyterlab-lsp#289]
The README shows this for prerequisites:

![image](https://user-images.githubusercontent.com/1839645/86936927-7de58080-c0f3-11ea-97b7-8566ddca689e.png)

and this for the installation commands:

![image](https://user-images.githubusercontent.com/1839645/86936960-876ee880-c0f3-11ea-8bdd-08dd1210e950.png)

Could you advise which it is? And then I am happy to make a PR that changes it

**Comment by bollwyvl** [comment]
One of the in-flight PRs fixes it... But PRs always welcome!

Presently, it works and is tested with both the 2.0 and 2.1 line. If/when
lab 2.2 drops, future releases of the extension will require that to fix
some outstanding issues around completion, I believe.
