### ISSUE TITLE
%%latex doesn't show diagnostics

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#296]
## Description

On #288, even when configured (as below), the `%%latex` magic doesn't show diagnostics from `chktex`.

## Reproduce

- configure the plugin with 
```json
{"language_servers": {"texlab": {"serverSettings": {"latex.lint.onChange": true}}}}
```
- open `atest/examples/Foreign extractors.ipynb`
- open the diagnostic panel
- do not see any `chktex` warnings

- #288

## Expected behavior

Should see a `chktex` diagnostic

## Context

- Operating System and version: All Azure CI, but also local ubuntu 20.04
- Browser and version: chromium and firefox
- JupyterLab version: 2.1.5 and 2.2.0

**Comment by krassowski** [comment]
Cross-referencing my comments on the PR: it does work but not for notebooks which have space in the filename. See https://github.com/krassowski/jupyterlab-lsp/pull/288#issuecomment-663909088 and the following comments.

It seems that others have experienced related issues: https://www.mail-archive.com/bug-auctex@gnu.org/msg03622.html
(but I am not sure how closely it relates to our situation).

Is there any place in jupyter-lsp where we could escape spaces in filenames but we don't?
