### ISSUE TITLE
Improve syntax highlighting in the cells with cell magics

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#298]
## What are you trying to do?

Currently, JupyterLab does not highlight syntax properly for cells fully occupied by a foreign language (syntax of the language of the notebook is used instead). It can be easily improved upon, changing the mode of the CodeMirror editor for that cell. This is already being done by the jumper, but it only takes place when it is activated:

https://github.com/krassowski/jupyterlab-lsp/blob/a46f3a8620a5e6460333850bd3fdb324870399b9/packages/jupyterlab-go-to-definition/src/jumpers/jumper.ts#L100-L110

Instead, it should be rewritten to take advantage of the cell magics mechanism that we already have in jupyterlab-lsp.

Ultimately, it would be perfect to operate on per-foreign extractor basis (which can be on a scope lower than a cell - just some lines or characters) but mixed modes do not seem to be supported by CodeMirror just yet (except for [html-css-js-etc mixed mode](https://codemirror.net/mode/htmlmixed/index.html))

**Comment by krassowski** [comment]
Well, actually the codemirror docs just encourage to implement mixed modes on your own using `mixed-mode HTML mode` as an example:

> Sometimes, it is useful for modes to nest—to have one mode delegate work to another mode. An example of this kind of mode is the mixed-mode HTML mode. To implement such nesting, it is usually necessary to create mode objects and copy states yourself. To create a mode object, there are CodeMirror.getMode(options, parserConfig), where the first argument is a configuration object as passed to the mode constructor function, and the second argument is a mode specification as in the mode option. To copy a state object, call CodeMirror.copyState(mode, state), where mode is the mode that created the given state.
>
> To make indentation work properly in a nested parser, it is advisable to give the startState method of modes that are intended to be nested an optional argument that provides the base indentation for the block of code. The JavaScript and CSS parser do this, for example, to allow JavaScript and CSS code inside the mixed-mode HTML mode to be properly indented.

And the source code seems concise and easy to grasp: https://www.sendeco2.com/base/resources/javascript/CodeMirror2/mode/htmlmixed/htmlmixed.js

It does seem easy to use the foreign extractor-provided position data to with a custom mode then :)

**Comment by bollwyvl** [comment]
Yeah, the nesting stuff is _great_, when it works... the simplest way i have found to get it is with [simple mode](https://codemirror.net/demo/simplemode.html
), specifically the `mode` option.

Because these are plain-old-JSON (plus regex, but also accepts strings),  we could fairly confidently make a fully dynamic mode... we're already doing a lot of stuff to these codemirrors. About all we'd have to do is extend all the extractor defs with the codemirror mode we want.

**Comment by bollwyvl** [comment]
Here's a previous thing i did with simple mode, https://github.com/deathbeds/jupyterlab-simple-syntax, which eventually resulted in a PR to core (to make mode registration lazier), but I didn't get around to rebooting in Lab 1+ (much less 2+). Syntax modes as mime outputs is still really cute, though.

**Comment by krassowski** [comment]
> About all we'd have to do is extend all the extractor defs with the codemirror mode we want.

There should be a way to get the mimetype - CodeMirror mapping. It will require some experimentation as to what is more reliable.

**Comment by bollwyvl** [comment]
It's true, the `CodeMirror.detectMode` or whatever _usually_ works with mime types as registered. I just usually like to be sure. 

What simple mode _isn't_ going to give us is the reverse-translcusion, e.g. `{var}`... that's a whole other kettle of fish.
