### ISSUE TITLE
Code completion sometimes overwrites existing text 

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#30]
Happens only when completing a code symbol which is in the middle of a line (not at the end). Needs unit tests to prevent this in the future.

Example:
`DataFrame(da<tab>)` leads to `DataFrame(dta=)`, should `DataFrame(data=)`

R examples:
`data.frame(row.nam<tab>` → `data.frame(row.nrow.names`
`data.f<tab>` → `data.fdata.frame`

**Comment by krassowski** [comment]
Minimal Python example without the need to import anything:

```
CamelCase = 1
mean(cam<tab>
```

**Comment by krassowski** [comment]
Another test case: `from jupyter_helpers.tabl<tab>`

**Comment by krassowski** [comment]
```python
def display_table():
    pass

disp<tab>data
```
leads to
`ddisplay_table`

**Comment by yunair** [comment]
I don't think this is a valid test case
``` python
def display_table():
    pass

disp<tab>data
```

Python doesn't support to  write code like this

**Comment by krassowski** [comment]
Some explanations: I use `<tab>` to indicate invocation of the completer with <kbd>tab</kbd> key and `<cursor>` to indicate the expected position of cursor (thus the code is valid).

**Comment by krassowski** [comment]
The `from jupyter_helpers.tabl<tab>` can be reproduced in bare Python with:

`from os.pat<tab>` → choose `path` or `os.path`; the result expected for both is `from os.path`, but the latter produces `os.os.path`. This is because the kernel returns prefixed tokens (with `os.`), while LSP (pyls) does not (and we can handle either prefixed responses or non-prefixed responses, but not both mixed together, due to how the completer in JupyterLab is written).

- we cannot detect the prefix from kernel response alone
- we have to take a look at the token preceding the requested token.

**Comment by krassowski** [comment]
Even more nicer test case `from os.pathse<tab>` → `from os.pathsep`.

I now got fixes for every case reported so far, will PR soon.
