### ISSUE TITLE
Choose and then add icons for the completion items

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#303]
Completion items list can now use items, as implemented in https://github.com/jupyterlab/jupyterlab/pull/8140. We should take use of that as this is very low-effort high-gain feature. Currently the first letter and a colour code is used to indicate completion type. It will make it easier and more efficient to choose the right completion.

Costs:
- We need to bring the icons. The types/icon set is well defined by the LSP specification.

Potential icons:
- [gnvim](https://github.com/vhakulinen/gnvim/tree/master/assets/icons) uses feather which is MIT
- official [VSCode](https://github.com/microsoft/vscode-icons) icons are release under CC BY 4.0
   - some users will like it
   - we would need to think where to put the attribution - I do not see a good place for it...
- any other options?

**Please do propose other options and discuss** - this is the kind of issue anyone can get involved in - no extension coding skills required!

**Comment by bollwyvl** [comment]
Behold, the iconpocalypse!

Lab uses mostly material icons, so that might be an harmonious look, overall.

Agreed that anybody can get this started , but I'm very definitely willing to help out on any grunt work to actually get it loaded, once they are in place.

This might be a good time to bring our own icon in as well (selfishly, i want one for the LSP kernel, as well) I've completely lost wherever i had the original design, but we can bring that back, too, and re-cook it to make it more harmonious.

> where to put the attribution - I do not see a good place for it...

I don't think _About_ is extensible, but we could make our own command/menu item that pops a (generated) markdown file. The other thing is to just leave the attribution in the icons themselves, they would be visible from view source, which is as good a UI as any.

**Comment by bollwyvl** [comment]
It would also be interesting if we could use these icons in the hover UI, if it already pulls the type, etc.

**Comment by krassowski** [comment]
Material would be ok, ideally all from the same collection (of the same author). But to be honest, I could not find a suitable icon's set.

Here are the completion kinds that we would want to cover:

| Kind | VSC | material? |
|:---|:----:|---|
|Text|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-string.svg?sanitize=true' />|
|Method|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-method.svg?sanitize=true' />|
|Function|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-method.svg?sanitize=true' />|
|Constructor|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-method.svg?sanitize=true' />|
|Field|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-field.svg?sanitize=true' />|
|Variable|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-variable.svg?sanitize=true' />|
|Class|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-class.svg?sanitize=true' />|
|Interface|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-interface.svg?sanitize=true' />|
|Module|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/json.svg?sanitize=true' />|
|Property|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-property.svg?sanitize=true' />|
|Unit|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-ruler.svg?sanitize=true' />|
|Value|?|
|Enum|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-enumerator.svg?sanitize=true' />|
|Keyword|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-keyword.svg?sanitize=true' />|
|Snippet|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-snippet.svg?sanitize=true' />|
|Color|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-color.svg?sanitize=true' />|
|File|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/file.svg?sanitize=true' />|
|Reference|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/references.svg?sanitize=true' />|
|Folder|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/folder.svg?sanitize=true' />|
|EnumMember|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-enumerator-member.svg?sanitize=true' />|
|Constant|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-constant.svg?sanitize=true' />|
|Struct|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-structure.svg?sanitize=true' />|
|Event|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-event.svg?sanitize=true' />|
|Operator|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-operator.svg?sanitize=true' />|
|TypeParameter|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/symbol-parameter.svg?sanitize=true' />|

For VSCode I used this reference: https://code.visualstudio.com/api/references/icons-in-labels

**Comment by bollwyvl** [comment]
I guess the high road would be to consider if there is any ISO/OMG standard for this kind of iconography. Probably would have to buy it, lol.

What I note about many of these: they are very much informed by microsoft language typography (c#, ts). Perhaps if we make it work once, we could consider allowing a spec to override specific symbols.

Also, i feel like method, function, and constructor all being the same is a wasted opportunity.

Maybe we toss up to discourse?
