### ISSUE TITLE
All Robot tests started failing on Linux on CI

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#308]
With the message:

```
Parent suite setup failed:
SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

Which seems to be connected to selenium/firefox/gecko, see:
- https://stackoverflow.com/questions/43713445/selenium-unable-to-find-a-matching-set-of-capabilities-despite-driver-being-in
= https://stackoverflow.com/questions/47782650/selenium-common-exceptions-sessionnotcreatedexception-message-unable-to-find-a/47785513

### Linux:

> firefox                   79.0                 he1b5a44_1    conda-forge
> selenium                  3.141.0         py36h8c4c3a4_1001
> robotframework-seleniumlibrary 4.5.0              pyh9f0ad1d_0    conda-forge

### MacOS

> firefox                   78.0esr              h4a8c4bd_0    conda-forge
> selenium                  3.141.0         py36h37b9a7d_1001    conda-forge
> robotframework-seleniumlibrary 4.5.0              pyh9f0ad1d_0    conda-forge

### Windows

> firefox                   79.0                 ha925a31_1    conda-forge
> selenium 3.141.0 py36h8c4c3a4_1001
> robotframework-seleniumlibrary 4.5.0 pyh9f0ad1d_0 conda-forge

@bollwyvl any ideas?

**Comment by bollwyvl** [comment]
oof. i'll take a look.

**Comment by bollwyvl** [comment]
Ah. `geckodriver 0.27.0` will now no longer accept any-old-`firefox`... it has to actually point at a _real_ firefox binary. Will have a patch up presently.
