### ISSUE TITLE
LSP Servers always Connecting...

### ISSUE THREAD

**Issue by walidsi** [krassowski/jupyterlab-lsp#310]
Hi,

I followed the instructions at https://jupyterlab-lsp.readthedocs.io/en/latest/Installation.html in order to get jupyterlab-lsp up and running. Installation steps were successful without errors but upon opening a notebook in juypter lab, I noticed that the LSP Servers status is always "Connecting..."

![image](https://user-images.githubusercontent.com/42148514/89716285-02a21380-d9ac-11ea-9eae-32aba223854c.png)

What is wrong please? and how can I get it to work?

**Comment by krassowski** [comment]
I think it is all ok (I see that you got the code diagnostics/linting) for
Python, I think that it says "connecting" because it cannot find JavaScript
language server. I will investigate.

**Comment by EnchoC** [comment]
![image](https://user-images.githubusercontent.com/28055454/90272011-52db1300-de8f-11ea-8c9d-3f07837a6062.png)

Me too, server connecting。。

**Comment by krassowski** [comment]
Thank you for the reports it should be fixed in the 2.0 version (to be released today).

**Comment by walidsi** [comment]
Thanks for the update. How do I upgrade to version 2.0?

**Comment by walidsi** [comment]
> 
> 
> Thank you for the reports it should be fixed in the 2.0 version (to be released today).

Thanks for the update. How do I upgrade to version 2.0? I tried removing everything and installing again but it seems v0.9 is still the one that gets installed.

**Comment by krassowski** [comment]
Sorry for the delay, I have not released it yet, waiting for #328. @bollwyvl do you need a hand with testing, or maybe should I go ahead and make a release now?

**Comment by bollwyvl** [comment]
Sorry for the delay, I have not released it yet, waiting for #328
> <https://github.com/krassowski/jupyterlab-lsp/pull/328>. @bollwyvl
> <https://github.com/bollwyvl> do you need a hand with testing, or maybe
> should I go ahead and make a release now?
>
Sorry, was heads-down on a talk the last couple days.

Haven't had the chance to start the tests, and agree it's a little weird to
just have one feature configurable. Go ahead and release, we'll fix it in
post!

>

**Comment by krassowski** [comment]
@walidsi you can update now with:

```
pip install jupyter-lsp==0.9.2
jupyter labextension install @krassowski/jupyterlab-lsp@2.0.0
```

Summary of changes: https://github.com/krassowski/jupyterlab-lsp/releases/tag/v2.0.0 (and more in the changelog). Please let us know how it works for you.

**Comment by stefaneidelloth** [comment]
Have this issue for current version 2.0.8
How can I check the availability of the python language server from the console?
