### ISSUE TITLE
jupyterlab-lsp and jupyterhub

### ISSUE THREAD

**Issue by djangoliv** [krassowski/jupyterlab-lsp#32]
First: thanks a lot for this awesome work @krassowski and thanks too for your PR @bollwyvl.

I installed jupyterlab-lsp on jupyterhub (with dockerspawner) and [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy/).

For that, I use two things from @bollwyvl 's PR:
- Add the schema file (require for install)
- And replace (in src/adapters/jupyterlab.ts): 
   `let socket = new WebSocket('ws://localhost:3000/' + language);`
    by 
```
    const wsBase = PageConfig.getBaseUrl().replace(/^http/, '');
    const wsUrl = `ws${wsBase}lsp/${language}`;
    let socket = new WebSocket(wsUrl);
```
And it works !!! So thanks a lot again !!

Some improvement ideas:
- make a script to open a file from command line: https://github.com/jupyterlab/jupyterlab/issues/5056
- Add shortcuts to allow the user to not use the mouse

Regards

**Comment by krassowski** [comment]
Thank you for your feedback! The shortcuts for each command are a good idea - will be added in future.

**Comment by krassowski** [comment]
Hi @djangoliv! We got a new version published silently (it includes the PR you mention). Would you mind checking if it works for your use-case of JupyterHub?

**Comment by djangoliv** [comment]
Hi @krassowski,
I tried the new version on dockerSpawner with success. Thanks a lot.
I will try with KubeSpawner soon and I'll keep you informed.

**Comment by djangoliv** [comment]
Hi @krassowski and @bollwyvl 

Thanks for your work and your encouragement.
I also managed to use the extension with kubespawner without any difficulty.
It's very comfortable not to have to manage the jupyter-proxy project myself.
I will continue to test the different versions of your work in my environments. I'll let you know.

Thanks a lot again for your awesome extension.

**Comment by djangoliv** [comment]
Hi you can close this issue. I use your extension in production for a while without problems.
Thanks for your work.

**Comment by krassowski** [comment]
Great to hear that - thank you for the update :)
