### ISSUE TITLE
Add support for an SQL langauge server

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#325]
- [ ] decide which server to use
  - https://github.com/joe-re/sql-language-server seems good first choice as it is an npm package; it is not clear which features it supports (but clearly it does support diagnostics and completion),
  - https://github.com/lighttiger2505/sqls is a nice alternative, but written in go and might slow down our CI; also it does not support diagnostics yet,
  - https://github.com/microsoft/vscode-mssql/ is a no go as it supports a single dialect only.
- [ ] allow the extractors to pass language-specific arguments to the connection initialization params see https://github.com/krassowski/jupyterlab-lsp/pull/321#issuecomment-683190128

**Comment by bollwyvl** [comment]
Looks like the node one works with sqlite (with a config file) so should
have minimal impact, and would be very useful.

I'm kinda wondering if the org we target might be something more general
like "jupyter-languages"... We're starting to stack up kernels, syntax
highlighting, etc. that don't all fall strictly under the lsp banner...
