### ISSUE TITLE
TexLab Not Working

### ISSUE THREAD

**Issue by BrandenEsses** [krassowski/jupyterlab-lsp#337]
## Description

I toook your advice @krassowski, and took a look at jupyterlab-lsp. This is really amazing work!

The extension shows the presence and full initialization of texlab, however the extension appears to not function. It works flawlessly with Python though. This is reproduced in the browser console output below, but this is the first thing I noticed is that the console complains:
<pre>
 feature.js:7 @krassowski/jupyterlab-lsp:signature settings schema could not be found and was not loaded
$e @ feature.js:7
feature.js:7 @krassowski/jupyterlab-lsp:highlights settings schema could not be found and was not loaded
$e @ feature.js:7
</pre>
## Reproduce

1. Open a .tex file in JupyterLab
2. The first command line error appears
3. Begin interacting with the LaTEX code
4. The errors regarding jsonrpc appear

## Expected behavior

I expected to see highlighting and function signatures.

## Context

- Operating System and version: Ubuntu 20.04.1 LTS
- Browser and version: Google Chrome 85.0.4183.83
- JupyterLab version: 2.2.6

<details><summary>Required: installed server extensions</summary>
<pre>
config dir: /root/.jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.6 OK
    jupyter_lsp  enabled
    - Validating...
      jupyter_lsp 0.9.2 OK
config dir: /usr/etc/jupyter
    jupyter_lsp  enabled
    - Validating...
      jupyter_lsp 0.9.2 OK
    jupyterlab_latex  enabled
    - Validating...
      jupyterlab_latex 2.0.0 OK
config dir: /usr/local/etc/jupyter
    jupyter_lsp  enabled
    - Validating...
      jupyter_lsp 0.9.2 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.6 OK
    jupyterlab_latex  enabled
    - Validating...
      jupyterlab_latex 2.0.0 OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v2.2.6
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyterlab/latex v2.0.1  enabled  OK
        @krassowski/jupyterlab-lsp v2.0.0  enabled  OK
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /usr/local/texlive/2020/bin/x86_64-linux
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /snap/bin

sys.path:
        /usr/local/bin
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /usr/local/lib/python3.8/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.8.2 (default, Jul 16 2020, 14:00:26)
        [GCC 9.3.0]

platform.platform():
        Linux-5.4.0-45-generic-x86_64-with-glibc2.29

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package                      Version
        ---------------------------- --------------------
        acme                         1.1.0
        aiohttp                      3.6.2
        alembic                      1.4.2
        apturl                       0.5.2
        astroid                      2.4.2
        async-generator              1.10
        async-timeout                3.0.1
        attrs                        19.3.0
        Automat                      0.8.0
        autopep8                     1.5.4
        backcall                     0.2.0
        bleach                       3.1.5
        blinker                      1.4
        certbot                      0.40.0
        certbot-apache               0.39.0
        certifi                      2020.6.20
        certipy                      0.1.3
        chardet                      3.0.4
        Click                        7.0
        cloud-init                   20.2
        colorama                     0.4.3
        command-not-found            0.3
        ConfigArgParse               0.13.0
        configobj                    5.0.6
        constantly                   15.1.0
        cryptography                 2.8
        cupshelpers                  1.0
        cycler                       0.10.0
        dbus-python                  1.2.16
        decorator                    4.4.2
        defer                        1.0.6
        defusedxml                   0.6.0
        distro                       1.4.0
        distro-info                  0.23ubuntu1
        dnspython                    1.16.0
        duplicity                    0.8.12.0
        entrypoints                  0.3
        fasteners                    0.14.1
        flake8                       3.8.3
        future                       0.18.2
        gpg                          1.13.1-unknown
        httplib2                     0.14.0
        hyperlink                    19.0.0
        idna                         2.8
        importlib-metadata           1.5.0
        incremental                  16.10.1
        ipykernel                    5.3.3
        ipython                      7.16.1
        ipython-genutils             0.2.0
        ipywidgets                   7.5.1
        isort                        5.5.1
        jedi                         0.17.2
        Jinja2                       2.10.1
        josepy                       1.2.0
        json5                        0.9.5
        jsonpatch                    1.22
        jsonpointer                  2.0
        jsonrpc                      1.2
        jsonschema                   3.2.0
        jupyter-client               6.1.6
        jupyter-core                 4.6.3
        jupyter-lsp                  0.9.2
        jupyter-telemetry            0.1.0
        jupyterhub                   1.1.0
        jupyterhub-ldapauthenticator 1.3.0
        jupyterlab                   2.2.6
        jupyterlab-latex             2.0.0
        jupyterlab-server            1.2.0
        keyring                      18.0.1
        kiwisolver                   1.2.0
        language-selector            0.1
        launchpadlib                 1.10.13
        lazr.restfulclient           0.14.2
        lazr.uri                     1.0.3
        lazy-object-proxy            1.4.3
        ldap3                        2.8
        lockfile                     0.12.2
        macaroonbakery               1.3.1
        Mako                         1.1.3
        Markdown                     3.1.1
        MarkupSafe                   1.1.0
        matplotlib                   3.3.1
        mccabe                       0.6.1
        mistune                      0.8.4
        mock                         3.0.5
        monotonic                    1.5
        more-itertools               4.2.0
        mpmath                       1.1.0
        multidict                    4.7.6
        nbconvert                    5.6.1
        nbformat                     5.0.7
        netifaces                    0.10.4
        notebook                     6.0.3
        numpy                        1.19.1
        oauthlib                     3.1.0
        olefile                      0.46
        packaging                    20.3
        pamela                       1.0.0
        pandas                       1.1.1
        pandocfilters                1.4.2
        parsedatetime                2.4
        parso                        0.7.1
        pbr                          5.4.5
        pexpect                      4.8.0
        pickleshare                  0.7.5
        Pillow                       7.2.0
        pip                          20.0.2
        pluggy                       0.13.1
        prometheus-client            0.8.0
        prompt-toolkit               3.0.6
        protobuf                     3.6.1
        psutil                       5.5.1
        ptyprocess                   0.6.0
        pyasn1                       0.4.8
        pyasn1-modules               0.2.1
        pycairo                      1.16.2
        pycodestyle                  2.6.0
        pycrypto                     2.6.1
        pycups                       1.9.73
        pydocstyle                   5.1.1
        pyflakes                     2.2.0
        Pygments                     2.3.1
        pygments-mathematica         0.3.4
        PyGObject                    3.36.0
        PyHamcrest                   1.9.0
        PyICU                        2.4.2
        PyJWT                        1.7.1
        pylint                       2.6.0
        pymacaroons                  0.13.0
        PyNaCl                       1.3.0
        pyOpenSSL                    19.0.0
        pyparsing                    2.4.6
        pyRFC3339                    1.1
        pyrsistent                   0.15.5
        pyserial                     3.4
        python-apt                   2.0.0+ubuntu0.20.4.1
        python-augeas                0.5.0
        python-dateutil              2.8.1
        python-debian                0.1.36ubuntu1
        python-editor                1.0.4
        python-json-logger           0.1.11
        python-jsonrpc-server        0.3.4
        python-language-server       0.34.1
        python-magic                 0.4.18
        pytz                         2019.3
        pyxdg                        0.26
        PyYAML                       5.3.1
        pyzmq                        19.0.2
        qtconsole                    4.7.5
        QtPy                         1.9.0
        reportlab                    3.5.34
        requests                     2.22.0
        requests-toolbelt            0.8.0
        requests-unixsocket          0.2.0
        rope                         0.17.0
        ruamel.yaml                  0.16.10
        ruamel.yaml.clib             0.2.0
        scipy                        1.5.2
        screen-resolution-extra      0.0.0
        SecretStorage                2.3.1
        Send2Trash                   1.5.0
        service-identity             18.1.0
        setuptools                   45.2.0
        simpervisor                  0.3
        simplejson                   3.16.0
        six                          1.14.0
        snowballstemmer              2.0.0
        SQLAlchemy                   1.3.18
        ssh-import-id                5.10
        sympy                        1.6.2
        system-service               0.3
        systemd-python               234
        terminado                    0.8.3
        testpath                     0.4.4
        toml                         0.10.1
        tornado                      6.0.4
        traitlets                    4.3.3
        Twisted                      18.9.0
        ubuntu-advantage-tools       20.3
        ubuntu-drivers-common        0.0.0
        ufw                          0.36
        ujson                        1.35
        unattended-upgrades          0.1
        urllib3                      1.25.8
        wadllib                      1.3.3
        wcwidth                      0.2.5
        webencodings                 0.5.1
        wheel                        0.34.2
        widgetsnbextension           3.5.1
        wrapt                        1.12.1
        xkit                         0.0.0
        yapf                         0.30.0
        yarl                         1.5.1
        zipp                         1.0.0
        zope.component               4.3.0
        zope.event                   4.4
        zope.hookable                5.0.0
        zope.interface               4.7.1
</pre>
</details>

<details><summary>Command Line Output</summary>

**This error always occurs first**

<pre>
thread 'main' panicked at 'Could not deserialize parameter object: Error("invalid type: null, expected struct InitializedParams", line: 0, column: 0)', /home/runner/work/texlab/texlab/crates/jsonrpc/src/server.rs:49:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
[I 2020-09-06 15:21:16.673 SingleUserNotebookApp log:174] 200 PATCH /user/besses/api/sessions/5951f380-5d17-48e3-8f69-5c40bf7f14ac?1599427272461 (besses@::ffff:127.0.0.1) 1.97ms
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <texlab::server::LatexLspServer<C> as jsonrpc::server::RequestHandler>::handle_notification::__handle_notification::{{closure}}
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: texlab::main::{{closure}}
  17: std::thread::local::LocalKey<T>::with
  18: texlab::main
  19: std::rt::lang_start::{{closure}}
  20: main
  21: __libc_start_main
  22: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>

**These errors happen throughout**

<pre>
 {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///network/notebooks/notebooks/shared/PHYS-5030/HW2/main.tex","languageId":"latex","text":"\\documentclass**TONS of LaTEX**\\end{document}\n\n","version":0}}}
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyter_lsp/stdio.py", line 161, in write
        await convert_yielded(self._write_one(response.encode("utf-8")))
      File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/dist-packages/jupyter_lsp/stdio.py", line 169, in _write_one
        self.stream.write(message)
    BrokenPipeError: [Errno 32] Broken pipe
[E 2020-09-06 15:21:16.837 SingleUserNotebookApp stdio:163] <LspStdIoWriter(parent=<LanguageServerSession(language_server=texlab, argv=['/usr/local/bin/texlab'])>)> couldn't write message: Content-Length: 15874
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Issues detected. The new Issues tab displays information about deprecations, breaking changes and other potential problems.Go to IssuesLearn more
index.js:31 hub-extension: Found configuration  Object
feature.js:7 @krassowski/jupyterlab-lsp:signature settings schema could not be found and was not loaded
$e @ feature.js:7
feature.js:7 @krassowski/jupyterlab-lsp:highlights settings schema could not be found and was not loaded
$e @ feature.js:7
index.js:50 Starting application in workspace: "/lab"
notebook.js:75 LSP: waiting for notebooks/shared/PHYS-5030/HW2/Untitled.ipynb to fully load
file_editor.js:10 LSP: file ready for connection: notebooks/shared/PHYS-5030/HW2/main.tex
adapter.js:307 LSP: will connect using language: latex
connection_manager.js:159 LSP: connection requested Object
connection_manager.js:94 LSP: Connection Socket Object
20command_manager.js:129 is_visible failed TypeError: Cannot read property 'virtual_line' of undefined
    at F.virtual_position_at_document (document.js:224)
    at Proxy.root_position_to_virtual_position (codemirror_editor.js:142)
    at fn.get_context (adapter.js:385)
    at fn.context_from_active_document (file_editor.js:48)
    at w.get_context (command_manager.js:116)
    at w.is_visible (command_manager.js:123)
    at isVisible (command_manager.js:29)
    at e.isVisible (index.es6.js:332)
    at e.get [as isVisible] (index.es6.js:4689)
    at c (index.es6.js:4388)
is_visible @ command_manager.js:129
adapter.js:259 LSP: Skipping document update signal: connection not ready
3default.js:51 Starting WebSocket: wss://jupyterlab.com/user/besses/api/kernels/9a627b0d-280d-48c9-891f-99cdb5137fd9
connection_manager.js:171 LSP: notebooks/shared/PHYS-5030/HW2/main.tex 0(latex) connected.
adapter.js:352 LSP: Adapter for notebooks/shared/PHYS-5030/HW2/main.tex is ready.
adapter.js:187 LSP: virtual document(s) for notebooks/shared/PHYS-5030/HW2/main.tex have been initialized
console.js:34 LSP:  Will invoke completer after \
completion_handler.js:131 [LSP][Completer] Fetching and Transforming
completion_handler.js:132 [LSP][Completer] Token: Object Object Object
</pre>
</details>

**Comment by krassowski** [comment]
Thank you for opening this issue! I see that there is an error, though not where it appears to be.

There are multiple layers:

1. The warnings you provide are just a reminder to ourselves to add settings for highlights and signature features but have no impact on the extension functionalities (as to best of my knowledge they work very well - though they may not be implemented by the LaTeX server yet).

2. As for the Latex server, it is not the most straightforward and requires some configuration. For example, to make diagnostics work you need to set the settings to `{"language_servers": {"texlab": {"serverSettings": {"latex.lint.onChange": true}}}}`, which we need to document better I guess...

3. I see an error `"invalid type: null, expected struct InitializedParams"` which was fixed on #288 by @bollwyvl. However, I think that I did not release the updated package which was patched (no changelog entry - whoops). Working on this now...

**Comment by krassowski** [comment]
The patched release is now published. @BrandenEsses would you mind upgrading:

```bash
jupyter labextension install @krassowski/jupyterlab-lsp@2.0.1
```

restarting lab and checking if it works now?

**Comment by BrandenEsses** [comment]
@krassowski Just updated and it works perfectly! Thank you again!
