### ISSUE TITLE
virtual_documents customization

### ISSUE THREAD

**Issue by fcollonval** [krassowski/jupyterlab-lsp#353]
first of, thanks a lot for this amazing extension :1st_place_medal: 

## Description

> I do not think it is a bug per se. But there may be an opportunity for improvements - once I understand clearly what is going on :wink: 

Context:
- JupyterHub installation with JupyterLab as single-user server
- All single-user servers share the same disk and the same root directory. So users can share their work as they all belong to a common group.

Bug:

```
[W 2020-09-11 07:57:06.563 SingleUserNotebookApp notebookapp:1950] Error loading server extension jupyter_lsp
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1945, in init_server_extensions
        func(self)
      File "/opt/conda/lib/python3.7/site-packages/jupyter_lsp/serverextension.py", line 48, in load_jupyter_server_extension
        setup_shadow_filesystem(virtual_documents_uri=virtual_documents_uri)
      File "/opt/conda/lib/python3.7/site-packages/jupyter_lsp/virtual_documents_shadow.py", line 115, in setup_shadow_filesystem
        rmtree(str(shadow_filesystem))
      File "/opt/conda/lib/python3.7/shutil.py", line 498, in rmtree
        onerror(os.rmdir, path, sys.exc_info())
      File "/opt/conda/lib/python3.7/shutil.py", line 496, in rmtree
        os.rmdir(path)
    PermissionError: [Errno 13] Permission denied: '/homes/.virtual_documents'
```

In that configuration, I get permission error. And more importantly it seems wrong to have the same `virtual_documents` for all users. So this raises two questions:

- Would it be possible to parametrize the virtual_documents path?
- Does it need to be a child of root_dir? For what I understand, that folder contains only transient information that are better saved in a cache or temporary folder.

## Expected behavior

The virtual document folder is configurable and it lies in a cache or temporary place.

## Context

- Operating System and version: Debian strech
- Browser and version: N/A
- JupyterLab version: 2.1.5
- Jupyter-lsp 0.9.1 jupyterlab-lsp@1.1.2

> I'm unfortunately stuck to 2.1.x due to a bug in 2.2.x with nbdime.

**Comment by krassowski** [comment]
This is a fair point! It might be that moving it elsewhere will complicate resolution of paths for the LSP servers.

It also might be that it would have no effect at all. In fact, I am looking at moving this to a ramdisk on platforms that support it as to get a speed improvement on a component that can be quite a bottleneck if one does not have SSD.

Fortunately, fewer and fewer servers require this workaround; namely pyls went from being effectively unmaintained to a well managed project thank to the Spyder folks; they recently improved support of some features for documents which are not on the disk (but I think that the rename still requires the virtual documents); if it is only needed as a workaround for a few actions we might try disabling it by default and only writing it on rename request - should improve performance, though can be error prone.

Do users have their unique home within the `/homes/`? Can we grab it with an environment variable or something?

**Comment by fcollonval** [comment]
> It might be that moving it elsewhere will complicate resolution of paths for the LSP servers.

You mean that some LSP server assume the existence of a virtual folder in the current working directory?

> Do users have their unique home within the `/homes/`? 

Yes they have:
- /homes/user1
- /homes/user2
- ...

> Can we grab it with an environment variable or something?

As the jupyter server is run by the user, yes. The usual environment variables are avalaible; in particular: $HOME and $USER. So it would be possible to use them to create a unique path.
