### ISSUE TITLE
Variable names consume the underline

### ISSUE THREAD

**Issue by marimeireles** [krassowski/jupyterlab-lsp#371]
Hey Jupyterlab-lsp folks!

## Description

Using pyls-memestra I found a bug and I believe it's happening because of something wrong with juplab-lsb. Variable names are consuming the underline on the deprecated class/function.

## Reproduce

You can see it happening here: https://mybinder.org/v2/gh/QuantStack/pyls-memestra/master?urlpath=/lab/tree/binder/default_decorator_example.ipynb

But here is a screenshot:

![image](https://user-images.githubusercontent.com/17600982/93768050-56895480-fc08-11ea-913e-fd42eb08c150.png)

Any opinions on this? Have you seen this before?

Thanks a lot!

Related issue: https://github.com/QuantStack/pyls-memestra/issues/25

**Comment by krassowski** [comment]
This underline should only be visible when hovering over a variable... I will investigate.

**Comment by krassowski** [comment]
If you need something ASAP you could pin your binder to the previous version (2.0.6) where the hover underlines were not showing up at all.

**Comment by marimeireles** [comment]
Thanks for it @krassowski, didn't know we had a chrome issue. Will investigate!

**Comment by krassowski** [comment]
The binder on Chrome started working after a third trial - just a hiccup apparently.

**Comment by krassowski** [comment]
Hi @marimeireles, I had a quick look and I think that this might be on your side:

![Screenshot from 2020-09-21 14-22-10](https://user-images.githubusercontent.com/5832902/93771812-e681cb00-fc15-11ea-8c27-00b2334488e8.png)

`SomeOldFunction`  has 15 characters but the diagnostic (as shown above) specifies a range between 6th and 12th character - and we correctly only underline the first 6 characters.

**Comment by marimeireles** [comment]
Ah yeah! It does look like something on my side.
That's right. I'm sorry for this!

**Comment by krassowski** [comment]
No worries, glad I could help! It looks that the [err_range](https://github.com/QuantStack/pyls-memestra/blob/ec66c73eacf243f2e24200656e50e4585429a965/pyls_memestra/plugin.py#L19-L22) defionition, which currently is:

```python
err_range = {
    'start': {'line': lineno - 1, 'character': colno},
    'end': {'line': lineno - 1, 'character': len(fname)},
}
```

should have been:

```python
err_range = {
    'start': {'line': lineno - 1, 'character': colno},
    'end': {'line': lineno - 1, 'character': colno + len(fname)},  # <- change here
}
```

Hope it helps. Thanks for the mention of jupyterlab-lsp in the blog post btw!

**Comment by marimeireles** [comment]
You're welcome @krassowski, you're doing an amazing job here :)
Sorry for opening the issue without investigating it properly and thanks!

**Comment by bollwyvl** [comment]
awesome debugging, folks!

one of the things that will hopefully come out of the language server kernel proxy #278 is that we would be able to offer that part of the stack headless with a client for testing these kinds of things... some other "language server construction kits" have some utilities like this, but it might be useful for us to have in-package... it may make sense to land that in `pygls` and take that as an optional dependency... unless there's a lot of value in using it directly.
