### ISSUE TITLE
Is it possible to jump back after jump to definition?

### ISSUE THREAD

**Issue by stephenkraemer** [krassowski/jupyterlab-lsp#372]
## What I am trying to do...

I use Ctrl-B to jump to a definition. Then I am trying to jump back to the original location. Nothing happens.

This feature was available in the go-to-definition extension (via Alt-O). On the go-to-definition readme, it is indicated that jupyterlab-lsp makes use of this package to manage a jump list. There is also issue #370. I am nut sure whether that means that there is a way to jump back which I haven't found.

I can install the go-to-definition package and use Ctrl-Alt-B and Alt-O to jump back and forth, but that does not seem to give me the same powerful definition lookup as the Ctrl-B lookup (via the language server, I presume).

## How I would like to learn how to do it...

I would like to learn whether jumping back is currently possible for the language server go to definition feature.

Thanks so much for your great work!

**Comment by krassowski** [comment]
Thanks for reminding me of this! Yes, this definitely should be included in the next release.

**Comment by stephenkraemer** [comment]
Great, thanks a lot!

**Comment by stephenkraemer** [comment]
Thank you so much for all the great work, much appreciated!
