### ISSUE TITLE
Python missing issue

### ISSUE THREAD

**Issue by lindaorny** [krassowski/jupyterlab-lsp#374]
Hi there,

I am using jupyter lab v2.2.8, nodejs v10.22.1 and python v3.7.7 (OS ubuntu 18.04). I have tried to install the lsp server on my Jupyterhub using both pip and conda, configure the setting at the Advance language setting as well. 

However, the Initialized (additional servers needed) LSP servers Missing:1 python keep showing whatever method I try. Does anyone encounter the same before?

I have checked the python language server is actually located at /opt/tljh/user/pkgs. I am not sure why still prompting missing.

Many thanks in advance!

**Comment by krassowski** [comment]
Sorry, I cannot help you much until you fill in the bug issue template. Also, please take time to read the issue #93.

**Comment by lindaorny** [comment]
## Description

I try to uninstall all and install again but seems failed.

Version below:
OS version == ubuntu 18.04
JupyterLab version == 2.2.8
Python version == 3.7.7
nodejs == 12.18.4



## Reproduce



Steps:
1. Open JupyterHub terminal
2. Run the following command:

sudo conda install -c conda-forge python=3
sudo conda install -c conda-forge jupyterlab
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo conda install -c conda-forge jupyter-lsp
sudo jupyter serverextension enable --sys-prefix --py jupyter_lsp
sudo jupyter labextension install @krassowski/jupyterlab-lsp@2.7.0-rc.0
sudo conda install -c conda-forge python-language-server r-languageserver

3. Add the below lines at the Advance Language Setting:
{
  "language_servers": {
    "pyls": {
      "serverSettings": {
        "pyls.plugins.pydocstyle.enabled": true,
        "pyls.plugins.pyflakes.enabled": false,
        "pyls.plugins.flake8.enabled": true
      }
    },
    "r-languageserver": {
      "serverSettings": {
        "r.lsp.debug": false,
        "r.lsp.diagnostics": false
      }
    }
  }
}

3. Open a new python notebook
4. At the left hand corner, it shows "Initialized (additional servers needed)" -- LSP servers Missing:1 python
![image](https://user-images.githubusercontent.com/25446451/94224920-3dddaf00-ff26-11ea-939b-11c928b71186.png)



## Expected behavior



## Context



- Operating System and version: ubuntu 18.04
- Browser and version: Google Chrome Version 85.0.4183.121 
- JupyterLab version: 2.2.8

<details><summary>Required: installed server extensions</summary>
<pre>
Paste the output from running `jupyter serverextension list` from the command line here.
 jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 0.9.2 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.8 OK
    nbgitpuller  enabled 
    - Validating...
      nbgitpuller 0.7.2 OK
    nteract_on_jupyter  enabled 
    - Validating...
      nteract_on_jupyter 2.1.3 OK
    nbresuse  enabled 
    - Validating...
      nbresuse  OK
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
Paste the output from running `jupyter labextension list` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>



<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
pip list:
        Package                           Version
        --------------------------------- ---------
        absl-py                           0.8.1
        alabaster                         0.7.12
        alembic                           1.4.0
        ansiwrap                          0.8.4
        appdirs                           1.4.3
        argon2-cffi                       20.1.0
        astor                             0.8.0
        astroid                           2.4.2
        attrs                             20.2.0
        autopep8                          1.5.4
        Babel                             2.8.0
        backcall                          0.2.0
        Backtesting                       0.1.6
        beautifulsoup4                    4.8.2
        black                             19.10b0
        bleach                            3.2.1
        bokeh                             2.0.0
        boto3                             1.12.20
        botocore                          1.15.20
        brewer2mpl                        1.4.1
        brotlipy                          0.7.0
        bs4                               0.0.1
        cchardet                          2.1.5
        certifi                           2020.6.20
        certipy                           0.1.3
        cffi                              1.14.0
        chardet                           3.0.4
        click                             6.7
        colorama                          0.4.3
        colorlog                          4.1.0
        colormap                          1.0.3
        comtypes                          1.1.7
        conda                             4.8.5
        conda-package-handling            1.7.0
        cryptography                      3.1
        cycler                            0.10.0
        Cython                            0.29.15
        datapackage                       1.11.1
        DateTime                          4.3
        decorator                         4.4.2
        defusedxml                        0.6.0
        distro                            1.5.0
        dnspython                         1.16.0
        docopt                            0.6.2
        docutils                          0.15.2
        easydev                           0.9.38
        entrypoints                       0.3
        et-xmlfile                        1.0.1
        feedparser                        5.2.1
        flake8                            3.8.3
        fred                              3.1
        future                            0.18.2
        gast                              0.2.2
        ggplot                            0.11.5
        gitsome                           0.8.4
        google-pasta                      0.1.8
        grpcio                            1.16.1
        h5py                              2.10.0
        html5lib                          1.0.1
        idna                              2.10
        ijson                             2.6.1
        imagesize                         1.2.0
        importlib-metadata                1.7.0
        ipykernel                         5.3.4
        ipython                           7.18.1
        ipython-genutils                  0.2.0
        ipywidgets                        7.5.1
        isodate                           0.6.0
        isort                             5.5.3
        jdcal                             1.4.1
        jedi                              0.17.2
        Jinja2                            2.11.2
        jmespath                          0.9.5
        joblib                            0.14.1
        json5                             0.9.5
        jsonlines                         1.2.0
        jsonpickle                        1.3
        jsonpointer                       2.0
        jsonschema                        3.2.0
        jupyter-client                    6.1.6
        jupyter-contrib-core              0.3.3
        jupyter-contrib-nbextensions      0.5.1
        jupyter-core                      4.6.3
        jupyter-highlight-selected-word   0.2.0
        jupyter-latex-envs                1.4.6
        jupyter-lsp                       0.9.2
        jupyter-nbextensions-configurator 0.4.1
        jupyterhub                        1.0.0
        jupyterlab                        2.2.8
        jupyterlab-server                 1.2.0
        kafka-python                      1.4.3
        Keras                             2.3.1
        Keras-Applications                1.0.8
        Keras-Preprocessing               1.1.0
        kiwisolver                        1.1.0
        lazy-object-proxy                 1.4.3
        linear-tsv                        1.1.0
        linearmodels                      4.17
        lxml                              4.5.0
        Mako                              1.1.1
        Markdown                          3.1.1
        MarkupSafe                        1.1.1
        matplotlib                        3.1.3
        mccabe                            0.6.1
        mistune                           0.8.4
        more-itertools                    8.2.0
        mypy-extensions                   0.4.3
        mysql-connector-python            8.0.19
        nbclient                          0.2.0
        nbconvert                         5.6.1
        nbformat                          5.0.7
        nbgitpuller                       0.7.2
        nbresuse                          0.3.3
        nest-asyncio                      1.3.3
        networkx                          2.4
        notebook                          6.1.1
        nteract-on-jupyter                2.1.3
        numpy                             1.18.1
        numpydoc                          0.9.2
        oauthlib                          3.1.0
        openpyxl                          3.0.3
        opt-einsum                        3.1.0
        packaging                         20.4
        pamela                            1.0.0
        pandas                            1.0.0
        pandocfilters                     1.4.2
        papermill                         2.1.1
        parso                             0.7.1
        pathspec                          0.8.0
        patsy                             0.5.1
        pexpect                           4.8.0
        pickleshare                       0.7.5
        Pillow                            7.0.0
        pip                               20.2.2
        pluggy                            0.13.1
        ply                               3.11
        prometheus-client                 0.8.0
        prompt-toolkit                    3.0.7
        property-cached                   1.6.4
        protobuf                          3.6.1
        psutil                            5.6.7
        ptvsd                             4.3.2
        ptyprocess                        0.6.0
        pycodestyle                       2.6.0
        pycosat                           0.6.3
        pycparser                         2.20
        pydocstyle                        5.1.1
        pyflakes                          2.2.0
        Pygments                          2.7.1
        pylint                            2.6.0
        pyOpenSSL                         19.1.0
        pyparsing                         2.4.7
        pypi                              2.1
        pyrsistent                        0.17.3
        PySocks                           1.7.1
        python-dateutil                   2.8.1
        python-editor                     1.0.4
        python-jsonrpc-server             0.4.0
        python-language-server            0.35.1
        pytz                              2019.3
        PyYAML                            5.1.2
        pyzmq                             19.0.2
        rc-research-api                   0.0.12
        rc-util-lite                      0.1.16
        regex                             2020.5.7
        reports                           0.3.1
        requests                          2.24.0
        rfc3986                           1.3.2
        rope                              0.17.0
        ruamel-yaml                       0.15.87
        runipy                            0.1.5
        s3transfer                        0.3.3
        scikit-learn                      0.22.1
        scipy                             1.4.1
        seaborn                           0.10.0
        selenium                          3.141.0
        Send2Trash                        1.5.0
        setuptools                        50.3.0
        six                               1.15.0
        sklearn                           0.0
        snowballstemmer                   2.0.0
        soupsieve                         2.0
        Sphinx                            2.4.4
        sphinxcontrib-applehelp           1.0.2
        sphinxcontrib-devhelp             1.0.2
        sphinxcontrib-htmlhelp            1.0.3
        sphinxcontrib-jsmath              1.0.1
        sphinxcontrib-qthelp              1.0.3
        sphinxcontrib-serializinghtml     1.1.4
        SQLAlchemy                        1.3.13
        statsmodels                       0.11.1
        tableschema                       1.15.0
        tabula-py                         2.1.0
        tabulator                         1.35.0
        tenacity                          6.2.0
        tensorboard                       2.0.0
        tensorflow                        2.0.0
        tensorflow-estimator              2.0.0
        termcolor                         1.1.0
        terminado                         0.8.3
        testpath                          0.4.4
        textwrap3                         0.9.2
        Theano                            1.0.4
        there                             0.0.9
        toml                              0.10.1
        tornado                           6.0.4
        tqdm                              4.49.0
        traitlets                         5.0.4
        typed-ast                         1.4.1
        typing-extensions                 3.7.4.1
        ujson                             3.2.0
        unicodecsv                        0.14.1
        uritemplate                       3.0.1
        uritemplate.py                    3.0.2
        urllib3                           1.25.10
        wcwidth                           0.2.5
        webencodings                      0.5.1
        weo                               0.0.65
        Werkzeug                          0.16.1
        wheel                             0.35.1
        widgetsnbextension                3.5.1
        wrapt                             1.11.2
        xlrd                              1.2.0
        XlsxWriter                        1.2.8
        xmltodict                         0.12.0
        yapf                              0.30.0
        zipp                              3.1.0
        zope.interface                    4.7.2

conda list:
        # packages in environment at /opt/tljh/user:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                        main  
        _r-mutex                  1.0.1               anacondar_1    conda-forge
        absl-py                   0.8.1                    pypi_0    pypi
        alabaster                 0.7.12                   pypi_0    pypi
        alembic                   1.4.0                    pypi_0    pypi
        ansiwrap                  0.8.4                    pypi_0    pypi
        appdirs                   1.4.3                    pypi_0    pypi
        argon2-cffi               20.1.0           py37h7b6447c_1  
        astor                     0.8.0                    pypi_0    pypi
        astroid                   2.4.2                    py37_0  
        attrs                     19.3.0                   pypi_0    pypi
        autopep8                  1.5.4                    pypi_0    pypi
        babel                     2.8.0                    pypi_0    pypi
        backcall                  0.1.0                    pypi_0    pypi
        backtesting               0.1.6                    pypi_0    pypi
        beautifulsoup4            4.8.2                    pypi_0    pypi
        black                     19.10b0                  pypi_0    pypi
        bleach                    3.1.0                    pypi_0    pypi
        bokeh                     2.0.0                    pypi_0    pypi
        boto3                     1.12.20                  pypi_0    pypi
        botocore                  1.15.20                  pypi_0    pypi
        brewer2mpl                1.4.1                    pypi_0    pypi
        brotlipy                  0.7.0           py37h7b6447c_1000  
        bs4                       0.0.1                    pypi_0    pypi
        bwidget                   1.9.11                        1  
        bzip2                     1.0.8                h7b6447c_0  
        ca-certificates           2020.6.20            hecda079_0    conda-forge
        cairo                     1.14.12              h8948797_3  
        cchardet                  2.1.5                    pypi_0    pypi
        certifi                   2019.11.28               pypi_0    pypi
        certipy                   0.1.3                    pypi_0    pypi
        cffi                      1.14.0           py37h2e261b9_0  
        chardet                   3.0.4                 py37_1003  
        click                     6.7                      pypi_0    pypi
        colorama                  0.4.3                    pypi_0    pypi
        colorlog                  4.1.0                    pypi_0    pypi
        colormap                  1.0.3                    pypi_0    pypi
        comtypes                  1.1.7                    pypi_0    pypi
        conda                     4.8.5            py37hc8dfbb8_1    conda-forge
        conda-package-handling    1.6.1            py37h7b6447c_0  
        cryptography              3.1              py37h1ba5d50_0  
        curl                      7.68.0               hf8cf82a_0    conda-forge
        cycler                    0.10.0                   pypi_0    pypi
        cython                    0.29.15                  pypi_0    pypi
        datapackage               1.11.1                   pypi_0    pypi
        datetime                  4.3                      pypi_0    pypi
        decorator                 4.4.1                    pypi_0    pypi
        defusedxml                0.6.0                      py_0  
        distro                    1.5.0                    pypi_0    pypi
        dnspython                 1.16.0                   pypi_0    pypi
        docopt                    0.6.2                    pypi_0    pypi
        docutils                  0.15.2                   pypi_0    pypi
        easydev                   0.9.38                   pypi_0    pypi
        entrypoints               0.3                      py37_0  
        et-xmlfile                1.0.1                    pypi_0    pypi
        feedparser                5.2.1                    pypi_0    pypi
        flake8                    3.8.3                    pypi_0    pypi
        fontconfig                2.13.1            he4413a7_1000    conda-forge
        fred                      3.1                      pypi_0    pypi
        freetype                  2.10.2               h5ab3b9f_0  
        future                    0.18.2                   py37_1  
        gast                      0.2.2                    pypi_0    pypi
        gettext                   0.19.8.1             hd7bead4_3  
        ggplot                    0.11.5                   pypi_0    pypi
        gitsome                   0.8.4                    pypi_0    pypi
        glib                      2.56.2            had28632_1001    conda-forge
        google-pasta              0.1.8                    pypi_0    pypi
        graphite2                 1.3.14               h23475e2_0  
        grpcio                    1.16.1                   pypi_0    pypi
        gsl                       2.2.1                h0c605f7_3  
        h5py                      2.10.0                   pypi_0    pypi
        harfbuzz                  1.9.0             he243708_1001    conda-forge
        html5lib                  1.0.1                    pypi_0    pypi
        icu                       58.2                 he6710b0_3  
        idna                      2.10                       py_0  
        ijson                     2.6.1                    pypi_0    pypi
        imagesize                 1.2.0                    pypi_0    pypi
        importlib-metadata        1.5.0                    pypi_0    pypi
        importlib_metadata        1.7.0                         0  
        ipykernel                 5.1.4                    pypi_0    pypi
        ipython                   7.12.0                   pypi_0    pypi
        ipython-genutils          0.2.0                    pypi_0    pypi
        ipython_genutils          0.2.0                    py37_0  
        ipywidgets                7.5.1                    pypi_0    pypi
        isodate                   0.6.0                    pypi_0    pypi
        isort                     5.5.3                    py37_0  
        jdcal                     1.4.1                    pypi_0    pypi
        jedi                      0.17.2                   pypi_0    pypi
        jinja2                    2.11.1                   pypi_0    pypi
        jmespath                  0.9.5                    pypi_0    pypi
        joblib                    0.14.1                   pypi_0    pypi
        jpeg                      9d                   h516909a_0    conda-forge
        json5                     0.9.0                    pypi_0    pypi
        jsonlines                 1.2.0                    pypi_0    pypi
        jsonpickle                1.3                      pypi_0    pypi
        jsonpointer               2.0                      pypi_0    pypi
        jsonschema                3.2.0                    py37_1  
        jupyter-client            6.1.2                    pypi_0    pypi
        jupyter-contrib-core      0.3.3                    pypi_0    pypi
        jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
        jupyter-core              4.6.1                    pypi_0    pypi
        jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
        jupyter-latex-envs        1.4.6                    pypi_0    pypi
        jupyter-lsp               0.9.2                      py_1    conda-forge
        jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
        jupyter_client            6.1.6                      py_0  
        jupyter_core              4.6.3                    py37_0  
        jupyterhub                1.0.0                    pypi_0    pypi
        jupyterlab                2.2.0                    pypi_0    pypi
        jupyterlab_server         1.2.0                      py_0  
        kafka-python              1.4.3                    pypi_0    pypi
        keras                     2.3.1                    pypi_0    pypi
        keras-applications        1.0.8                    pypi_0    pypi
        keras-preprocessing       1.1.0                    pypi_0    pypi
        kiwisolver                1.1.0                    pypi_0    pypi
        krb5                      1.16.4               h173b8e3_0  
        lazy-object-proxy         1.4.3            py37h7b6447c_0  
        ld_impl_linux-64          2.33.1               h53a641e_7  
        libcurl                   7.68.0               hda55be3_0    conda-forge
        libedit                   3.1.20191231         h14c3975_1  
        libffi                    3.2.1                hd88cf55_4  
        libgcc                    7.2.0                h69d50b8_2  
        libgcc-ng                 9.1.0                hdf63c60_0  
        libgfortran               3.0.0                         1    conda-forge
        libiconv                  1.15                 h63c8f33_5  
        libpng                    1.6.37               hbc83047_0  
        libsodium                 1.0.18               h7b6447c_0  
        libssh2                   1.9.0                h1ba5d50_1  
        libstdcxx-ng              9.1.0                hdf63c60_0  
        libtiff                   4.1.0                h2733197_1  
        libuuid                   2.32.1            h14c3975_1000    conda-forge
        libxcb                    1.14                 h7b6447c_0  
        libxml2                   2.9.10               he19cac6_1  
        linear-tsv                1.1.0                    pypi_0    pypi
        linearmodels              4.17                     pypi_0    pypi
        lxml                      4.5.0                    pypi_0    pypi
        lz4-c                     1.9.2                he6710b0_1  
        make                      4.2.1                h1bed415_1  
        mako                      1.1.1                    pypi_0    pypi
        markdown                  3.1.1                    pypi_0    pypi
        markupsafe                1.1.1            py37h14c3975_1  
        matplotlib                3.1.3                    pypi_0    pypi
        mccabe                    0.6.1                    pypi_0    pypi
        mistune                   0.8.4           py37h14c3975_1001  
        more-itertools            8.2.0                    pypi_0    pypi
        mypy-extensions           0.4.3                    pypi_0    pypi
        mysql-connector-python    8.0.19                   pypi_0    pypi
        nbclient                  0.2.0                    pypi_0    pypi
        nbconvert                 5.6.1                    py37_1  
        nbformat                  5.0.4                    pypi_0    pypi
        nbgitpuller               0.7.2                    pypi_0    pypi
        nbresuse                  0.3.3                    pypi_0    pypi
        ncurses                   6.2                  he6710b0_1  
        nest-asyncio              1.3.3                    pypi_0    pypi
        networkx                  2.4                      pypi_0    pypi
        notebook                  6.0.3                    pypi_0    pypi
        nteract-on-jupyter        2.1.3                    pypi_0    pypi
        numpy                     1.18.1                   pypi_0    pypi
        numpydoc                  0.9.2                    pypi_0    pypi
        oauthlib                  3.1.0                    pypi_0    pypi
        openpyxl                  3.0.3                    pypi_0    pypi
        openssl                   1.1.1h               h516909a_0    conda-forge
        opt-einsum                3.1.0                    pypi_0    pypi
        packaging                 20.3                     pypi_0    pypi
        pamela                    1.0.0                    pypi_0    pypi
        pandas                    1.0.0                    pypi_0    pypi
        pandoc                    2.10.1                        0  
        pandocfilters             1.4.2                    py37_1  
        pango                     1.40.14           hf0c64fd_1003    conda-forge
        papermill                 2.1.1                    pypi_0    pypi
        parso                     0.7.1                    pypi_0    pypi
        pathspec                  0.8.0                    pypi_0    pypi
        patsy                     0.5.1                    pypi_0    pypi
        pcre                      8.44                 he6710b0_0  
        pexpect                   4.8.0                    py37_1  
        pickleshare               0.7.5                 py37_1001  
        pillow                    7.0.0                    pypi_0    pypi
        pip                       20.2.2                   py37_0  
        pixman                    0.40.0               h7b6447c_0  
        pluggy                    0.13.1                   py37_0  
        ply                       3.11                     pypi_0    pypi
        prometheus-client         0.7.1                    pypi_0    pypi
        prometheus_client         0.8.0                      py_0  
        prompt-toolkit            2.0.10                   pypi_0    pypi
        property-cached           1.6.4                    pypi_0    pypi
        protobuf                  3.6.1                    pypi_0    pypi
        psutil                    5.6.7                    pypi_0    pypi
        ptvsd                     4.3.2            py37h516909a_1    conda-forge
        ptyprocess                0.6.0                    py37_0  
        pycodestyle               2.6.0                    pypi_0    pypi
        pycosat                   0.6.3            py37h7b6447c_0  
        pycparser                 2.20                       py_2  
        pydocstyle                5.1.1                      py_0  
        pyflakes                  2.2.0                    pypi_0    pypi
        pygments                  2.5.2                    pypi_0    pypi
        pylint                    2.6.0                    py37_0  
        pyopenssl                 19.1.0                     py_1  
        pyparsing                 2.4.6                    pypi_0    pypi
        pypi                      2.1                      pypi_0    pypi
        pyrsistent                0.15.7                   pypi_0    pypi
        pysocks                   1.7.1                    py37_1  
        python                    3.7.7           h191fe78_0_cpython  
        python-dateutil           2.8.1                      py_0  
        python-editor             1.0.4                    pypi_0    pypi
        python-jsonrpc-server     0.4.0                    pypi_0    pypi
        python-language-server    0.35.1                   pypi_0    pypi
        python_abi                3.7                     1_cp37m    conda-forge
        pytz                      2019.3                   pypi_0    pypi
        pyyaml                    5.1.2                    pypi_0    pypi
        pyzmq                     18.1.1                   pypi_0    pypi
        r-askpass                 1.1               r35hcdcec82_1    conda-forge
        r-assertthat              0.2.1             r35h6115d3f_1    conda-forge
        r-backports               1.1.6             r35hcdcec82_1    conda-forge
        r-base                    3.5.1                h391c2eb_5    conda-forge
        r-base64enc               0.1_3           r35hcdcec82_1003    conda-forge
        r-callr                   3.4.3             r35h6115d3f_0    conda-forge
        r-cli                     2.0.2             r35h6115d3f_0    conda-forge
        r-clipr                   0.7.0             r35h6115d3f_0    conda-forge
        r-codetools               0.2_16          r35h6115d3f_1001    conda-forge
        r-collections             0.3.1             r35hcdcec82_0    conda-forge
        r-crayon                  1.3.4           r35h6115d3f_1002    conda-forge
        r-curl                    4.3               r35hcdcec82_0    conda-forge
        r-cyclocomp               1.1.0           r35h6115d3f_1003    conda-forge
        r-desc                    1.2.0           r35h6115d3f_1002    conda-forge
        r-digest                  0.6.25            r35h0357c0b_1    conda-forge
        r-ellipsis                0.3.0             r35hcdcec82_0    conda-forge
        r-evaluate                0.14              r35h6115d3f_1    conda-forge
        r-fansi                   0.4.1             r35hcdcec82_0    conda-forge
        r-fs                      1.4.1             r35h0357c0b_0    conda-forge
        r-glue                    1.4.0             r35hcdcec82_0    conda-forge
        r-highr                   0.8               r35h6115d3f_1    conda-forge
        r-hms                     0.5.3             r35h6115d3f_0    conda-forge
        r-htmltools               0.4.0             r35h0357c0b_0    conda-forge
        r-httr                    1.4.1             r35h6115d3f_1    conda-forge
        r-jsonlite                1.6.1             r35hcdcec82_0    conda-forge
        r-knitr                   1.28              r35h6115d3f_0    conda-forge
        r-languageserver          0.3.5             r35hcdcec82_0    conda-forge
        r-lazyeval                0.2.2             r35hcdcec82_1    conda-forge
        r-lifecycle               0.2.0             r35h6115d3f_0    conda-forge
        r-lintr                   2.0.1             r35h6115d3f_0    conda-forge
        r-magrittr                1.5             r35h6115d3f_1002    conda-forge
        r-markdown                1.1               r35hcdcec82_0    conda-forge
        r-mime                    0.9               r35hcdcec82_0    conda-forge
        r-openssl                 1.4.1             r35he5c4762_0    conda-forge
        r-pillar                  1.4.3             r35h6115d3f_0    conda-forge
        r-pkgconfig               2.0.3             r35h6115d3f_0    conda-forge
        r-praise                  1.0.0           r35h6115d3f_1003    conda-forge
        r-processx                3.4.2             r35hcdcec82_0    conda-forge
        r-ps                      1.3.2             r35hcdcec82_0    conda-forge
        r-purrr                   0.3.4             r35hcdcec82_0    conda-forge
        r-r6                      2.4.1             r35h6115d3f_0    conda-forge
        r-rcpp                    1.0.4.6           r35h0357c0b_0    conda-forge
        r-readr                   1.3.1           r35h0357c0b_1002    conda-forge
        r-rematch2                2.1.2             r35h6115d3f_0    conda-forge
        r-remotes                 2.1.1             r35h6115d3f_0    conda-forge
        r-repr                    1.1.0             r35h6115d3f_0    conda-forge
        r-rex                     1.2.0             r35h6115d3f_0    conda-forge
        r-rlang                   0.4.5             r35hcdcec82_2    conda-forge
        r-rprojroot               1.3_2           r35h6115d3f_1002    conda-forge
        r-rstudioapi              0.11              r35h6115d3f_0    conda-forge
        r-stringdist              0.9.5.5           r35hcdcec82_0    conda-forge
        r-stringi                 1.4.3             r35h0357c0b_2    conda-forge
        r-stringr                 1.4.0             r35h6115d3f_1    conda-forge
        r-styler                  1.2.0             r35h6115d3f_0    conda-forge
        r-sys                     3.3               r35hcdcec82_0    conda-forge
        r-testthat                2.2.1             r35h0357c0b_0    conda-forge
        r-tibble                  3.0.1             r35hcdcec82_0    conda-forge
        r-utf8                    1.1.4           r35hcdcec82_1002    conda-forge
        r-vctrs                   0.2.4             r35hcdcec82_0    conda-forge
        r-withr                   2.2.0             r35h6115d3f_0    conda-forge
        r-xfun                    0.13              r35h6115d3f_0    conda-forge
        r-xml2                    1.3.2             r35h0357c0b_0    conda-forge
        r-xmlparsedata            1.0.3             r35h6115d3f_0    conda-forge
        r-xptr                    1.1.3             r35hcdcec82_0    conda-forge
        r-yaml                    2.2.1             r35hcdcec82_0    conda-forge
        r-zeallot                 0.1.0           r35h6115d3f_1001    conda-forge
        rc-research-api           0.0.12                   pypi_0    pypi
        rc-util-lite              0.1.16                   pypi_0    pypi
        readline                  7.0                  h7b6447c_5  
        regex                     2020.5.7                 pypi_0    pypi
        reports                   0.3.1                    pypi_0    pypi
        requests                  2.24.0                     py_0  
        rfc3986                   1.3.2                    pypi_0    pypi
        rope                      0.17.0                     py_0  
        ruamel_yaml               0.15.87          py37h7b6447c_1  
        runipy                    0.1.5                    pypi_0    pypi
        s3transfer                0.3.3                    pypi_0    pypi
        scikit-learn              0.22.1                   pypi_0    pypi
        scipy                     1.4.1                    pypi_0    pypi
        seaborn                   0.10.0                   pypi_0    pypi
        selenium                  3.141.0                  pypi_0    pypi
        send2trash                1.5.0                    py37_0  
        setuptools                50.3.0                   pypi_0    pypi
        six                       1.15.0                     py_0  
        sklearn                   0.0                      pypi_0    pypi
        snowballstemmer           2.0.0                      py_0  
        soupsieve                 2.0                      pypi_0    pypi
        sphinx                    2.4.4                    pypi_0    pypi
        sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
        sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
        sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
        sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
        sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
        sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
        sqlalchemy                1.3.13                   pypi_0    pypi
        sqlite                    3.33.0               h62c20be_0  
        statsmodels               0.11.1                   pypi_0    pypi
        tableschema               1.15.0                   pypi_0    pypi
        tabula-py                 2.1.0                    pypi_0    pypi
        tabulator                 1.35.0                   pypi_0    pypi
        tenacity                  6.2.0                    pypi_0    pypi
        tensorboard               2.0.0                    pypi_0    pypi
        tensorflow                2.0.0                    pypi_0    pypi
        tensorflow-estimator      2.0.0                    pypi_0    pypi
        termcolor                 1.1.0                    pypi_0    pypi
        terminado                 0.8.3                    pypi_0    pypi
        testpath                  0.4.4                      py_0  
        textwrap3                 0.9.2                    pypi_0    pypi
        theano                    1.0.4                    pypi_0    pypi
        there                     0.0.9                    pypi_0    pypi
        tk                        8.6.10               hbc83047_0  
        tktable                   2.10                 h14c3975_0  
        toml                      0.10.0                   pypi_0    pypi
        tornado                   6.0.3                    pypi_0    pypi
        tqdm                      4.46.0                   pypi_0    pypi
        traitlets                 4.3.3                    pypi_0    pypi
        typed-ast                 1.4.1            py37h7b6447c_0  
        typing-extensions         3.7.4.1                  pypi_0    pypi
        ujson                     3.2.0                    pypi_0    pypi
        unicodecsv                0.14.1                   pypi_0    pypi
        uritemplate               3.0.1                    pypi_0    pypi
        uritemplate-py            3.0.2                    pypi_0    pypi
        urllib3                   1.25.10                    py_0  
        wcwidth                   0.1.8                    pypi_0    pypi
        webencodings              0.5.1                    pypi_0    pypi
        weo                       0.0.65                   pypi_0    pypi
        werkzeug                  0.16.1                   pypi_0    pypi
        wheel                     0.35.1                     py_0  
        widgetsnbextension        3.5.1                    pypi_0    pypi
        wrapt                     1.11.2           py37h7b6447c_0  
        xeus                      0.24.1               h4d8c418_0    conda-forge
        xeus-python               0.8.1            py37h99015e2_0    conda-forge
        xlrd                      1.2.0                    pypi_0    pypi
        xlsxwriter                1.2.8                    pypi_0    pypi
        xmltodict                 0.12.0                   pypi_0    pypi
        xz                        5.2.5                h7b6447c_0  
        yaml                      0.2.5                h7b6447c_0  
        yapf                      0.30.0                     py_0  
        zeromq                    4.3.2                he6710b0_3  
        zipp                      2.2.0                    pypi_0    pypi
        zlib                      1.2.11               h7b6447c_3  
        zope-interface            4.7.2                    pypi_0    pypi
        zstd                      1.4.5                h9ceee32_0
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
feature.js:7 @krassowski/jupyterlab-lsp:signature settings schema could not be found and was not loaded
FeatureSettings @ feature.js:7
activate @ signature.js:118
(anonymous) @ index.es6.js:162
Promise.then (async)
push.8h0S.Application.activatePlugin @ index.es6.js:161
(anonymous) @ index.es6.js:281
push.8h0S.Application.start @ index.es6.js:280
main @ index.out.js:1059
load (async)
ANye @ index.out.js:1108
__webpack_require__ @ bootstrap:84
0 @ bootstrap:221
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ vendors~main.cb65b7fcf7c7f93ced3f.js:1
feature.js:7 @krassowski/jupyterlab-lsp:highlights settings schema could not be found and was not loaded
</pre>
</details>

**Comment by JeroenSchmidt** [comment]
I am experiencing the same issue however I am on macOS 10.15.7

**Comment by foreverlms** [comment]
I have the same issue with you.

**Comment by krassowski** [comment]
Thank you for the reports! I will close this in favour of #375.
