### ISSUE TITLE
Documentation for code completion and hover settings

### ISSUE THREAD

**Issue by quantum-booty** [krassowski/jupyterlab-lsp#376]
1) Is there a setting to disable automatic completion when I press enter? I would like enter to open a new line rather than select an completion.
2) What are the allowed values for hover key? I tried to set tab as the hover key but it does not work.

**Comment by krassowski** [comment]
1. No unfortunately not in the current version, but this is on the wish list (#350). For the technical reasoning on why we cannot do this just yet see #334, #335. However, if you can provide a reproducible example demonstrating where it is still a nuisance (*still* as I already added a workaround to suppress auto-invocation in a typical example demonstrated in #334) I will look into this.
2. Good catch! You can find the allowed values here:

https://github.com/krassowski/jupyterlab-lsp/blob/de32a3ae46db0aeec529f0f157874c3feb75b77e/packages/jupyterlab-lsp/schema/hover.json#L8-L14

It indeed would be better if we could include the enum values in the `description` field value. Would you like to contribute a fix by editing this file and creating a pull request?

You could also add information on some caveats for the Mac users, as I noted for my previous extension [here](https://github.com/krassowski/jupyterlab-go-to-definition#changing-the-modifiers-key-from-alt) (and maybe the link to the MDN page which describes to which physical keys they are actually mapped, also in the readme of the previous extension).

**Comment by quantum-booty** [comment]
Thank you @krassowski, I have made a PR.

**Comment by quantum-booty** [comment]
I tested the enter on a simple case of
```
x=1
x
```
and autocompletion refused to open a new line. But this scenario would never happen practically. So I am closing this.
