### ISSUE TITLE
Autocompletion not working correctly for Altair classes and sorting of matches is not optimal

### ISSUE THREAD

**Issue by joelostblom** [krassowski/jupyterlab-lsp#382]
Thanks you so much for making an lsp extension for JL!!! I didn't know this existed until today and I am really excited to have found it!

I have been comparing the autocompletion from this extension with what is provided by VS Code, and noticed that it is sometimes not working as expected. For example, when trying to autocomplete the `Chart()` class in Altair, I only see filenames come up as suggestions:

![image](https://user-images.githubusercontent.com/4560057/96159560-a2f34780-0ec9-11eb-956e-a77e108d995c.png)

If I skip the `()`, I get the correct suggestions, but ordered in a non-optimal way:

![image](https://user-images.githubusercontent.com/4560057/96159614-b6061780-0ec9-11eb-8029-f08f3282dd72.png)

In VS code, I get what I would expect, although the matching is fuzzy, matches starting with the letter I typed are shown on top, and autocompletion works when including the `()`:

![image](https://user-images.githubusercontent.com/4560057/96159669-c8805100-0ec9-11eb-8073-23f0b5ff48c9.png)

---

I also tried this for pandas `DataFrame()` class, and there the autocompletion works as expected:

![image](https://user-images.githubusercontent.com/4560057/96159821-f5ccff00-0ec9-11eb-934e-3d6dd0578003.png)

Which is the same in vscode:

![image](https://user-images.githubusercontent.com/4560057/96159878-0b422900-0eca-11eb-89d5-a112ba4bf8da.png)

```
Arch linux 5.8.13-arch1-1

Chromium 86.0.4240.75

jupyter core     : 4.6.3
jupyter-notebook : 5.6.0
qtconsole        : not installed
ipython          : 6.5.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 5.0.4
```

<details><summary>Required: installed server extensions</summary>
<pre>
# In the conda env where jupyterlab is installed
$ jupyter serverextension list
Config option `kernel_spec_manager_class` not recognized by `ListServerExtensionsApp`.
config dir: /home/joel/miniconda3/envs/jl/etc/jupyter
    jupyter_lsp  enabled
    - Validating...
      jupyter_lsp 0.9.2 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.8 OK
</pre>
<pre>
# In the conda env of the Python kernel I am running
$ jupyter serverextension list                                                   130 ↵
config dir: /home/joel/miniconda3/envs/531/etc/jupyter
    jupyter_lsp  enabled
    - Validating...
      jupyter_lsp 0.9.2 OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
# In the conda env where jupyterlab is installed
$ jupyter labextension list
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
JupyterLab v2.2.8
Known labextensions:
   app dir: /home/joel/miniconda3/envs/jl/share/jupyter/lab
        @axlair/jupyterlab_vim v0.12.4  enabled  OK
        @ijmbarr/jupyterlab_spellchecker v0.1.6  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v2.0.7  enabled  OK
        jupyterlab-plotly v4.11.0  enabled  OK
        plotlywidget v4.11.0  enabled  OK

</pre>
</details>

**Comment by krassowski** [comment]
Re-sortining - see #369 and https://github.com/jupyterlab/jupyterlab/issues/9048. This is an upstream issue in JupyterLab which was already fixed but the new version of JupyterLab was not yet released.

Re-suggesting a path in this place - this is a suggestion from the Python kernel that you use (IPython); it would need to be addressed over there.

**Comment by joelostblom** [comment]
> Re-sortining - see #369 and jupyterlab/jupyterlab#9048. This is an upstream issue in JupyterLab which was already fixed but the new version of JupyterLab was not yet released.

Great, thanks!

> Re-suggesting a path in this place - this is a suggestion from the Python kernel that you use (IPython); it would need to be addressed over there.

Hmm, but how come it works in vscode when the same conda environment is set as the kernel?

**Comment by joelostblom** [comment]
This is also working after updating IPython to 7.18, sorry for the noise!
