### ISSUE TITLE
Context menu does not get initialized when the extension is registered last

### ISSUE THREAD

**Issue by mnowacki-b** [krassowski/jupyterlab-lsp#398]
## Description

There may be a potential race condition when initializing the context menu. It currently get only registered when an even is fired when a new type is added to the `adapterManager`.
https://github.com/krassowski/jupyterlab-lsp/blob/a65019a7a5138510c568198f8179c5af1e077a5f/packages/jupyterlab-lsp/src/index.ts#L171
If the notebook adapter is added before the extension (jupyterlab-lsp) get registered; that even will be fired and potentially processed before the connection is made and the context mane will not be registered for that type.

## Reproduce

1. Edit your JupyterLab to make sure the extension (jupyterlab-lsp) is added at the end.
2. Build and run

## Expected behavior

Context menu should be initialized regardless of the order of extension initialization.

## Context

- Operating System and version: rhel7
- Browser and version: Chrome 86.0.4240.111
- JupyterLab version: 2.2

**Comment by krassowski** [comment]
Sorry it took a while; releasing today!
