### ISSUE TITLE
Update dev setup documentation

### ISSUE THREAD

**Issue by karlaspuldaro** [krassowski/jupyterlab-lsp#411]
Following the dev steps in [CONTRIBUTING.md](https://github.com/krassowski/jupyterlab-lsp/blob/master/CONTRIBUTING.md) I came across a few issues:
1. Wrong command to create a new conda environment:
```
$ conda env update -n jupyterlab-lsp
SpecNotFound: Invalid name, try the format: user/package
```
Conda version: 4.9.2
Solution: `conda create -n jupyterlab-lsp`

2. Node version expected to be 12+
```
$ jlpm
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @typescript-eslint/eslint-plugin@3.10.1: The engine "node" is incompatible with this module. Expected version "^10.12.0 || >=12.0.0". Got "10.0.0"
error Found incompatible module.
```

3. Recommend Python 3.6+
As per [jupyterlab requirements](https://github.com/jupyterlab/jupyterlab/blob/master/setup.py)

**Comment by krassowski** [comment]
Fantastic work! Thank you. Please note that node 12 is not required. The message you see says:

```
Expected version "^10.12.0 || >=12.0.0".
```

meaning that the old versions of node 10 are not supported. We do run CI tests on node 10 (10.15.3 at current), see https://github.com/krassowski/jupyterlab-lsp/runs/1414536659?check_suite_focus=true#step:6:156

However, now that you have changed it on #412 I am willing to consider accepting the change if @bollwyvl agrees. On one hand, it would make sense to recommend the newer version, on the other the 10.x will not be EOL before 2021-04-30.

**Comment by bollwyvl** [comment]
For the current line that supports jlab2, I feel we need to keep testing on
node10, as a number of os package managers don't have anything newer, and
errors at that part of the stack are not fun at all. Better we catch them
in CI!

For jlab3, devs will need node12... Users will not need node at all...
except for the node-based language servers. So we'll probably _still_ need
to keep testing on 10 until that above-mentioned EOL. But with jlab3, it
will be safe to do all of our up-front build stuff on one Linux machine, as
fast as possible, archive the wheels, and use those on the other platforms,
so the language servers are the only thing that need to be installed with
jlpm.... And we should be able to cache the yarn-packages as well.

So anyhow: getting these right, for all involved audiences is hard. having
the version check thing in place, irrespective of what the actual number is
today, is of value in its own right, as well help us avoid problems in the
future.

**Comment by karlaspuldaro** [comment]
Thank you for the feedback, I agree with all being said.
I can change notes back to node 10 on my PR if the plan is to continue testing it until next year.
Since I had node 10.0.0 and it wasn't enough, in that case I suggest updating the docs with the minimum expected then (10.12.0 from the logs)? Then make it more clear in #405  that node12 is required for devs?

**Comment by krassowski** [comment]
I think that this was fixed already. Many thanks @karlaspuldaro!
