### ISSUE TITLE
as_uri and url_parse do not work properly when using windows server

### ISSUE THREAD

**Issue by tchampet** [krassowski/jupyterlab-lsp#419]
I am new to windows and I am no strong-experienced developper.
My python installation is on my computer and I am working on a jupyter project on a server.
I have some bugs related to the paths.py functions **normalized_uri** and **file_uri_to_path**.

The project is in this folder :
> R:\Service interne\2020

which becomes this uri path :
> file://cyt-files01/service/Service%20interne/2020/

with "cyt-files01" being the UNC path servername, and "service" being the UNC path share from what I understood.

In **file_uri_to_path** function, after urlparse and taking the name of the path, the result path is :
> /service/Service interne/2020

Which is not the path of the folder I am working in. Consequently, when creating the .virtual_documents folder, it creates _R:/service/Service interne/2020/.virtual_documents_ instead of _R:/Service interne/2020/.virtual_documents_ . 

In some cases (I cannot reproduce this at the moment), it creates it in the folder I am working in. Giving:  _R:/Service interne/2020/service/Service interne/2020/.virtual_documents_. 
For longer path, it was problematic as it causes a windows error for to long pathes.

Working directly on the machine works as the parsing is good.

**Comment by bollwyvl** [comment]
Yeah looks like a real bug, but unfortunately very hard for us to test (and
keep testing).

In CI we have access to multiple drives (c: and d:) but not real UNC paths.

And there's literally nothing we can do about long paths from our side,
though I vaguely remember some registry hack which enables it.

Unfortunately all I can say is "PRs welcome" at this point...
