### ISSUE TITLE
How to config language-server?

### ISSUE THREAD

**Issue by yanyu0517** [krassowski/jupyterlab-lsp#438]
I have installed the python-language-server and jupyter-lsp, and step to config the servers. Maybe it's a simple question, I open the Advanced Settings editor in JupyterLab (Settings > Advanced Settings Editor), and find this like below:
![image](https://user-images.githubusercontent.com/5326851/103116796-ab72b600-46a2-11eb-85ec-e2a47d76b1c7.png)
Which settings should I write the configuration？

**Comment by bollwyvl** [comment]
Looks like some missed steps... There should be a "Language Servers," and a
bunch of other related things in the settings page. You suggest you may
have "step to config"... You pretty much have to do all of the steps, and
some in a specific order.

Anyhow: It's very hard to say more without more information about your
system: please try going back through the new issue template, and trying
those information gathering tools about versions, etc.

**Comment by ElLorans** [comment]
I have the same issue on Win10: after running `conda install -c conda-forge jupyter-lsp-python`, I don't see a "Language Servers" item in the menu.
This is my Jupyter Version: `
``jupyter core     : 4.7.0
jupyter-notebook : 6.1.6
qtconsole        : not installed
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : 3.0.1
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.0.8
traitlets        : 5.0.5```

Obviously `conda install -c conda-forge python-language-server` returns that all requested packages are already installed. What installation step am I missing?

**Comment by bollwyvl** [comment]
Sorry, $DAY_JOB and $WTF_WORLD has kept me from getting the new release up
on conda-forge. Should be up within the hour.

**Comment by bollwyvl** [comment]
This PR is merged:

https://github.com/conda-forge/jupyter-lsp-feedstock/pull/10

so the hour clock actually starts **now**... if we miss the replication window to the CDN in front of anaconda.org. But usually it's under 30 minutes.

**Comment by krassowski** [comment]
@ElLorans also, please do check the upgrade instructions here: https://github.com/krassowski/jupyterlab-lsp/releases/tag/v3.0.0 if upgrading rather than installing for the first time.

**Comment by bollwyvl** [comment]
Cf builds up for real now

**Comment by ElLorans** [comment]
Now it works! Thank you very much.
A simple question: How do I config now?
I have saved
```
{
    "continuousHinting": true,
        "showDocumentation": true,
            "theme": 'material'
}
```
in the Code Completion and 
```
{
  "language_servers": {
    "pyls": {
      "serverSettings": {
        "pyls": {
          "plugins": {
            "pydocstyle": {
              "enabled": true
            },
            "pyflakes": {
              "enabled": false
            },
            "flake8": {
              "enabled": true
            }
          }
        }
      }
    }
  }
}
```
in the Language Server tab but I still don't see autocompletion. Is there any step I likely missed?

**Comment by krassowski** [comment]
@ElLorans please fill in the "bug issue" template - we need more information about your environment to have an educated guess. Screenshots would certainly help too. Also please remember to include the logs from console (both the browser developer console and from the terminal) and the pip/conda info - as instructed by the template.

**Comment by ElLorans** [comment]
My bad, I forgot about `conda install -c conda-forge python-language-server` and now I start to see pycodestyle and flake8 warnings as well as highlighting. Thanks for the amazing support.
