### ISSUE TITLE
LSP can't work in dev mode

### ISSUE THREAD

**Issue by yanyu0517** [krassowski/jupyterlab-lsp#439]
I have installed LSP, and it worked well in normal mode. 
When I start jupyter lab in dev mode (jupyter lab --dev-mode --watch), it didn't work anymore.
Is there some way to enable LSP in dev mode?

**Comment by bollwyvl** [comment]
Please, _any_ more information than "didn't work" would help. As suggested
your previous issue, the issue template is not there to punish you, but to
save all of us time in communicating back and forth to see if there is a
bug, or a way we can document things better, or something special about
your computer that we can't do anything about today.

**Comment by yanyu0517** [comment]
I had read the issue template, and try to classify my problem into a template, But I failed.

**Bug report**? I don't think it's a bug
**Documentation request**? your doc is perfect
**Intent to Implement**? I don't know whether you have come it true
**Auto-detected Language Server Support**? I even don't know what that means
**Request Bring-your-own Language Server Support**? Absolute not

> Please, _any_ more information than "didn't work" would help

I have no idea do you read my issue. What I mean the LSP didn't work, just like I didn't install it, so I really couldn't provide any detailed information.
So can you descript what you need? Maybe a screenshot?

**Comment by bollwyvl** [comment]
Yeah, read your issue.  You want dev mode, it "doesn't work". Look inside
the templates. What are you running (os, lab, python, node). What are you
observing when it didn't work on dev mode (actual terminal logs, console,
etc). What are you expecting. When "--dev-whatever" is involved, sometimes
it's unclear what you're trying to do and therefore hard for us to help

**Comment by krassowski** [comment]
[The JupyterLab documentation](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#developing-a-prebuilt-extension) explains that extensions are disabled by default in the dev mode but you can enable them using `--extensions-in-dev-mode`, so your command would be:

```
jupyter lab --dev-mode --extensions-in-dev-mode
```

I will close this issue for now as it does not appear to be something wrong with the extension, but a generic question about advanced usage of JupyterLab. Sorry I missed it earlier.
