### ISSUE TITLE
websocket server do not send a ping frame to client, make websocket frequently lost connection throught a reverse proxy like nginx

### ISSUE THREAD

**Issue by franckchen** [krassowski/jupyterlab-lsp#458]
## Description

Hi~:
Notebook websocket will send ping frame periodically, by default the interval is 30 sec.
https://github.com/jupyter/notebook/blob/1550410229e302ecf74d5bf82d5caba6e6296a64/notebook/base/zmqhandlers.py#L162

but lsp websocket will not. bcz the handler override the open method.
https://github.com/krassowski/jupyterlab-lsp/blob/c9ba03bd85cef7b8f923099205bf7b0d958f3892/python_packages/jupyter_lsp/jupyter_lsp/handlers.py#L25

From my view. I think it's very necessary to send a ping frame periodically.bcz in production environment,the request are ofen forwarded through a reverse proxy like nginx, and alway nginx is set with a read timeout rule.If there is no ping frame, the websocket connection may not transmit any data for a long time, and then trigger ngnix timeout rule, the ws connection will be force closed by nginx.
 
From nginx document:

> By default, the connection will be closed if the proxied server does not transmit any data within 60 seconds. This timeout can be increased with the proxy_read_timeout directive. Alternatively, the proxied server can be configured to periodically send WebSocket ping frames to reset the timeout and check if the connection is still alive. 

**the recommendation is the set websocket server to periodically send WebSocket ping frames~**

so how about read the notebook configuration and send the ping frame?

## Reproduce

use jupyterlab-lsp with nginx together

## Expected behavior

websocket server read the notebook configuration and send the ping frame like notebook websokcet handler
## Context

- Operating System and version: any
- Browser and version: any
- JupyterLab version: any

<details><summary>Required: installed server extensions</summary>
<pre>
≈
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
≈
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
≈
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>≈
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>

</pre>
</details>

**Comment by krassowski** [comment]
Indeed, thank you! Calling `super().open` to trigger `WebSocketMixin.open` would probably suffice.

**Comment by franckchen** [comment]
lol, i need to thx for you first .I work for Baidu, Chinese biggest search engine .And im a jupyter developer. i've developed many jupyterlab plugins like jupyterlab-monaco-editor(not open source) for my company and another notebook named baidu notebook.
bcz of you amazing work they works so good. 


https://user-images.githubusercontent.com/5096940/103898341-c0822700-512f-11eb-933f-f35e455bf1f4.mov

https://user-images.githubusercontent.com/5096940/103899086-d47a5880-5130-11eb-9afd-b6645b6d39f0.mov

https://user-images.githubusercontent.com/5096940/103899468-684c2480-5131-11eb-9be4-87a6d58ec24a.mov
