### ISSUE TITLE
Auto-detect Julia language server

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#464]
It would be nice to suport the Julia language server. There is one here: https://github.com/julia-vscode/LanguageServer.jl

A few folks in Julia community brought this up but have not opened an issue yet:
- https://discourse.julialang.org/t/is-it-possible-to-use-julias-languageserver-jl-with-jupyterlabs-jupyterlab-lsp-extension/40945
- https://discourse.julialang.org/t/jupyter-lab-lsp-argv-path/48115/2

Julia is on conda but only for Mac and Linux: https://anaconda.org/conda-forge/julia (~60 MB). How do we want to approach this?

**Comment by bollwyvl** [comment]
I had a run at getting it packaged with conda, wasn't very satisfied with the results (but its always worth another look). Much like scala/coursier/almond, I just don't have a way that I can confidently tell someone they can install it and keep it running.

In GHA, however, I'm almost certain there is a `setup-julia`, that's Someone Else's Problem, etc. And I'd be more willing to make an exception for Julia than most other languages. But generally, maybe things like this could land in a `contrib` or `recipes` folder if they could _even be reproduced on CI on a single os/runtime workflow_, without having to go through the full gamut. 

As we discussed, we need to keep _at least one language server_ running on all supported platforms, and for the time being, that's probably `pyls`, unless we can really make the case for `jedi-language-server` (maybe it can).

By the same token, I don't think we'd want to drop R (although, I am not a user, so don't have much to add).

**Comment by krassowski** [comment]
Yes, https://github.com/julia-actions/setup-julia will give us certainly more up-to-date versions than conda (given that Julia community has not embraced conda yet - there is a hope that mamba could convince some folks, but majority is likely to install from binaries other than conda so maybe better to use a setup action instead).
