### ISSUE TITLE
Less verbose frontend

### ISSUE THREAD

**Issue by fcollonval** [krassowski/jupyterlab-lsp#471]
## Elevator Pitch

Add a frontend settings to silence LSP - I don't know in which settings category it would make the more sense.

## Motivation

The frontend extension is printing lots of messages in the web browser console. This make it quite crowded and can make looking for other messages complicated.

## Design Ideas

The idea would be to replace call to `console.log` to a wrapped version that call console.log only if the ad-hoc setting is true.

**Comment by krassowski** [comment]
Sorry about that! I am tracking this in #442.

**Comment by fcollonval** [comment]
> Sorry about that! I am tracking this in #442.

Don't be sorry - this extension is amazing. Just pointing out a small improvement ;)
