### ISSUE TITLE
Autocompletion does not work after "Restart Kernel and Run All Cells"

### ISSUE THREAD

**Issue by dschaehi** [krassowski/jupyterlab-lsp#475]
## Description

Autocompletion does not work after "Restart Kernel and Run All Cells". 

## Reproduce
Let's say the notebook has got the following three cells:
Cell 1: import math
Cell 2: math.sin(1)

Now do the following:
1. Run "Restart Kernel and Run All Cells"
2. Create a new cell "Cell 3".
2. Go to Cell 3 and write "math."

## Expected behavior

Autocompletion should work, but it does not.
Autocompletion "works" if I close and reopen the notebook and run the cells 1 and 2 one by one.

## Context

- Operating System and version: Ubuntu 18.04 LTS
- Browser and version: Chrome
- JupyterLab version: 3.0.5
--
Update: Content changed according to https://github.com/krassowski/jupyterlab-lsp/issues/475#issuecomment-761524398

**Comment by krassowski** [comment]
Thank you! This is incredibly helpful, it may let me pinpoint a very weird issue that I was experiencing too. One note: I am not able to reproduce if the cell 3 already exists (this is it works fine in that case). The problem appears to be that once the "Restart Kernel and Run All Cells" command gets executed anew new cells don't get added to our virtual document for some reason. It needs more investigation, but certainly sets us on a good path.

**Comment by dschaehi** [comment]
@krassowski  Glad that this helps! I was enjoying jupyter-lsp a lot, but found out that autocompletion, which is one of the most important features, was not reliable. Hope this get fixed soon!

**Comment by krassowski** [comment]
Another note: It is not specific to autocompletion, all features are not working in the new cells.

For the autocompletion, the slowness is due to several factors, including the default python language server being slow, it transmitting all docstrings every single time over air (while other serves only send docstrings when the completion is hovered over though we have not implemented this yet) etc. Long story short, for better completion you can either:
- experiment with jedi-language-sever instead of pyls or wait until we support it out of the box
- try to contribute to pyls to improve their performence

**Comment by dschaehi** [comment]
Oh I see. No, by reliability I was not actually referring to the general speed of the autocompletion, but the issue with the kernel restart (I am so far happy with the general speed of the autocompletion). If this current issue gets solved, then I can imagine that jupyter-lsp will be one of my default extensions for JupyterLab. Thanks for this nice extension by the way!

**Comment by krassowski** [comment]
@dschaehi please do check out the new [release 3.1](https://github.com/krassowski/jupyterlab-lsp/releases/tag/v3.1.0) and let us know if you encounter any issues. thanks again for reporting with clear, reproducible example!

**Comment by dschaehi** [comment]
@krassowski it works like a charm. Many thanks for the quick fix!

**Comment by dschaehi** [comment]
> @dschaehi please do check out the new [release 3.1](https://github.com/krassowski/jupyterlab-lsp/releases/tag/v3.1.0) and let us know if you encounter any issues. thanks again for reporting with clear, reproducible example!

Oh, although autocompletion works, the diagnostics panel does not seem to work. Could you try to create some warnings in the code and then do "Restart kernel and run all cells" to check whether you can see the warnings in the diagnostics panel?

**Comment by krassowski** [comment]
@dschaehi the issues are now fully resolved in 3.3. Please give it a try.

**Comment by dschaehi** [comment]
The problem is now gone. Thanks!
