### ISSUE TITLE
Conda Environments/Kernels Documentation Request

### ISSUE THREAD

**Issue by capdevc** [krassowski/jupyterlab-lsp#501]
I'm trying to understand what (`jupyter-lsp`, `jupyterlab-lsp`, `pyls`) needs to be installed where in a multi-kernel/conda env environment.

I'm currently running jupyterhub and launching a docker image that has a bare bones conda python environment, mostly just stuff needed for jupyterlab itself so that it won't need to be updated super frequently. I'm using separate conda environments (located on shared, persistent storage) as kernels with the [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) package.

To illustrate, imagine I have two conda envs, each with `ipykernel` installed

`base_env` <- `jupyterlab`, `jupyter-lsp`, `jupyterlab-lsp`, `pyls` installed here
`work_env` <- `some_package` installed here

With this setup, and the `work_env` kernel selected, I don't get documentation, pyls completions etc. for `some_package`. Is there a setup/config that would fix that? Or would I need to be running jupyterlab from `work_env`? My limited understanding suggests that I would need pyls installed and running in `work_env` and to somehow configure jupyterlab-lsp to talk to that server rather than the one it starts running from my `base_env`. 

Some documentation on how that works would be awesome

**Comment by bollwyvl** [comment]
yeah, even though we make extensive use of conda for testing, etc. we're unlikely to put any particular smarts in this codebase to deal with multiple environments... once you get outside of what's on PATH, it's a pretty wild world, and none of our autodetection stuff is going to work.

Have a gander at the [docs](https://jupyterlab-lsp.readthedocs.io/en/latest/Configuring.html#language_servers)... you will need to build up a `jupyter_server_config.json` that has all your paths hardcoded, and probably turn _off_ autodetection.

**Comment by capdevc** [comment]
I suspected that may be the case (pyls has to be started from the relevant environment). It would have been nice to be able to do something dynamic where I could repoint jupyterlab-lsp to a different language server when switching kernels, but I get that that's out of scope for you guys. The path of least resistance may be for us to switch between single conda env jupyterlab docker images rather than switching between kernels.

Thanks for the clarification!

**Comment by krassowski** [comment]
> repoint jupyterlab-lsp to a different language server when switching kernels

this by itself should be possible in the future, assuming that both kernels are in the same environment (technically it is already the case - we switch between language servers depending on kernel response but right now this is only switching when the language changes and cannot be adjusted from the user interface)

**Comment by bollwyvl** [comment]
Yeah, we'll likely want some dynamically configurable `M x N` affinity matrix for kernels (and paths for files) to language servers (and client configurations) at some point when we really attack the cardinality problem (#184). Stepping outside of code-town... one could imagine spelling/grammar checking in different languages based on the file path.
