### ISSUE TITLE
Tabbing through completion hints

### ISSUE THREAD

**Issue by filyp** [krassowski/jupyterlab-lsp#513]
## Elevator Pitch

When completion hints are shown, it would be nice to press tab to walk through the hints, instead of down arrow. It would be very useful for touch typers.

## Motivation

When I type, I don't move from the home row too often (touch typing + vim). The exception is using autocompletion. Moving to the arrows breaks the flow a bit, but it happens very often when coding. Just tabbing through the completions would be really handy.
Optionally shift+tab could serve as up arrow, but it's not so essential.

**Comment by krassowski** [comment]
I agree, this is a nice and useful feature/setting to have. This might  however need to be addressed upstream in JupyterLab as currently the keybindings to the completer are implementation detail of the `Completer` widget (see [here for the implementation](https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/completer/src/widget.ts#L402-L465)). I already added it to the completer refactor whishlist for 4.0 (so basically in ~1 years time), but if you would like to tackle it sooner, please do consider opening an issue and PR on JupyterLab repository (please do tag me for review).

I am thinking that JupyterLab should also allow vim-like <kbd>ctrl</kbd> + <kbd>p</kbd> and all of this should ideally be independent of whether there is an extension that supplies extra completer capabilities or not.

**Comment by krassowski** [comment]
See https://github.com/jupyterlab/jupyterlab/pull/10147

**Comment by fsondej** [comment]
:o great news!

**Comment by filyp** [comment]
I see it working fine so I'm closing.
Thanks!
