### ISSUE TITLE
Issue in LSP stopping Jupyterlab Build

### ISSUE THREAD

**Issue by ParasKoundal** [krassowski/jupyterlab-lsp#518]
Hi,
I am facing an issue in jupyterlab build. The issue seems to originate from LSP. No solution online seems to work. Errorlog from "jupter lab build" 

<details>

```
[LabBuildApp] Building in /cr/users/koundal/miniconda3/share/jupyter/lab
[LabBuildApp] Node v12.4.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.64s.

[LabBuildApp] > node /cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 1.25s.

[LabBuildApp] > node /cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab-classic/application' in '/cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib'
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1656:28
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:708:13
    at eval (eval at create (/cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:632:24
    at /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:781:5
    at finishWithoutResolve (/cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
resolve '@jupyterlab-classic/application' in '/cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib'
  Parsed request is a module
  using description file: /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/node_modules doesn't exist or is not a directory
      looking for modules in /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules
        single file module
          using description file: /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/package.json (relative path: ./node_modules/@jupyterlab-classic/application)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules/@jupyterlab-classic/application doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules/@jupyterlab-classic/application.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules/@jupyterlab-classic/application.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules/@jupyterlab-classic/application.wasm doesn't exist
        /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules/@jupyterlab-classic/application doesn't exist
      /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@krassowski/node_modules doesn't exist or is not a directory
      /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules
        single file module
          using description file: /cr/users/koundal/miniconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules/@jupyterlab-classic/application)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab-classic/application doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab-classic/application.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab-classic/application.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab-classic/application.wasm doesn't exist
        /cr/users/koundal/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab-classic/application doesn't exist
      /cr/users/koundal/miniconda3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /cr/users/koundal/miniconda3/share/jupyter/node_modules doesn't exist or is not a directory
      /cr/users/koundal/miniconda3/share/node_modules doesn't exist or is not a directory
      /cr/users/koundal/miniconda3/node_modules doesn't exist or is not a directory
      looking for modules in /cr/users/koundal/node_modules
        single file module
          No description file found in /cr/users/koundal/node_modules/@jupyterlab-classic or above
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /cr/users/koundal/node_modules/@jupyterlab-classic/application doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /cr/users/koundal/node_modules/@jupyterlab-classic/application.js doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            /cr/users/koundal/node_modules/@jupyterlab-classic/application.json doesn't exist
          .wasm
            Field 'browser' doesn't contain a valid alias configuration
            /cr/users/koundal/node_modules/@jupyterlab-classic/application.wasm doesn't exist
        /cr/users/koundal/node_modules/@jupyterlab-classic/application doesn't exist
      /cr/users/node_modules doesn't exist or is not a directory
      /cr/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 168, in start
    raise e

[LabBuildApp]   File "/cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 165, in start
    app_options=app_options, production = production, minimize=self.minimize)

[LabBuildApp]   File "/cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 470, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

[LabBuildApp]   File "/cr/users/koundal/miniconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

</details>

**Comment by krassowski** [comment]
Thanks for highlighting this. I don't think that this would happen if you installed using our official installation instructions (with `pip install` or `conda install`). Building the extension from source is now intended for developers only (and currently requires dev-dependencies to be installed). If you still wish to install from source, please install `@jupyterlab-classic/application` from source too to fix the problem.

I wonder if there is a way for us to keep the `IClassicShell` usage in [adapter_manager](https://github.com/krassowski/jupyterlab-lsp/blob/4237299de807ca71e3afc2495f41efa6a31da8d3/packages/jupyterlab-lsp/src/adapter_manager.ts) without forcing users who decide to install from source (although they should not) to also install `jupyterlab-classic`? Would moving `@jupyterlab-classic/application` to dependencies be enough or does it pull a lot of stuff?

CC @jtpio

**Comment by krassowski** [comment]
I see you closed the issue - I hope you managed to solve it :). May I ask if installing @jupyterlab-classic/application helped, or did you decide to install the pre-built version? It would very much help to know what are the user needs to improve it in future releases (and e.g. if there is an outdated installation instruction somewhere out there that could be corrected).

**Comment by jtpio** [comment]
> I wonder if there is a way for us to keep the `IClassicShell` usage in [adapter_manager](https://github.com/krassowski/jupyterlab-lsp/blob/4237299de807ca71e3afc2495f41efa6a31da8d3/packages/jupyterlab-lsp/src/adapter_manager.ts) without forcing users who decide to install from source (although they should not) to also install `jupyterlab-classic`? Would moving `@jupyterlab-classic/application` to dependencies be enough or does it pull a lot of stuff?

Normally `@jupyterlab-classic/application` should be very similar to `@jupyterlab/application`. Not sure why it would behave differently. For reference this is the list of [its dependencies](https://github.com/jtpio/jupyterlab-classic/blob/4e32baa08c86cdc269f9e75843f68208b1458f46/packages/application/package.json#L45-L57).

Maybe it just needs to also be specified in `peerDependencies` just like `@jupyterlab/application`?

https://github.com/krassowski/jupyterlab-lsp/blob/4237299de807ca71e3afc2495f41efa6a31da8d3/packages/jupyterlab-lsp/package.json#L107

**Comment by jtpio** [comment]
Also somehow related: an issue to consider using `peerDependencies` for JupyterLab prebuilt extensions: https://github.com/jupyterlab/jupyterlab/issues/9724

**Comment by krassowski** [comment]
But `"@jupyterlab/application": "^3.0.0"` will always be there, but classic will not, right? I am afraid that the class import might need to be reverted and replaced with some kind of duck typing or a more general type instead :(

**Comment by krassowski** [comment]
But I hope I am wrong. In either case some few hundreds users might have just received broken update. I will work on this in the evening.

**Comment by bollwyvl** [comment]
ick. Maybe we make anything that knows about non-core into another package? It doesn't even have to be a separate python package (that's why [this is a list](https://github.com/krassowski/jupyterlab-lsp/blob/master/python_packages/jupyterlab_lsp/jupyterlab_lsp/__init__.py#L6)), but it maybe _should_ be, so that we can specify a tested range of `jupyterlab-classic` compatibility.

Especially if a separate python package, this would also serve as an end-to-end example of how to integrate a custom lab downstream with `jupyterlab-lsp`, which has value in its own right.

**Comment by krassowski** [comment]
I'm thinking that it would have been easier if there was a way to still publish to npm (for extension developers) but prevent users to install from there (and especially to upgrade from 2.x) and only officially support the federated version.

**Comment by krassowski** [comment]
> Maybe we make anything that knows about non-core into another package? 

It would be difficult to keep this conditional logic then:

https://github.com/krassowski/jupyterlab-lsp/blob/4237299de807ca71e3afc2495f41efa6a31da8d3/packages/jupyterlab-lsp/src/adapter_manager.ts#L145-L166

**Comment by krassowski** [comment]
Looking at the error again:

```
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab-classic/application' in
'/opt/hostedtoolcache/Python/3.6.12/x64/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib'
```

maybe it is enough to add it to webpack externals? I remember it was a pain to modify webpack config for extensions, but I will try...

**Comment by krassowski** [comment]
This comment: https://github.com/jupyterlab/jupyterlab/issues/4328#issuecomment-723964931 indicates that it might not be possible for source extensions, is this correct @jtpio? I did try to add it as a peer dependency but it did not help.

**Comment by jasongrout** [comment]
> I'm thinking that it would have not be a problem if there was a way to still publish to npm (for extension developers) but prevent users to install from there (and especially to upgrade from 2.x) and only officially support the federated version.

A couple of thoughts:

1. We at least partly avoid this problem in core jlab by separating our packages into a library package that contains the tokens and relevant widgets and functionality, and separately a very thin `-extension` package that imports the token and library and is the actual jlab extension. It doesn't completely alleviate the issue, because you might want to publish the extension package too for people to modify.
2. Here are three ideas for publishing an npm package that was not extension, while still being able to build a prebuilt extension from it:
  A. Remove the `jupyterlab.extension` (and `jupyterlab.mimeExtension` probably) keys from the package.json before publishing to npm. IIRC, those are the keys JupyterLab uses to determine if a package is really an extension. Also, remove the `jupyterlab-extension` keyword from the npm package.
  B. Remove those two package.json keys permanently, and just add them back in when prebuilding an extension.
  C. Perhaps `jupyter labextension build` should have some command line arguments to give those two extension entry points, which would override what it finds in the package.json, i.e., something you could use like `jupyter labextension build --extension ./lib/plugin.js --mimeExtension ./lib/mime`. In this case, like in the option above, we would permanently remove the keys from package.json.

**Comment by jasongrout** [comment]
I made https://github.com/jupyterlab/jupyterlab/issues/9807 to track making it officially supported how to publish an npm package that is not a source extension, but which is the basis of a prebuilt extension.

**Comment by krassowski** [comment]
So [here](https://github.com/krassowski/jupyterlab-lsp/pull/526/files#diff-212d532258fbc8181f7aa6fa50dcff2961a19ef8fd5375a7539decfff6243dadR12-R147) is the patch solution that worked (revert to `app.shell` and use `import type` instead of `import`). This solution is obviously only helpful for the very specific case of accessing `jupyterlab-classic` shell and does not solve the general case so the discussion is still worth having.

1. Yes, having the token published as a separate lightweight package would help.
2. I though about about removing the keyword but that would not solve this unpleasant situation for users who already installed the broken version.

Another lesson is that it is worth to have a CI task that tries to install from source and build lab (i.e. testing that the federated version works is not enough). Might be worth including in the cookiecutter.

**Comment by jasongrout** [comment]
> Might be worth including in the cookiecutter

Would you mind opening an issue in the cookiecutter to track that idea?
