### ISSUE TITLE
Need #noqa marker for monkeypatching imports

### ISSUE THREAD

**Issue by michaelaye** [krassowski/jupyterlab-lsp#519]
I hope it's okay to do this without the full-shebang of infos, as the case should be pretty clear.

None of the usual linters (at least the ones I know) can cope with the monkeypatching imports like these:

```python
import hvplot.pandas 
import hvplot.xarray 
```

that simply enable `hvplot` as a method in pandas and xarray objects.
These imports will always be marked as "not-used" because a normal linter wouldn't be able to catch this:
![image](https://user-images.githubusercontent.com/69774/107841588-4c175500-6d79-11eb-8fd3-2658798e9211.png)

And this is fine as long as there's a way to tell the linter to ignore a line by using something like this:

```python
import hvplot.pandas  # noqa
import hvplot.xarray  # noqa
```
(= No Quality Assurance)
(As you can see from the screenshot, I tried if it helps.. ;) )
So , if we could get a marker like that for jlab-lsp, that would be sweet, so that I can have "clean" lint! 

Thanks again for your plugin!

**Comment by bollwyvl** [comment]
Which exact linter is complaining e.g. include the diagnostic panel (opened from the context menu) in the screenshot? Very likely, it has a config file which will allow you to set ignores.

At present, we're reporting exactly what the language servers are telling us... we've considered adding a client-side filtering mechanism (initially through some _Advanced Settings_, but probably driven through that panel, or something, eventually) but that opens a whole other can of worms.

**Comment by michaelaye** [comment]
ah, I see, this was pyflakes, as I forgot to activate the recommended settings from your README where pyflakes is deactivated.
But I also failed to understand who is reading/filtering a #noqa switch.
Anyway, I switched to flake8 and the #noqa is being honored. Closing!
