### ISSUE TITLE
Where is the configuration file of jupyterlab-lsp? 

### ISSUE THREAD

**Issue by dclong** [krassowski/jupyterlab-lsp#530]
## What I am trying to do...

I'm trying to figure out the location of jupyterlab-lsp configuration file. 
I try to search text files under paths suggested by `jupyter --paths` and the only file look close to me is the file `/usr/local/share/jupyter/labextensions/@krassowski/jupyterlab-lsp/schemas/@krassowski/jupyterlab-lsp/plugin.json`. However, it still differs significantly from what I see in advanced settings. 
![image](https://user-images.githubusercontent.com/824507/108293465-856d0d80-7149-11eb-8733-88f5b25655a6.png)

## How I would like to learn how to do it...

Have this clearly documented in [Configuring](https://github.com/krassowski/jupyterlab-lsp/blob/master/docs/Configuring.ipynb)

**Comment by bollwyvl** [comment]
Everything in the advanced settings is stored in the user settings
directory:

https://jupyterlab.readthedocs.io/en/latest/user/directories.html#jupyterlab-user-settings-directory

A link to this documentation site is also available from the help menu in
lab (though maybe not this specific page).

**Comment by krassowski** [comment]
Unless configured otherwise (see JupyterLab documentation), it should be in:

```
ls $HOME/.jupyter/lab/user-settings/@krassowski/jupyterlab-lsp/
```

**Comment by dclong** [comment]
Is there a system-wide configuration file for jupyterlab-lsp?

**Comment by bollwyvl** [comment]
No there is no global config file.

We only touch/read:
- the $PREFIX/{etc,share} locations you get off "jupyter paths" and
"jupyter lab paths"
- a .virtual_documents folder where you launch lab, so that notebooks work
with language servers

**Comment by dclong** [comment]
Thank everyone for the useful info!
