### ISSUE TITLE
Server detection configuration files are not passed to us from config directories

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#535]
Placing LSP server config in jupyter_notebook/server_config.d does not seem to work. See #534 for details; using `jupyter_server_config.json` still works. The server apps detects the json files:

> [ServerApp] Paths used for configuration of jupyter_server_config:
>   etc/jupyter/jupyter_server_config.d/pyright.json

in several passes. If this is an upstream issue, it needs to be looked into; if this is something at our end, we need to fix/update the docs.

**Comment by krassowski** [comment]
Any immediate thoughts @bollwyvl?

**Comment by bollwyvl** [comment]
Yeah, it's weird it doesn't find it... but we should definitely _not_ be distributing a `jupyter_(server|notebook)_config.json`, as that gets updated by command line stuff (`serverextension enable`, etc)... nothing that has a cardinality of 1 can be shared by more than one extension, and as we've seen, nobody runs _just_ our stuff.

I'll have a look at validating the setup, but getting it work work with `conf.d` is **critical**.

Basic plan:
- make a `any_conf_d` fixture which gives all the permutations across `server` and `notebook`
- validate that the manager loads them

At present, we _don't_ actually instantiate the parent application directly (which is part of why the migration was so straightforward).

We might also need to make the smoke tests more angry.

**Comment by bollwyvl** [comment]
Oh, yeah, it is an upstream issue... I've had to work around this before on [jupyterlab-starters](https://github.com/deathbeds/jupyterlab-starters/blob/master/src/jupyter_starters/manager.py#L85-L94).

I don't think the contract was ever, "you can configure any HasTraits", just "you can configure NotebookApp or ServerApp". It may not even be feasible for the general case.

When `conf.d` was added to `notebook` (mainly to remove the need for install-time executed code), there was pushback against actually adding it to the underlying `triatlets.config` system, as it doesn't actually make a claim about where config files go on disk, so all the `Application` subclasses have to implement it themselves.

I'll adapt my approach from starters, and while i'm at it, I could add an API route to reload the config, such that folk can put a file in place and have new servers show up... probably won't touch any JS on the PR, though...

**Comment by bollwyvl** [comment]
#538 is looking good... didn't mess about with dynamic re-configuration, there's probably a lot to consider about that, and actually having the behavior we've had in the docs _forever_ seems more important than that particular async design discussion.
