### ISSUE TITLE
Documentation theme and markdown parser

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#540]
Two topics to discuss:
- should we switch to the [PyData Sphinx Theme](https://github.com/pydata/pydata-sphinx-theme) which is already used in Jupyter documentation of multiple core projects (but not JupyterLab), as well as pandas, numpy etc?
- should we switch away from [recommonmark](https://github.com/readthedocs/recommonmark) which does not seem to receive much attention nowadays to [MyST](https://myst-parser.readthedocs.io/en/latest/index.html) parser and [MyST-NB](https://myst-nb.readthedocs.io/en/latest/) to fix issues with Markdown parsing in documentation and get built-in variable substitution with Jinja2 syntax? A few examples of current issues:

### Changelog bug fixes and features at the same level (ignoring indent):

![Screenshot from 2021-02-21 16-27-00](https://user-images.githubusercontent.com/5832902/108631384-adb67e00-7461-11eb-87d4-7e3a49518dcb.png)

### Block quotes after code blocks are merged with preceding code block:

![Screenshot from 2021-02-21 16-27-34](https://user-images.githubusercontent.com/5832902/108631397-c32ba800-7461-11eb-8e0c-86bcf26b551d.png)

![Screenshot from 2021-02-21 16-28-10](https://user-images.githubusercontent.com/5832902/108631430-dcccef80-7461-11eb-8d73-e6d6b83127b9.png)

### Code blocks malformed inside lists:

![Screenshot from 2021-02-21 16-29-38](https://user-images.githubusercontent.com/5832902/108631494-0dad2480-7462-11eb-805d-4a8a073e1dd5.png)

![Screenshot from 2021-02-21 17-08-12](https://user-images.githubusercontent.com/5832902/108632544-6fbc5880-7467-11eb-966e-55eedce0b058.png)

TBD:
- [ ] Should we use [substitutions](https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#substitutions-with-jinja2), or wait until the MyST-NB matures enough to support markdown from cell outputs properly (https://github.com/executablebooks/MyST-NB/issues/317)?

**Comment by bollwyvl** [comment]
I'm +:100: on going to `myst-nb` and `pydata-sphinx-theme`. `jupyter-book` would be lovely, but currently has some issues in the packaging department. I also still owe us an icon/wordmark... `pst` sites kind of anticipate you have a wide one, but it's still tasty to have an icon (favicon, etc).

Additionally on the docs front: our architecture diagrams are getting pretty out-of-date. Updating the grpahviz wouldn't be a huge lift, but [ipydrawio](https://github.com/deathbeds/ipydrawio) is basically ready to rock for these kinds of tasks, with the editable SVG format being the strongest candidate for docs, I'd think, as they look good in github diffs.

**Comment by krassowski** [comment]
Working on it this weekend.

**Comment by krassowski** [comment]
I stumbled upon https://github.com/executablebooks/MyST-NB/issues/315 - did you encounter such a behaviour before, or is it something with my setup?

**Comment by chrisjsewell** [comment]
Any feedback for MyST welcome, I'd like to eventually look into writing an LSP with this package for MyST in JupyterLab 😄

**Comment by bollwyvl** [comment]
A myst-ls would be lovely. Pygls is for sure the way to start. Some
thoughts:

The biggest challenge in adapting an existing parser is that
code-as-it's-being-typed is broken 90% of the time, and many parsers
(rightly) are expecting well-formed content.

Having the docs propagate up would provides a remarkable experience... Did
this directive take args or not?

A challenge inherited from rst will be, well, rst, and potentially a whole
sphinx site for references/includes.

A final money piece would be spelling and grammar checking, both of which
require a lot of dependencies and configuration to be fit for purpose.

**Comment by chrisjsewell** [comment]
FYI, I've already dabbled with an RST language server: https://github.com/chrisjsewell/rst-language-server
