### ISSUE TITLE
pinfo2 substitution does not work for variables with s

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#542]
## Description

```ipython
open??
```

Gets correctly transformed to:

```python
get_ipython().run_line_magic('pinfo2',  'open')
```

but

```ipython
stat_distribution??
```

does not get transformed and results in a syntax error for Python servers that do not know about IPython syntax.

## Context

- JupyterLab version: 3.0.8
- `@krassowski/jupyterlab-lsp v3.4.0 enabled OK (python, jupyterlab_lsp)`

**Comment by bollwyvl** [comment]
What's the `.virtual_document` look like?
