### ISSUE TITLE
Error thrown when creating a new cell with shift + enter

### ISSUE THREAD

**Issue by brendan0powers** [krassowski/jupyterlab-lsp#543]
## Description

When creating a new cell by pressing shift+enter, an exception is thrown and printed to the JS console.

## Reproduce

1. Open a new notebook
2. Select the first blank cell and press shift+enter
3. A warning will be printed to the dev console
    ```
    codemirror_editor.js:185 LSP.WidgetAdapter: Editor not found in editor_to_source_line map
    ```
4. An un-caught exception is printed to the dev console
   ```
   TypeError: Cannot read property 'line' of null
    at VirtualDocument.get_editor_at_source_line (document.js:491)
    at Proxy.get_editor_at_root_line (codemirror_editor.js:276)
    at Proxy.getTokenAt (codemirror_editor.js:283)
    at Proxy.get_token_at (codemirror_editor.js:124)
    at HighlightsCM.onCursorActivity (highlights.js:87)
   ```
   
   There are other ways to reproduce this issue, they seem to happen when the focus changes. If there is no current editor available, then the cursor position is not valid.

## Expected behavior

   The first warning `Editor not found in editor_to_source_line map` should be printed, but no exception should be thrown.

## Context

This issue does not seem to be environment-dependent. I've tested on OSX and Linux, with Chrome and Chromium-based browsers. I've tested with jupyter-lsp from master, the latest stable release (v3.4.1) as well as v2.1.3.

**Comment by krassowski** [comment]
Thank you for reporting it and for the quick fix! I will merge it and include in the next release as there is no harm in doing that check.

However, I would like to understand the core source of this issue too (why is the line not yet available?). I was able to reproduce the issue on binder with JupyterLab 3.0.7, but failed to reproduce it locally with JupyterLab 3.0.8. What JupyterLab versions did you use?

An important observation is that it does not happen when inserting a cell using `esc + b + enter` which is equivalent to `shift + enter`.

**Comment by brendan0powers** [comment]
I suspect this is a race condition of some sort. I've been able to reproduce with jupyter lab 3.0.9 and 2.2.1.  I also can't reproduce using ctl + b + enter. I also can't reproduce by adding a cell from the toolbar. I've had a few reports from users that they were able to trigger the error without creating a cell at all (switching window focus, I think?). It's not clear though that they were related to this issue.

I've also noticed that control+enter will usually cause the problem, but not always.

**Comment by krassowski** [comment]
Yes, might be a race condition. My current suspicion is that `cursorActivity` event firing is wrong...

- shift + enter: `cursorActivity` fired four times
- typing a character: `cursorActivity` fired once
- adding new cell via + button in toolbar: `cursorActivity` fired 3 times
- adding new cell in command mode: `cursorActivity` fired 0 times
- entering newly created cell fro command mode: `cursorActivity` fired 2 times.

I think that `shift + enter` tries to activate next cell and if it does not exist, then add it (not necessarily in this order). I wonder if this could be improved usptream in JupyterLab. I will look into this further (in any case firing the same event four times does not look good).

**Comment by krassowski** [comment]
And thanks for the additional info!

**Comment by krassowski** [comment]
Reopening to investigate further later.

**Comment by bsyouness** [comment]
Looks like this is still happening somewhere else in the code. See #658.
