### ISSUE TITLE
continiousHinting is mentioned in README, but not in docs

### ISSUE THREAD

**Issue by sa-** [krassowski/jupyterlab-lsp#548]
## What I am trying to do...
Enable continiousHinting

## How I would like to learn how to do it...

The README mentions that one can enable continiousHinting, but doesn't say how. A link would be nice. Searching the repo for `continiousHinting` only gives the README as a result

**Comment by krassowski** [comment]
Thanks for bringing this up. There is a GIF in the README demonstrating the process:

![](https://raw.githubusercontent.com/krassowski/jupyterlab-lsp/master/examples/screenshots/autocompletion.gif)

It shows three tabs:
- Trigger.ipynb (notebook)
- Settings
- Continuous.ipynb (notebook)

The GIF first demonstrates completion on trigger (after pressing `.` in Python) in the `Trigger.ipynb` notebook, then the tab is switched to the `Settings` tab where the `continuousHinting`setting is switched and then the continuous hinting is demonstrated in the `Continuous.ipynb` notebook.

In case if you wonder how to open the Settings tab, please see the GIF below:

![settings](https://user-images.githubusercontent.com/5832902/109172497-bfa66280-777a-11eb-8bf7-b458cf45fde5.gif)

This GIF shows opening the `Settings` menu in the top menubar and then selecting `Advanced Settings Editor`, followed by switching between a few of the setting groups relevant to this extension.

As for why is does not show in search: I just noticed that there was a typo in the README (it says `continiousHinting` whereas it should be `continuousHinting`). **Thank you** for highlighting this issue and sorry about that (I will blame it on English not being my first language, but really it should not happen). I fixed it in https://github.com/krassowski/jupyterlab-lsp/commit/2564fe70bb6b50cdeee9a9745d2e2c660d9be541.

We now have quite a few settings and I have not figured out how to best document them online; quality GIFs would be nice but it takes surprisingly long time to record those without mistakes such as clicking in a wrong place or moving mouse in a wrong direction to keep them short (and this is a volunteer project); for now these settings are documented in the settings editor - if you find any of the descriptions there please do let us know..

**Comment by krassowski** [comment]
As for your original issue, does the GIF in README render well for you, or is there some kind of a problem in a specific browser, or environment @sa- ? I spelled out descriptions for what is shown on the GIFs in the comment above just in case if a person with a vision impairment was to navigate here (although it may take until the next JupyterLab release to be fully accessible).

**Comment by sa-** [comment]
Thanks! Your english is perfect :). Native speakers make more typos than you do.

About the gif, it does move pretty fast so the text instructions are easier to read. Thank you so much for the prompt response and for making this awesome plugin
