### ISSUE TITLE
jsonrpc-ws-proxy

### ISSUE THREAD

**Issue by SergeyPy** [krassowski/jupyterlab-lsp#56]
Good afternoon! please tell me completely confused, in what order and what to install? I seem to do everything according to the instructions and in the package.json file there is no "jsonrpc-ws-proxy", and server.js, respectively

**Comment by bollwyvl** [comment]
This is still a work in progress. Where did you get the code, how did you
install the code, what os are you on, those kinds of things, would help.

**Comment by SergeyPy** [comment]
> This is still a work in progress. Where did you get the code, how did you install the code, what os are you on, those kinds of things, would help.
> […](#)

I use Mac OS, I do everything in order as it is written in readme:

install the extension:

`jupyter labextension install @krassowski/jupyterlab-lsp`

install servers for languages of your choice. Below are examples for Python (with pyls) and R (with languageserver):

`pip install python-language-server[all]`

next, I go to the folder 

> /Users/sergejsuhinin/anaconda 3/lib/python 3.7/site-packages/jupyterlab/staging

create servers.yml file:

> langservers:
>   python:
>     - pyls
>   R:
>     - R
>     - --slave
>     - -e
>     - languageserver::run()

and execute the following commands

```
npm install
npm run build
jupyter labextension link .
```
this is where the problems arise
> node_modules/jsonrpc-ws-proxy/dist/server.js: No such file or directory

**Comment by bollwyvl** [comment]
Did you install the python portion with pip/setup.py?

**Comment by krassowski** [comment]
For normal installation (`jupyter labextension install @krassowski/jupyterlab-lsp`) you should **not** execute the following commands:

```
npm install
npm run build
jupyter labextension link .
```

These are for development install (please take a careful look at the instructions in the readme).

The readme does not say that you should go to the staging directory, but rather that the `node_modules/jsonrpc-ws-proxy/dist/server.js` is likely to be located there. The `servers.yml` should not be created in the staging directory but in your current project directory.

And, finally, as @bollwyvl, mentioned the next version (due to be published next month) will remove the necessity to configure the `servers.yml` - stay tuned.

**Comment by SergeyPy** [comment]
> For normal installation (`jupyter labextension install @krassowski/jupyterlab-lsp`) you should **not** execute the following commands:
> 
> ```
> npm install
> npm run build
> jupyter labextension link .
> ```
> 
> These are for development install (please take a careful look at the instructions in the readme).
> 
> The readme does not say that you should go to the staging directory, but rather that the `node_modules/jsonrpc-ws-proxy/dist/server.js` is likely to be located there. The `servers.yml` should not be created in the staging directory but in your current project directory.
> 
> And, finally, as @bollwyvl, mentioned the next version (due to be published next month) will remove the necessity to configure the `servers.yml` - stay tuned.


but the fact is that at this address

> /Users/sergejsuhinin/anaconda3/lib/python3.7/site-packages/jupyterlab/staging

no `node_modules/jsonrpc-ws-proxy/dist/server.js`

and I can not execute the command
` node path_to_jupyterlab_staging/node_modules/jsonrpc-ws-proxy/dist/server.js --port 3000 --languageServers servers.yml`

**Comment by krassowski** [comment]
Could you please paste the exact command you used and the contents of your `servers.yml` file - this might help to decipher the error message.

**Comment by krassowski** [comment]
Closing, as we no longer use `jsonrpc-ws-proxy`.
