### ISSUE TITLE
Expose extractor API (as separate package?)

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#561]
## What are you trying to do?

> from https://github.com/krassowski/jupyterlab-lsp/pull/560#issuecomment-803457273
>>
>> So we were trying our hand at an out-of-tree %%sparql extractor (locally) for #551... when the full built application is set up, the RegExpForeignCodeExtractor and a few of the interfaces would need to be hoisted all the way up to jupyterlab-lsp/index.ts. 

#### Plan A**

- in `packages/jupyterlab-lsp/tokens.ts`, as described in original issue, just hoist a few classes, e.g. 
  - `export { IForeignCodeExtractor } from './extractors/types'`  
  - `export { RegExpForeignCodeExtractor } from './extractors/regexp'`

#### Plan B

- extract  these tokens (and their parent modules) into a new package
- in `packages/transclusions/index.ts` and elsewhere, import these tokens

## How is it done today, and what are the limits of current practice?

>> For reference, at present we're basically just exporting plugins. This ends up making us ship (and use) our own copy of jlsp by referencing stuff in lib/extractors/regexp, which isn't too fun.

## What is new in your approach and why do you think it will be successful?

>> I feel like trying it out for a very string-in-string-out kind API (before we get to rich widgets, etc.) would be an interesting experiment. Will make a separate ticket!

- originally in #76, we had long discussed publishing additional portions of the underlying architecture 

## Who cares? If you are successful, what difference will it make?

- extension authors will easily be able to create simple, potentially single `.ts` file plugins to add new transclusion rules
- Jupyterlab-lsp maintainers might not have to review PRs for every special magic

## What are the risks?

- if shipped as part of the public API of `jupyterlab-lsp`, we'd have to be pretty sure to get it _right_ the first time
- if made as a separate package, we would have to handle the semver range
  - either start it at the current release version (and bump the parent version), 
    - or restart it at `0.1.0` or something
      - this _may_ make it easier to maintain in backport

## ~~How much will it cost?~~

Free as in speech :laughing: .

## How long will it take?

- **Plan A**
  - a few hours of work, get on the next release train 
- **Plan B** 
  - a fair amount of boilerplate `json` management to get connected to `lerna`
  - updating documentation
  - future costs will include publishing additional packages

## What are the mid-term and final “exams” to check for success?

Write and test an example, a la #163.

**Comment by krassowski** [comment]
Very good plan above. I would propose:
- let's aim to implement Plan A for 3.5 (let me know if you can make it this weekend) or 3.6 (probably in April); we can keep the documentation as-is (which includes a note that adding custom magics by extensions should be possible, but uses unstable APIs)
- let's aim with Plan B for 4.0

Also, for transclusions we have three elements:
- `extractors/`: discussed above
- `overrides/`: we need to make sure we export all from `tokens.ts` (e.g. `ICodeOverride`, `IScopedCodeOverride`)
- `transclusions/`: this only imports, nothing to export if I remember correctly

**Comment by bollwyvl** [comment]
@krassowski thanks for the super-quick feedback. Feel free to have a hand at other exports we need on #562, am fine to do this now, and push off even starting Plan B at this point... please update the description (update, add new plans!) if it's clearer in your mind!

**Comment by bollwyvl** [comment]
Good stuff. Let's see how it goes, and we can consider re-opening if (i'm
not kidding myself, _when_) we find issues with the current approach.
