### ISSUE TITLE
How to disable Diagnostics underlining ?

### ISSUE THREAD

**Issue by julioyildo** [krassowski/jupyterlab-lsp#585]
Hello ! 

## How I would like to learn how to do it...
I would like to disable the *Diagnostics* feature and its red and orange underlining... Is there a way to do it? 

## How the project might keep the docs accurate...

Thank you !

**Comment by krassowski** [comment]
Do you wish to disable diagnostics completely (both the underlines and the diagnostics manager) or only the underlines?

A simple approach for now would be to take advantage of regular expression pattern matching intended to provide diagnostics filtering. You could use a catch-all regexp to hide all diagnostics:

```json
{
    "ignoreMessagesPatterns": [".*"]
}
```

![Screenshot from 2021-05-01 17-56-35](https://user-images.githubusercontent.com/5832902/116789442-b9986f00-aaa6-11eb-83dd-816d7f99ac11.png)

This will cause all linter messages to be ignored.

**Comment by bollwyvl** [comment]
So we should probably figure out a way to auto-generate that insight into the docs, so that this returns something:

https://jupyterlab-lsp.readthedocs.io/en/latest/search.html?q=ignoreMessagesPatterns

Back in the day (#89), we mentioned [@adobe/jsonschema2md](https://github.com/adobe/jsonschema2md). Here's a very rough cut of it (looks like I need to revist with myst-nb!) on the [starters docs](https://jupyterstarters.readthedocs.io/en/latest/schema/v2.html). I'll take a look...

**Comment by bollwyvl** [comment]
Sorry to keep hijaaking this for docs stuff. but I gave `sphinx-jsonschema` another go [over here](https://jupyterlite--58.org.readthedocs.build/en/58/schema-v0.html#jupyterlite-configuration) and like how it uses the page. I think we use some inline markdown in our schema, whereas it speaks rst, so maybe I need to figure out how to get that in there.

**Comment by krassowski** [comment]
I believe myst speaks both markdown and rst so it should work (after a minimal modification). And it does look nice!

**Comment by bollwyvl** [comment]
Yeah, sphinx-jsonschema operates down at the docutils layer (buh) so it's a
matter of digging out some stuff. Not my favorite place to be.

It also makes poorly-behaved duplicate html ids, which I need to unwrap.

But if we get it working (here or on lite) it's probably worth there being
a plugin, I guess, unless I can get something to take it as a PR...
Maintaining docs packages is also not my favorite place to be.

**Comment by krassowski** [comment]
> Yeah, sphinx-jsonschema operates down at the docutils layer (buh) 

Oh, I thought it is a bit higher-level. So https://github.com/adobe/jsonschema2md seems better in that case, right?

**Comment by julioyildo** [comment]
Hi, 

First of all, sorry for the delay in response,

I thank you for your feedback. @krassowski The setting you shared with me worked !  Thanks !

In the same way is it possible to disable auto completion? 
This one is a bit slow, we would like to use native version of Jupyterlab with "Tab" or Shift + Tab". 

(I have the impression that the auto-complete of the extension prevents the native version from working).

**Comment by krassowski** [comment]
There was a PR that implemented this #586 so it will be possible in the next release. you may want to use my pyls fork in the meantime to get faster completions

**Comment by krassowski** [comment]
Also to disable linting only for `python-lsp-server`:

```json
{
    "language_servers": {
        "pylsp": {
            "serverSettings": {
                "pylsp.plugins.pycodestyle.enabled": false,
                "pylsp.plugins.pydocstyle.enabled": false,
                "pylsp.plugins.pyflakes.enabled": false,
                "pylsp.plugins.pylint.enabled": false,
                "pylsp.plugins.mccabe.enabled": false,
            }
        }
    }
}

```

or only for `python-language-server`:

```json
{
    "language_servers": {
        "pyls": {
            "serverSettings": {
                "pyls.plugins.pycodestyle.enabled": false,
                "pyls.plugins.pydocstyle.enabled": false,
                "pyls.plugins.pyflakes.enabled": false,
                "pyls.plugins.pylint.enabled": false,
                "pyls.plugins.mccabe.enabled": false,
            }
        }
    }
}
```

**Comment by julioyildo** [comment]
Hi! 

Thank you very much! That works well! :)

**Comment by kwon14** [comment]
Hello. Thank you always for your great work.
I am wondering if there is a way to make only the red underline appear.

Whether there is a separate option in code Diagnostics,
Ask if other options are available.
(I hope there is no yellow underline. Make sure that only the red underline for errors appears.)

thank you.
