### ISSUE TITLE
before starting JupyterLab phase error

### ISSUE THREAD

**Issue by mmrezaie** [krassowski/jupyterlab-lsp#59]
When I run this command:

`node /path/to/anaconda/3/share/jupyter/lab/staging --port 3000 --languageServers servers.yml`

I get this error:

`import {
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
`

The only thing I have done was installing nodejs from conda, and my python version 3.7. I wonder if any of those can be the culprit?

Edit:

`
I also tried site-packages of the python3 version installed by conda but with the same result. I feel my nodejs must be the reasons but I am not sure if I had to do anything for setting it up beforehand!
`

**Comment by mmrezaie** [comment]
I see what I did there. I missed adding this:

node_modules/jsonrpc-ws-proxy/dist/server.js

**Comment by bollwyvl** [comment]
Thanks for trying jupyterlab-lsp. We're hoping to make the setup more streamlined in the next release. Please let us know if you encounter any other issues.

**Comment by mmrezaie** [comment]
Thank you for this interesting project.
