### ISSUE TITLE
JupyterLab RTC

### ISSUE THREAD

**Issue by hbcarlos** [krassowski/jupyterlab-lsp#590]
## Description
Hi, I'm working on JupyterLab-RTC, trying out some extensions to check we are not breaking extensions.
When trying out this extension, I got a warning on the console that I'm not sure if RTC related.

<details><summary>Console log warning</summary>
<pre>
LSP: is_visible failed TypeError: Cannot read property 'model' of undefined
    at se.context_from_active_document (364.8c5f2472dd169e4e4112.js:1)
    at re.get_context (364.8c5f2472dd169e4e4112.js:1)
    at re.is_visible (364.8c5f2472dd169e4e4112.js:1)
    at isVisible (364.8c5f2472dd169e4e4112.js:1)
    at CommandRegistry.isVisible (index.es6.js:347)
    at CommandItem.get [as isVisible] (index.es6.js:4724)
    at matchItems (index.es6.js:4413)
    at Object.search (index.es6.js:4375)
    at CommandPalette.onUpdateRequest (index.es6.js:3873)
    at CommandPalette.Widget.processMessage (index.es6.js:1341)
is_visible @ 364.8c5f2472dd169e4e4112.js:1
</pre>
</details>

## Reproduce
Install JupyterLab from [here](https://github.com/jupyter-rtc/jupyterlab). And install the extension using the conda package.
This is a federated extension, so you'll see some warnings on the bowser's console log indicating that the extension uses different dependencies from the ones it was built on.

## Context
This is the [issue](https://github.com/jupyter-rtc/jupyterlab/issues/60) where we are tracking the extensions on RTC

**Comment by krassowski** [comment]
This looks innocent to me. I was not able to reproduce it after installing RTC locally. There is an issue with the cursor after completion though:

![completion-issue](https://user-images.githubusercontent.com/5832902/117180455-190abd80-adcc-11eb-8ca8-9a29b10f7e3b.gif)

**Comment by krassowski** [comment]
I see you track it in https://github.com/jupyter-rtc/jupyterlab/issues/64.

**Comment by hbcarlos** [comment]
Hey, thanks for checking!

Yeah, we have the issue tracked.
Actually, some help on this issue would be really appreciated (we don't have much experience in the completer 😊)

**Comment by krassowski** [comment]
I tested in locally and other things seem to work. Ideally you could just fork this repo and change the lab version to be installed from the RTC fork rather than from conda-foge and see if the CI passes (this would involve modifying https://github.com/krassowski/jupyterlab-lsp/tree/master/requirements I guess, but may also need an extra build step). Then you could make a PR here (that we will not merge) and after any substantial update of the RTC fork we can re-trigger the CI to make sure all is fine.

**Comment by krassowski** [comment]
> Actually, some help on this issue would be really appreciated (we don't have much experience in the completer blush)

I will take a look.

**Comment by hbcarlos** [comment]
Nice, I'll open a PR. Thanks!
