### ISSUE TITLE
Release jupyter-lsp

### ISSUE THREAD

**Issue by mlucool** [krassowski/jupyterlab-lsp#617]
Hi,

https://github.com/krassowski/jupyterlab-lsp/pull/587 adds pyright (as announced in [jupyterlab-lsp v3.7.0](https://github.com/krassowski/jupyterlab-lsp/releases/tag/v3.7.0)), but my understanding is that the pyright detection code is in `jupyter-lsp`, which has not been released to pypi since it was merged. Can you please release a new version?

**Comment by krassowski** [comment]
Sorry I missed it. Should be up within an hour or so.

**Comment by krassowski** [comment]
jupyter-lsp 1.3 is up. Thank you for the report!
