### ISSUE TITLE
"Server Extension Missing" unless manually enabled in Jupyter Server

### ISSUE THREAD

**Issue by tomweingarten** [krassowski/jupyterlab-lsp#620]
After installing jupyterlab and jupyterlab-lsp via pip, I got the "Server Extension Missing" error. I followed all the advice there, and tried a clean install with no luck. Eventually I figured out that the only way to make it work was to run this command:

`jupyter server extension enable --user --py jupyter_lsp`

**Comment by krassowski** [comment]
Thanks for opening this issue! I don't know why it sometimes does not get enabled, I think it has to do with a specific installation/environment and not with the extension itself. However, I agree that we could do more to help users who bump into this problem. For example we could include the above command as a last-resort action in the pop-up window with advice that we have (something like "If the server extension is installed but not enabled and all other suggestions listed above failed try the following:").

The error message is defined in https://github.com/krassowski/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/src/errors.tsx - would you like to send a PR improving it?

**Comment by devstein** [comment]
Hi @krassowski @tomweingarten For what it's worth, I ran into the same issue and the solution was to update the user settings configuration per the README (I'm using `pylsp`). The default configuration didn't work.
```json
{
  "language_servers": {
    "pylsp": {
      "serverSettings": {
        "pyls.plugins.pydocstyle.enabled": true,
        "pyls.plugins.pyflakes.enabled": false,
        "pyls.plugins.flake8.enabled": true
      }
    },
    "r-languageserver": {
      "serverSettings": {
        "r.lsp.debug": false,
        "r.lsp.diagnostics": false
      }
    }
  }
}
```
Hope this helps anyone else who stumbles on this issue!
