### ISSUE TITLE
jupyter-lsp-python does not work with python 3.9

### ISSUE THREAD

**Issue by antonkulaga** [krassowski/jupyterlab-lsp#626]
I tried to install it to one of my projects ( https://github.com/antonkulaga/lab-automation ) via micromamba and for some reasons it does not install to python 3.9

**Comment by krassowski** [comment]
Thank you for opening this issue. In general the extension works fine with Python 3.9. Is there an error during installation that you could share? Could you also please provide the details of your environment, including operating system name and version, version of conda, list of installed packages (conda list/pip list) and anything else you think may be relevant?

**Comment by krassowski** [comment]
@antonkulaga I would very much like to help you but I need more information. I will close this one for now, as I am confident that the extension works fine with Python 3.9. If you can provide the details on what problems you have with the installation I will be happy to investigate.
