### ISSUE TITLE
Potential hover cache malfunction spam

### ISSUE THREAD

**Issue by jabbera** [krassowski/jupyterlab-lsp#628]
## Description

Unsure if you would consider this a bug but my chrome console is being spammed with the following:

![image](https://user-images.githubusercontent.com/301208/122220339-3bd5ca80-ce7e-11eb-815d-780b2580bc38.png)

## Reproduce

Hosting via JupyterHub
Happens with pyright and jedi at least.
lsp 3.7.0

## Expected behavior

Don't spam the console.

## Context

- Operating System and version: jupyter docker-stacks image
- Browser and version: Chrome 91
- JupyterLab version: 3.0.16

<details><summary>Required: installed server extensions</summary>
<pre>
Config option `kernel_spec_manager_class` not recognized by `ListServerExtensionsApp`.
Config dir: /home/jovyan/.jupyter

/opt/conda/lib/python3.9/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
/opt/conda/lib/python3.9/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
Config dir: /opt/conda/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.3.0 OK
    jupyter_server_proxy enabled
    - Validating jupyter_server_proxy...
      jupyter_server_proxy  OK
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage  OK
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.16 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.30.1 OK
    jupyterlab_spellchecker enabled
    - Validating jupyterlab_spellchecker...
      jupyterlab_spellchecker 0.6.0 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    nbdime enabled
    - Validating nbdime...
      nbdime 3.1.0 OK
    retrolab enabled
    - Validating retrolab...
      retrolab 0.2.2 OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2021-06-16 12:42:45.070 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.0.16
/opt/conda/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.0 enabled OK
        jupyterlab-plotly v5.0.0-rc.1 enabled OK
        ipysheet v0.5.0 enabled OK (python, ipysheet)
        jupyterlab-execute-time v2.0.4 enabled OK (python, jupyterlab_execute_time)
        jupyterlab-system-monitor v0.8.0 enabled OK (python, jupyterlab-system-monitor)
        jupyterlab-topbar-extension v0.6.1 enabled OK (python, jupyterlab-topbar)
        jupyter-matplotlib v0.9.0 enabled OK
        @jupyterlab/git v0.30.1 enabled OK (python, jupyterlab-git)
        @jupyterlab/server-proxy v3.0.2 enabled OK
        @jupyter-server/resource-usage v0.5.0 enabled OK (python, jupyter-resource-usage)
        @retrolab/lab-extension v0.2.2 enabled OK
        @ijmbarr/jupyterlab_spellchecker v0.6.0 enabled OK (python, jupyterlab-spellchecker)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @krassowski/jupyterlab-lsp v3.7.0 enabled OK (python, jupyterlab-lsp)
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
(base) jovyan@jupyter-mbarry:~$ jupyter troubleshoot

InvalidVersionSpec: Invalid version '2ipywidgets>=7.5.0': invalid character(s)

$PATH:
        /opt/conda/bin
        /opt/conda/condabin
        /opt/dotnet/tools
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /home/jovyan/.dotnet/tools
        /opt/mssql-tools/bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python39.zip
        /opt/conda/lib/python3.9
        /opt/conda/lib/python3.9/lib-dynload
        /opt/conda/lib/python3.9/site-packages

sys.executable:
        /opt/conda/bin/python

sys.version:
        3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
        [GCC 9.3.0]

platform.platform():
        Linux-5.4.0-1046-azure-x86_64-with-glibc2.31

which -a jupyter:
        /opt/conda/bin/jupyter
        /opt/conda/bin/jupyter

pip list:
        Package                             Version
        ----------------------------------- -------------------
        aiohttp                             3.7.4.post0
        alembic                             1.6.5
        ansiwrap                            0.8.4
        anyio                               3.1.0
        appdirs                             1.4.4
        argon2-cffi                         20.1.0
        astroid                             2.5.8
        async-generator                     1.10
        async-timeout                       3.0.1
        attrs                               21.2.0
        autopep8                            1.5.7
        azure-core                          1.15.0
        azure-identity                      1.6.0
        Babel                               2.9.1
        backcall                            0.2.0
        backports.functools-lru-cache       1.6.4
        black                               21.5b2
        bleach                              3.3.0
        blinker                             1.4
        brotlipy                            0.7.0
        certifi                             2021.5.30
        certipy                             0.1.3
        cffi                                1.14.5
        chardet                             4.0.0
        click                               8.0.1
        colorama                            0.4.4
        conda                               4.10.1
        conda-package-handling              1.7.3
        cryptography                        3.4.7
        cycler                              0.10.0
        data-catalog-gmo                    0.1a51
        debugpy                             1.3.0
        decorator                           5.0.9
        defusedxml                          0.7.1
        deltalake                           0.5.0
        docstring-to-markdown               0.9
        entrypoints                         0.3
        flake8                              3.9.2
        gitdb                               4.0.7
        GitPython                           3.1.17
        greenlet                            1.1.0
        holdings-gmo                        0.1a73
        idna                                2.10
        importlib-metadata                  4.5.0
        ipykernel                           5.5.5
        ipympl                              0.7.0
        ipynbname                           2021.3.2
        ipysheet                            0.5.0
        ipython                             7.24.1
        ipython-genutils                    0.2.0
        ipywidgets                          7.6.3
        isort                               5.8.0
        jedi                                0.18.0
        jedi-language-server                0.32.0
        Jinja2                              3.0.1
        json5                               0.9.5
        jsonschema                          3.2.0
        jupyter-client                      6.1.12
        jupyter-core                        4.7.1
        jupyter-lsp                         1.3.0
        jupyter-resource-usage              0.5.1
        jupyter-server                      1.8.0
        jupyter-server-mathjax              0.2.3
        jupyter-server-proxy                3.0.2
        jupyter-telemetry                   0.1.0
        jupyter-vscode-proxy                0.1
        jupyterhub                          1.4.1
        jupyterlab                          3.0.16
        jupyterlab-execute-time             2.0.4
        jupyterlab-git                      0.30.1
        jupyterlab-lsp                      3.7.0
        jupyterlab-pygments                 0.1.2
        jupyterlab-server                   2.6.0
        jupyterlab-spellchecker             0.6.0
        jupyterlab-system-monitor           0.8.0
        jupyterlab-topbar                   0.6.1
        jupyterlab-widgets                  1.0.0
        kiwisolver                          1.3.1
        lazy-object-proxy                   1.6.0
        Mako                                1.1.4
        mamba                               0.13.0
        MarkupSafe                          2.0.1
        matlab-production-server-client-gmo 1.1.21
        matplotlib                          3.4.2
        matplotlib-inline                   0.1.2
        mccabe                              0.6.1
        mistune                             0.8.4
        mplcursors                          0.4
        msal                                1.12.0
        msal-extensions                     0.3.0
        multidict                           5.1.0
        mypy-extensions                     0.4.3
        nb-conda-kernels                    2.3.1
        nbclassic                           0.3.1
        nbclient                            0.5.3
        nbconvert                           6.0.7
        nbdime                              3.1.0
        nbformat                            5.1.3
        nest-asyncio                        1.5.1
        notebook                            6.4.0
        nteract-on-jupyter                  2.1.3
        numpy                               1.20.3
        oauthlib                            3.1.1
        olefile                             0.46
        packaging                           20.9
        pamela                              1.0.0
        pandas                              1.2.4
        pandocfilters                       1.4.2
        papermill                           2.3.3
        parso                               0.8.2
        pathspec                            0.8.1
        pexpect                             4.8.0
        pickleshare                         0.7.5
        Pillow                              8.2.0
        pip                                 21.1.2
        plotly                              5.0.0rc1
        pluggy                              0.13.1
        portalocker                         1.7.1
        prometheus-client                   0.11.0
        prompt-toolkit                      3.0.18
        protobuf                            3.17.3
        psutil                              5.8.0
        psycopg2                            2.8.6
        ptyprocess                          0.7.0
        pyarrow                             4.0.1
        pycodestyle                         2.7.0
        pycosat                             0.6.3
        pycparser                           2.20
        pycurl                              7.43.0.6
        pydantic                            1.8.2
        pydocstyle                          6.1.1
        pyflakes                            2.3.1
        pygls                               0.10.3
        Pygments                            2.9.0
        PyJWT                               2.1.0
        pylint                              2.7.2
        pymssql                             2.1.5
        pyodbc                              4.0.30
        pyOpenSSL                           20.0.1
        pyparsing                           2.4.7
        pyrsistent                          0.17.3
        PySocks                             1.7.1
        python-dateutil                     2.8.1
        python-dotenv                       0.17.1
        python-editor                       1.0.4
        python-json-logger                  2.0.1
        python-lsp-jsonrpc                  1.0.0
        python-lsp-server                   1.0.1
        pytz                                2021.1
        PyYAML                              5.4.1
        pyzmq                               22.1.0
        regex                               2021.4.4
        requests                            2.25.1
        retrolab                            0.2.2
        rope                                0.19.0
        ruamel-yaml-conda                   0.15.80
        ruamel.yaml                         0.17.9
        ruamel.yaml.clib                    0.2.2
        Send2Trash                          1.5.0
        setuptools                          49.6.0.post20210108
        simpervisor                         0.4
        six                                 1.16.0
        smmap                               3.0.5
        sniffio                             1.2.0
        snowballstemmer                     2.1.0
        SQLAlchemy                          1.4.18
        tenacity                            7.0.0
        terminado                           0.10.1
        testpath                            0.5.0
        textwrap3                           0.9.2
        toml                                0.10.2
        tornado                             6.1
        tqdm                                4.61.1
        traitlets                           5.0.5
        typed-ast                           1.4.3
        typeguard                           2.12.1
        typing-extensions                   3.10.0.0
        ujson                               4.0.2
        urllib3                             1.26.5
        wcwidth                             0.2.5
        webencodings                        0.5.1
        websocket-client                    0.57.0
        wheel                               0.36.2
        widgetsnbextension                  3.5.1
        wrapt                               1.12.1
        yapf                                0.31.0
        yarl                                1.6.3
        zipp                                3.4.1

conda list:
        # packages in environment at /opt/conda:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       1_gnu    conda-forge
        aiohttp                   3.7.4.post0      py39h3811e60_0    conda-forge
        alembic                   1.6.5              pyhd8ed1ab_0    conda-forge
        ansiwrap                  0.8.4                      py_0    conda-forge
        anyio                     3.1.0            py39hf3d152e_0    conda-forge
        appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
        argon2-cffi               20.1.0           py39h3811e60_2    conda-forge
        astroid                   2.5.8            py39hf3d152e_0    conda-forge
        async-timeout             3.0.1                   py_1000    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
        autopep8                  1.5.7              pyhd8ed1ab_0    conda-forge
        azure-core                1.15.0                   pypi_0    pypi
        azure-identity            1.6.0                    pypi_0    pypi
        babel                     2.9.1              pyh44b312d_0    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                        py_2    conda-forge
        backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
        black                     21.5b2             pyhd8ed1ab_0    conda-forge
        bleach                    3.3.0              pyh44b312d_0    conda-forge
        blinker                   1.4                        py_1    conda-forge
        brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        c-ares                    1.17.1               h7f98852_1    conda-forge
        ca-certificates           2021.5.30            ha878542_0    conda-forge
        certifi                   2021.5.30        py39hf3d152e_0    conda-forge
        certipy                   0.1.3                      py_0    conda-forge
        cffi                      1.14.5           py39he32792d_0    conda-forge
        chardet                   4.0.0            py39hf3d152e_1    conda-forge
        click                     8.0.1            py39hf3d152e_0    conda-forge
        colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
        conda                     4.10.1           py39hf3d152e_0    conda-forge
        conda-package-handling    1.7.3            py39h3811e60_0    conda-forge
        configurable-http-proxy   4.4.0           node15_he6ea98c_0    conda-forge
        cryptography              3.4.7            py39hbca0aa6_0    conda-forge
        cycler                    0.10.0                     py_2    conda-forge
        data-catalog-gmo          0.1a51                   pypi_0    pypi
        dataclasses               0.8                pyhc8e2a94_1    conda-forge
        debugpy                   1.3.0            py39he80948d_0    conda-forge
        decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
        defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
        deltalake                 0.5.0                    pypi_0    pypi
        docstring-to-markdown     0.9                pyhd8ed1ab_0    conda-forge
        entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
        flake8                    3.9.2              pyhd8ed1ab_0    conda-forge
        freetds                   1.1.15               h94af77a_0    conda-forge
        freetype                  2.10.4               h0708190_1    conda-forge
        gitdb                     4.0.7              pyhd8ed1ab_0    conda-forge
        gitpython                 3.1.17             pyhd8ed1ab_0    conda-forge
        greenlet                  1.1.0            py39he80948d_0    conda-forge
        holdings-gmo              0.1a73                   pypi_0    pypi
        icu                       68.1                 h58526e2_0    conda-forge
        idna                      2.10               pyh9f0ad1d_0    conda-forge
        importlib-metadata        4.5.0            py39hf3d152e_0    conda-forge
        ipykernel                 5.5.5            py39hef51801_0    conda-forge
        ipympl                    0.7.0              pyhd8ed1ab_0    conda-forge
        ipynbname                 2021.3.2           pyhd8ed1ab_0    conda-forge
        ipysheet                  0.5.0                    pypi_0    pypi
        ipython                   7.24.1           py39hef51801_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
        isort                     5.8.0              pyhd8ed1ab_0    conda-forge
        jbig                      2.1               h7f98852_2003    conda-forge
        jedi                      0.18.0           py39hf3d152e_2    conda-forge
        jedi-language-server      0.32.0             pyhd8ed1ab_0    conda-forge
        jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
        jpeg                      9d                   h36c2ea0_0    conda-forge
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
        jupyter-lsp               1.3.0              pyhd8ed1ab_0    conda-forge
        jupyter-resource-usage    0.5.1              pyhd8ed1ab_0    conda-forge
        jupyter-server-mathjax    0.2.3              pyhd8ed1ab_0    conda-forge
        jupyter-server-proxy      3.0.2              pyhd8ed1ab_0    conda-forge
        jupyter-vscode-proxy      0.1                      pypi_0    pypi
        jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
        jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
        jupyter_server            1.8.0              pyhd8ed1ab_0    conda-forge
        jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
        jupyterhub                1.4.1            py39hf3d152e_0    conda-forge
        jupyterhub-base           1.4.1            py39hf3d152e_0    conda-forge
        jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
        jupyterlab-git            0.30.1             pyhd8ed1ab_0    conda-forge
        jupyterlab-lsp            3.7.0              pyhd8ed1ab_0    conda-forge
        jupyterlab-spellchecker   0.6.0              pyhd8ed1ab_0    conda-forge
        jupyterlab-system-monitor 0.8.0              pyhd8ed1ab_1    conda-forge
        jupyterlab-topbar         0.6.1              pyhd8ed1ab_2    conda-forge
        jupyterlab_execute_time   2.0.4              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
        jupyterlab_server         2.6.0              pyhd8ed1ab_0    conda-forge
        jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
        kiwisolver                1.3.1            py39h1a9c180_1    conda-forge
        krb5                      1.19.1               hcc1bbae_0    conda-forge
        lazy-object-proxy         1.6.0            py39h3811e60_0    conda-forge
        lcms2                     2.12                 hddcbb42_0    conda-forge
        ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
        lerc                      2.2.1                h9c3ff4c_0    conda-forge
        libarchive                3.5.1                hccf745f_2    conda-forge
        libblas                   3.9.0                9_openblas    conda-forge
        libcblas                  3.9.0                9_openblas    conda-forge
        libcurl                   7.77.0               h2574ce0_0    conda-forge
        libdeflate                1.7                  h7f98852_5    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libffi                    3.3                  h58526e2_2    conda-forge
        libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
        libgfortran-ng            9.3.0               hff62375_19    conda-forge
        libgfortran5              9.3.0               hff62375_19    conda-forge
        libgomp                   9.3.0               h2828fa1_19    conda-forge
        libiconv                  1.16                 h516909a_0    conda-forge
        liblapack                 3.9.0                9_openblas    conda-forge
        libnghttp2                1.43.0               h812cca2_0    conda-forge
        libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
        libpng                    1.6.37               h21135ba_2    conda-forge
        libpq                     13.3                 hd57d9b9_0    conda-forge
        libsodium                 1.0.18               h36c2ea0_1    conda-forge
        libsolv                   0.7.18               h780b84a_0    conda-forge
        libssh2                   1.9.0                ha56f1ee_6    conda-forge
        libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
        libtiff                   4.3.0                hf544144_1    conda-forge
        libuuid                   2.32.1            h7f98852_1000    conda-forge
        libuv                     1.41.0               h7f98852_0    conda-forge
        libwebp-base              1.2.0                h7f98852_2    conda-forge
        libxml2                   2.9.12               h72842e0_0    conda-forge
        lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
        lzo                       2.10              h516909a_1000    conda-forge
        mako                      1.1.4              pyh44b312d_0    conda-forge
        mamba                     0.13.0           py39h951de11_0    conda-forge
        markupsafe                2.0.1            py39h3811e60_0    conda-forge
        matlab-production-server-client-gmo 1.1.21                   pypi_0    pypi
        matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
        matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
        mccabe                    0.6.1                      py_1    conda-forge
        mistune                   0.8.4           py39h3811e60_1003    conda-forge
        mplcursors                0.4                pyhd8ed1ab_0    conda-forge
        msal                      1.12.0                   pypi_0    pypi
        msal-extensions           0.3.0                    pypi_0    pypi
        multidict                 5.1.0            py39h3811e60_1    conda-forge
        mypy_extensions           0.4.3            py39hf3d152e_3    conda-forge
        nb_conda_kernels          2.3.1            py39hf3d152e_0    conda-forge
        nbclassic                 0.3.1              pyhd8ed1ab_1    conda-forge
        nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
        nbconvert                 6.0.7            py39hf3d152e_3    conda-forge
        nbdime                    3.1.0              pyhd8ed1ab_0    conda-forge
        nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
        ncurses                   6.2                  h58526e2_4    conda-forge
        nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
        nodejs                    15.14.0              h92b4a50_0    conda-forge
        notebook                  6.4.0              pyha770c72_0    conda-forge
        nteract_on_jupyter        2.1.3                      py_0    conda-forge
        numpy                     1.20.3           py39hdbf815f_1    conda-forge
        oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
        olefile                   0.46               pyh9f0ad1d_1    conda-forge
        openjpeg                  2.4.0                hb52868f_1    conda-forge
        openssl                   1.1.1k               h7f98852_0    conda-forge
        packaging                 20.9               pyh44b312d_0    conda-forge
        pamela                    1.0.0                      py_0    conda-forge
        pandas                    1.2.4                    pypi_0    pypi
        pandoc                    2.14.0.1             h7f98852_0    conda-forge
        pandocfilters             1.4.2                      py_1    conda-forge
        papermill                 2.3.3              pyhd8ed1ab_0    conda-forge
        parso                     0.8.2              pyhd8ed1ab_0    conda-forge
        pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
        pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pillow                    8.2.0            py39hf95b381_1    conda-forge
        pip                       21.1.2             pyhd8ed1ab_0    conda-forge
        plotly                    5.0.0rc1                 pypi_0    pypi
        pluggy                    0.13.1           py39hf3d152e_4    conda-forge
        portalocker               1.7.1                    pypi_0    pypi
        prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
        prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
        protobuf                  3.17.3                   pypi_0    pypi
        psutil                    5.8.0            py39h3811e60_1    conda-forge
        psycopg2                  2.8.6            py39h3811e60_3    conda-forge
        ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
        pyarrow                   4.0.1                    pypi_0    pypi
        pycodestyle               2.7.0              pyhd8ed1ab_0    conda-forge
        pycosat                   0.6.3           py39h3811e60_1006    conda-forge
        pycparser                 2.20               pyh9f0ad1d_2    conda-forge
        pycurl                    7.43.0.6         py39h72e3413_1    conda-forge
        pydantic                  1.8.2            py39h3811e60_0    conda-forge
        pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
        pyflakes                  2.3.1              pyhd8ed1ab_0    conda-forge
        pygls                     0.10.3             pyhd8ed1ab_1    conda-forge
        pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
        pyjwt                     2.1.0              pyhd8ed1ab_0    conda-forge
        pylint                    2.7.2            py39hf3d152e_0    conda-forge
        pymssql                   2.1.5            py39he80948d_2    conda-forge
        pyodbc                    4.0.30           py39he80948d_1    conda-forge
        pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
        pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
        pyrsistent                0.17.3           py39h3811e60_2    conda-forge
        pysocks                   1.7.1            py39hf3d152e_3    conda-forge
        python                    3.9.4           hffdb5ce_0_cpython    conda-forge
        python-dateutil           2.8.1                      py_0    conda-forge
        python-dotenv             0.17.1                   pypi_0    pypi
        python-editor             1.0.4                      py_0    conda-forge
        python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
        python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
        python-lsp-server         1.0.1              pyhd8ed1ab_0    conda-forge
        python_abi                3.9                      1_cp39    conda-forge
        pytz                      2021.1             pyhd8ed1ab_0    conda-forge
        pyyaml                    5.4.1            py39h3811e60_0    conda-forge
        pyzmq                     22.1.0           py39h37b5a0c_0    conda-forge
        readline                  8.1                  h46c0cb4_0    conda-forge
        regex                     2021.4.4         py39h3811e60_0    conda-forge
        reproc                    14.2.1               h36c2ea0_0    conda-forge
        reproc-cpp                14.2.1               h58526e2_0    conda-forge
        requests                  2.25.1             pyhd3deb0d_0    conda-forge
        retrolab                  0.2.2              pyhd8ed1ab_0    conda-forge
        rope                      0.19.0             pyhd8ed1ab_0    conda-forge
        ruamel.yaml               0.17.9           py39h3811e60_0    conda-forge
        ruamel.yaml.clib          0.2.2            py39h3811e60_2    conda-forge
        ruamel_yaml               0.15.80         py39h3811e60_1004    conda-forge
        send2trash                1.5.0                      py_0    conda-forge
        setuptools                49.6.0           py39hf3d152e_3    conda-forge
        simpervisor               0.4                pyhd8ed1ab_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        smmap                     3.0.5              pyh44b312d_0    conda-forge
        sniffio                   1.2.0            py39hf3d152e_1    conda-forge
        snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
        sqlalchemy                1.4.18           py39h3811e60_0    conda-forge
        sqlite                    3.35.5               h74cdb3f_0    conda-forge
        tenacity                  7.0.0              pyhd8ed1ab_0    conda-forge
        terminado                 0.10.1           py39hf3d152e_0    conda-forge
        testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
        textwrap3                 0.9.2                      py_0    conda-forge
        tk                        8.6.10               h21135ba_1    conda-forge
        toml                      0.10.2             pyhd8ed1ab_0    conda-forge
        tornado                   6.1              py39h3811e60_1    conda-forge
        tqdm                      4.61.1             pyhd8ed1ab_0    conda-forge
        traitlets                 5.0.5                      py_0    conda-forge
        typed-ast                 1.4.3            py39h3811e60_0    conda-forge
        typeguard                 2.12.1             pyhd8ed1ab_0    conda-forge
        typing-extensions         3.10.0.0             hd8ed1ab_0    conda-forge
        typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
        tzdata                    2021a                he74cb21_0    conda-forge
        ujson                     4.0.2            py39he80948d_0    conda-forge
        unixodbc                  2.3.9                hb166930_0    conda-forge
        urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
        wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        websocket-client          0.57.0           py39hf3d152e_4    conda-forge
        wheel                     0.36.2             pyhd3deb0d_0    conda-forge
        widgetsnbextension        3.5.1            py39hf3d152e_4    conda-forge
        wrapt                     1.12.1           py39h3811e60_3    conda-forge
        xeus                      1.0.3                h7d0c39e_1    conda-forge
        xeus-python               0.12.5           py39h1aaad98_1    conda-forge
        xz                        5.2.5                h516909a_1    conda-forge
        yaml                      0.2.5                h516909a_0    conda-forge
        yapf                      0.31.0             pyhd8ed1ab_0    conda-forge
        yarl                      1.6.3            py39h3811e60_1    conda-forge
        zeromq                    4.3.4                h9c3ff4c_0    conda-forge
        zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
        zlib                      1.2.11            h516909a_1010    conda-forge
        zstd                      1.5.0                ha95c52a_0    conda-forge
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
364.560fb07260ff05330d4d.js:1 LSP.WidgetAdapter.LSP Hover tooltip: Potential hover cache malfunction:  {ch: 11, line: 7} (2) [{…}, {…}]
restore_from_cache @ 364.560fb07260ff05330d4d.js:1
_updateUnderlineAndTooltip @ 364.560fb07260ff05330d4d.js:1
Zt.updateUnderlineAndTooltip @ 364.560fb07260ff05330d4d.js:1
(anonymous) @ 364.560fb07260ff05330d4d.js:1

</pre>
</details>

**Comment by krassowski** [comment]
Thanks foro opening this issue. You are right, this message is of little use most of the time and should not be a warning but a `log` or `debug` message (which are by default not shown by our console wrapper). We would need to change this line:

https://github.com/krassowski/jupyterlab-lsp/blob/22bf7b3757207182e3a671b2bb8fef9e302417a3/packages/jupyterlab-lsp/src/features/hover.ts#L119-L123

Would you like to send a PR?

**Comment by krassowski** [comment]
Wait, actually maybe we can fix this... The issue seems to be that we do not de-duplicate responses in:

https://github.com/krassowski/jupyterlab-lsp/blob/22bf7b3757207182e3a671b2bb8fef9e302417a3/packages/jupyterlab-lsp/src/features/hover.ts#L50-L55

I will have a look. But I am happy to switch it to a log message anyways.
