### ISSUE TITLE
LSP servers Missing: 1 r

### ISSUE THREAD

**Issue by amida47** [krassowski/jupyterlab-lsp#631]
## Description
this my problem
![image](https://user-images.githubusercontent.com/49212088/122578877-38903980-d04c-11eb-8184-fa31ce405ad5.png)

I first installed jupyterlab-lsp
pip install 'jupyterlab>=3.0.0,<4.0.0a0' jupyterlab-lsp
then I ran the following command in both RGUI and in jupyterlab
install.packages("languageserver")
this the output I get
Installing package into ‘C:/Users/../Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/languageserver_0.3.10.zip'
Content type 'application/zip' length 897118 bytes (876 KB)
downloaded 876 KB

package ‘languageserver’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\...\AppData\Local\Temp\RtmpusPWJf\downloaded_packages

I restarted jupyterlab serval times and the problem persist 

## Reproduce

launch jupyter lab
start a R notebook

## Context

- Operating System and version: win 10 
- Browser and version: Google chrome 
- JupyterLab version: 3.0.14

<details><summary>Required: installed server extensions</summary>
<pre>
jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.3.0 ok
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.14 ok
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  ok
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.0.14
c:\users\.....\appdata\local\programs\python\python39\share\jupyter\labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)
        @krassowski/jupyterlab-lsp v3.7.0 enabled ok (python, jupyterlab-lsp)

</pre>
</details>

<details><summary>output from your browser JavaScript console</summary>
<pre>

remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.7 of shared singleton module @jupyterlab/apputils (required ^3.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.7 of shared singleton module @jupyterlab/translation (required ^3.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.6 of shared singleton module @jupyterlab/ui-components (required ^3.0.7)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.7 of shared singleton module @jupyterlab/statusbar (required ^3.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.8 of shared singleton module @jupyterlab/logconsole (required ^3.0.10)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 6.0.7 of shared singleton module @jupyterlab/services (required ^6.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 5.0.5 of shared singleton module @jupyterlab/coreutils (required ^5.0.6)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.8 of shared singleton module @jupyterlab/tooltip (required ^3.0.10)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.7 of shared singleton module @jupyterlab/completer (required ^3.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.9 of shared singleton module @jupyterlab/fileeditor (required ^3.0.11)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.9 of shared singleton module @jupyterlab/application (required ^3.0.11)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.5 of shared singleton module @jupyterlab/settingregistry (required ^3.0.6)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.7 of shared singleton module @jupyterlab/codemirror (required ^3.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.7 of shared singleton module @jupyterlab/codeeditor (required ^3.0.9)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.9 of shared singleton module @jupyterlab/notebook (required ^3.0.11)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.9 of shared singleton module @jupyterlab/docmanager (required ^3.0.11)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
remoteEntry.060055c1e09a4d5d42e7.js:1 Unsatisfied version 3.0.8 of shared singleton module @jupyterlab/rendermime (required ^3.0.10)
u @ remoteEntry.060055c1e09a4d5d42e7.js:1
jlab_core.64abc115a1efeec58694.js?v=64abc115a1efeec58694:2 Disabling terminals plugin because they are not available on the server
k @ jlab_core.64abc115a1efeec58694.js?v=64abc115a1efeec58694:2
364.560fb07260ff05330d4d.js:1 @krassowski/jupyterlab-lsp:signature settings schema could not be found and was not loaded
He @ 364.560fb07260ff05330d4d.js:1
LSP.WidgetAdapter: No language server installed for language r
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
Hi, thanks for the detailed report and sorry it is not working! What happens if you execute:

```bash
Rscript -e "cat(system.file(package='languageserver'))"
```

from command line? If it is properly installed we should get a path to the library.

**Comment by amida47** [comment]
it did exactly what you expected
![image](https://user-images.githubusercontent.com/49212088/122649825-b83f0680-d127-11eb-89fc-2ad2bfcae5fa.png)

**Comment by krassowski** [comment]
But could you please run it from command line, not from the R console? I suspect that you might be missing the `Rscript`, or it might not be in path. We are using `Rscript` exactly as shown above to confirm whether this language server is installed.

**Comment by krassowski** [comment]
From a glance it seems that `Rscript` should  be available on Windows. https://stackoverflow.com/questions/3506007/running-r-code-from-command-line-windows; It most certainly is available when R is installed with conda, but I expect that other various R distributions might not embed it in path.

**Comment by amida47** [comment]
You're right 
![image](https://user-images.githubusercontent.com/49212088/122650249-afe7cb00-d129-11eb-9e44-3d930156dc9e.png)

**Comment by amida47** [comment]
I am not using Anaconda by the way

**Comment by amida47** [comment]
When I go to where R is installed it works
![image](https://user-images.githubusercontent.com/49212088/122650391-7ebbca80-d12a-11eb-8503-e3228af4ca5f.png)

**Comment by amida47** [comment]
I added the path to where R is installed (C:\Program Files\R\R-4.0.5\bin) to the path variable, now everything is working fine.
thanks for the help.
![image](https://user-images.githubusercontent.com/49212088/122650581-b0816100-d12b-11eb-98b4-d76190323c45.png)

**Comment by krassowski** [comment]
That's great! I will leave a link to instructions on adding it to path on Windows I just googled: https://stackoverflow.com/a/42567862/6646912

I wonder if we can do any better. Maybe we could:
- show suggestion saying "is not installed or RScript not in the path",
- add information on requirement of RScript being in the path to the documentation of auto-detected language servers

I also wonder, where you just running `R` without having it in the path previously? Does it mean that some installers on Windows only link `R` executable but not `RScript`, or was it that neither was available?

**Comment by amida47** [comment]
Yes, I just running R without having it in the path previously, for me to install R I just downloaded the installer from https://cran.r-project.org/bin/windows/base/, and was enough to run code in Jupyter, I don't run code in command line that's why I never noticed that R was not in the path variable.

**Comment by krassowski** [comment]
Indeed, the default R installer for Windows does not add RScript to PATH (https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Rcmd-is-not-found-in-my-PATH_0021) which is... strange? However, it seems that Microsoft's R Open distribution of R (https://mran.microsoft.com/documents/rro/installation) does properly set the PATH.

Design idea: we could have a  little help icon (?) in the status bar popover "missing" section which could show a dialog with extra troubleshooting information for specific language server (in this case informing that either R is not installed or not in PATH). We may need to allow for dynamic generation of these messages so that it changes to "R detected but r-languageserver not installed" when R is in PATH but language server is not.
