### ISSUE TITLE
Language server warnings

### ISSUE THREAD

**Issue by karlaspuldaro** [krassowski/jupyterlab-lsp#640]
## Description
After installing the 3.8 version along with jupyter-lsp 1.4.0, new server warnings are logged when running jupyterlab in the format:
```
Failed to validate commands from language server spec finder `x-language-server`: [<ValidationError: "None is not of type 'string'">]
```
for some of  the language server specs [defined here](https://github.com/krassowski/jupyterlab-lsp/tree/master/python_packages/jupyter_lsp/jupyter_lsp/specs) (See list below)
Command Line Output:
```
[W 2021-07-06 12:28:01.705 ServerApp] Failed to validate commands from language server spec finder `bash-language-server`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.705 ServerApp] Failed to validate commands from language server spec finder `dockerfile-language-server-nodejs`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.706 ServerApp] Failed to validate commands from language server spec finder `javascript-typescript-langserver`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.708 ServerApp] Failed to validate commands from language server spec finder `pyright`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.710 ServerApp] Failed to validate commands from language server spec finder `sql-language-server`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.712 ServerApp] Failed to validate commands from language server spec finder `unified-language-server`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.712 ServerApp] Failed to validate commands from language server spec finder `vscode-css-languageserver-bin`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.713 ServerApp] Failed to validate commands from language server spec finder `vscode-html-languageserver-bin`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.713 ServerApp] Failed to validate commands from language server spec finder `vscode-json-languageserver-bin`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.714 ServerApp] Failed to validate commands from language server spec finder `yaml-language-server`:
    [<ValidationError: "None is not of type 'string'">]
```

I believe this is be related to troubleshooting introduced in #634 where a new property is added to the schema but some of the server language specs are not including it.

## Reproduce

1. Install jupyterlab (3.0.14)
2. Install jupyterlab-lsp (3.8.0) and jupyter-lsp (1.4.0)
3. Run jupyter lab with the `--debug` flag and watch for warning logs

## Expected behavior
Either no warnings logged for missing servers, or a way to turn them off?

## Context
- Operating System and version: MacOS Version 11.3.1 
- Browser and version: Chrome Version 91.0.4472.114
- JupyterLab version: 3.0.14

<details><summary>Required: installed server extensions</summary>
<pre>
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.4.0 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.14 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.0.14
my-conda-env/share/jupyter/labextensions
        bqplot v0.5.26 enabled OK (python, bqplot)
        @krassowski/jupyterlab-lsp v3.8.0 enabled OK (python, jupyterlab-lsp)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: my-conda-env/share/jupyter/lab
</pre>
</details>

**Comment by krassowski** [comment]
Thank you. We need to improve the validator output as it is hard to tell what failed from these logs, but I believe your assessment right. An immediate solution is to update the [schema](https://github.com/krassowski/jupyterlab-lsp/blob/master/python_packages/jupyter_lsp/jupyter_lsp/schema/schema.json) to accept `null`. I agree that ideally we would not be showing warnings for servers which are not installed.

**Comment by karlaspuldaro** [comment]
I can help looking into this

**Comment by karlaspuldaro** [comment]
Quick update on this, making `troubleshoot` nullable did not clear the warnings 😬
I'm debugging the validator to find the spec key flagged as invalid.

**Comment by karlaspuldaro** [comment]
@krassowski Apparently the `None` type warning was coming from the `argv` property in any [NodeModuleSpec](https://github.com/krassowski/jupyterlab-lsp/blob/bba7fd1f3f10e93c2dc428bb19eb2959a9b29def/python_packages/jupyter_lsp/jupyter_lsp/specs/utils.py#L119) not installed.
`node_module` would resolve to `None` and passed to the `argv` array, so the validator would complain about the type not being a string.

There are a few ways to solve this, not sure which one is best:
1. Accept null for `argv` in schema (not sure we have control over shell-args as we're using a ref there..)
2. Update [solve](https://github.com/krassowski/jupyterlab-lsp/blob/bba7fd1f3f10e93c2dc428bb19eb2959a9b29def/python_packages/jupyter_lsp/jupyter_lsp/specs/utils.py#L131) function to return empty string when `find_node_module` comes back as `None`
3. (Best guess) Update `argv` in `__call__` to be an empty array when spec is not installed (same approach used in [PythonModuleSpec](https://github.com/krassowski/jupyterlab-lsp/blob/bba7fd1f3f10e93c2dc428bb19eb2959a9b29def/python_packages/jupyter_lsp/jupyter_lsp/specs/utils.py#L81))

**Comment by krassowski** [comment]
Thank you for looking into this. I agree that option 3 would be best for now.
