### ISSUE TITLE
Javascript syntax highlighting with PixieDust Node magic (%%node)

### ISSUE THREAD

**Issue by daneto82** [krassowski/jupyterlab-lsp#641]
Hello!

I'm using [PixieDust Node](https://github.com/pixiedust/pixiedust_node), an "extension that enable a Jupyter Notebook user to invoke Node.js commands".

I'm trying to activate Javascript syntax highlighting for the cells with %%node magic, but I didn't find anywhere in the documentation how can I achieve that. I tried to work on that:

```
{
  "LanguageServerManager": {
    "language_servers": {
      "a-language-server-implementation": {
        "version": 2,
        "argv": ["/absolute/path/to/a-language-server", "--stdio"],
        "languages": ["a-language"],
        "mime_types": ["text/language", "text/x-language"]
      }
    }
  }
}
```

... but I could not succeed.

Thank you in advance, and sorry if I am missing something.

**Comment by krassowski** [comment]
It is not exactly a new language server that you need (we already have language servers configured for JavaScript), but an extractor as in:

https://github.com/krassowski/jupyterlab-lsp/blob/bba7fd1f3f10e93c2dc428bb19eb2959a9b29def/packages/_example-extractor/src/index.ts#L12-L18

also see: https://github.com/krassowski/jupyterlab-lsp/tree/master/packages/jupyterlab-lsp/src/transclusions.

I would normally say that we plan to make it configurable by supplying a JSON object to Advanced Settings Editor soon, but as you already seem familiar with JavaScript you may be able to create an extractor extension (modifying the example linked above).

After you get a new document extracted you will also need to install the language server as explained in [the docs](https://jupyterlab-lsp.readthedocs.io/en/latest/Language%20Servers.html).

**Comment by krassowski** [comment]
I will close this issue now since there was no response in three weeks, but please feel free to reopen if you have any further questions.
