### ISSUE TITLE
jupyter-lsp mixed autocompletion results from different r notebook

### ISSUE THREAD

**Issue by TTTPOB** [krassowski/jupyterlab-lsp#642]
## Description

jupyter-lsp mixed autocompletion results from different r notebook
## Reproduce

1. open more than one notebooks
2. create some variables in notebook a
3. trigger autocompletion in notebook b
4. you see results from notebook a
![image](https://user-images.githubusercontent.com/19909103/125054059-62cb9900-e0d8-11eb-90a5-765b890e774b.png)

hmmm sorry but i'll try in normal notebook

## Expected behavior

autocompletion do not mix

## Context

- Operating System and version: `CentOS Linux 7 (Core) x86_64  3.10.0-1062.9.1.el7.x86_64`
- Browser and version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.64`
- JupyterLab version: `3.0.16`

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: /NAS392047/home/xxx/.jupyter

/home/xxx/anaconda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
Config dir: /home/xxx/anaconda/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.4.0 OK
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage  OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.16 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter

</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.0.16
/home/xxx/anaconda/share/jupyter/labextensions
        jupyterlab-execute-time v2.0.4 enabled OK (python, jupyterlab_execute_time)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @krassowski/jupyterlab-lsp v3.8.0 enabled OK (python, jupyterlab-lsp)
        @jupyter-server/resource-usage v0.6.0 enabled OK (python, jupyter-resource-usage)

Other labextensions (built into JupyterLab)
   app dir: /NAS392047/home/xxx/anaconda/share/jupyter/lab
        @axlair/jupyterlab_vim v0.13.4 enabled OK

Uninstalled core extensions:
    @karosc/jupyterlab_dracula
    @lckr/jupyterlab_variableinspector
    @ryantam626/jupyterlab_code_formatter
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
Hi @TTTPOB thank you for opening this issue, I very much appreciate feedback like this! In this case I think it's not us - it's the r-languageserver. I think that this is by design, this is completion symbols are shared across workspace for a certain definition of workspace.

Looking at this issue in the language server repository: https://github.com/REditorSupport/languageserver/issues/58 I understand that it was based on an observation that when you are developing an R **package** than all functions and variables are usually shared across files (I don't think this is a good thing, but this is how it most frequently works). I agree that it does not make sense for **notebooks** and we should be able to enable restricting the completion sources (this is the workspace) to a single notebook if user chooses too. This is a very interesting and important observation for the future design of the extension.

The current way r-languageserver handles this is described in https://github.com/REditorSupport/languageserver/pull/123 and I think that we would need to open an issue in their repo first to discuss it, and if they agree create a PR with a configuration option allowing to change whether the completion should be coming from a single document only or from entire workspace (all open files). I don't have a bandwidth to work on this, but if you are comfortable with R this might be a good feature to contribute upstream. Would you like to start by creating an issue in https://github.com/REditorSupport/languageserver to discuss that with maintainers? Please link back to this issue and feel free to CC me.

**Comment by krassowski** [comment]
Also, it's so nice to see this extension being used for bioinformatics work :)

**Comment by TTTPOB** [comment]
> Hi @TTTPOB thank you for opening this issue, I very much appreciate feedback like this! In this case I think it's not us - it's the r-languageserver. I think that this is by design, this is completion symbols are shared across workspace for a certain definition of workspace.
> 
> Looking at this issue in the language server repository: [REditorSupport/languageserver#58](https://github.com/REditorSupport/languageserver/issues/58) I understand that it was based on an observation that when you are developing an R **package** than all functions and variables are usually shared across files (I don't think this is a good thing, but this is how it most frequently works). I agree that it does not make sense for **notebooks** and we should be able to enable restricting the completion sources (this is the workspace) to a single notebook if user chooses too. This is a very interesting and important observation for the future design of the extension.
> 
> The current way r-languageserver handles this is described in [REditorSupport/languageserver#123](https://github.com/REditorSupport/languageserver/pull/123) and I think that we would need to open an issue in their repo first to discuss it, and if they agree create a PR with a configuration option allowing to change whether the completion should be coming from a single document only or from entire workspace (all open files). I don't have a bandwidth to work on this, but if you are comfortable with R this might be a good feature to contribute upstream. Would you like to start by creating an issue in https://github.com/REditorSupport/languageserver to discuss that with maintainers? Please link back to this issue and feel free to CC me.

ok thank you for the clarification, I feel sorry about bothering you before I fully investigated the problem. I thought it may be a r language server problem but I have not verify it. I will seek help there.



> Also, it's so nice to see this extension being used for bioinformatics work :)

haha, autocompletion from IRKernel is not so good so... thank your for the great work!

**Comment by randy3k** [comment]
I reckon one possible solution is to support [multiple workspace folders](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_workspaceFolders) and have each notebook opened under a different workspace folder.

Then for servers which support multiple workspace folders, they will be able to differentiate completions from different workspaces and forward only relevant ones.

PS: by the way, R server doesn't support multiple workspace folders, neither.

**Comment by randy3k** [comment]
Another solution is to open a process for each individual notebook (I believe the R kernel iRKernel also does it).

**Comment by krassowski** [comment]
Thanks for chiming in. Multiple workspace folders seems like a good solution, but I understand this is a chicken and egg problem for developing that.

> PS: by the way, R server doesn't support multiple workspace folders, neither.

Would that be in scope for the R server in the future?

**Comment by randy3k** [comment]
It was in my mind when I was developing the R server so supporting it is not very difficult.  
But I guess you will be the only client that uses the multiple folders feature. Most other editors would spawn a separate server for each folder.
