### ISSUE TITLE
Unable to access syntax highlighting for IPython BigQuery magic

### ISSUE THREAD

**Issue by HalfMillennium** [krassowski/jupyterlab-lsp#644]
## What I am trying to do...

I'm currently attempting to take advantage of a merged PR that provided syntax highlighting while using IPython's BigQuery magic `%%bigquery`, but I'm unsure how to set this up. (#553)

## How I would like to learn how to do it...

I would like to have a better understanding of what I need to setup (a connected SQL language server?) in order to make use of the highlighting, since there is very little mention of BigQuery elsewhere in the repo.

**Comment by krassowski** [comment]
Welcome :) There is nothing needed to configure. Just install the extension and it should work out of the box. If it is not working please fill in the template for bug reports.

I just tried this on binder: https://mybinder.org/v2/gh/krassowski/jupyterlab-lsp/master?urlpath=lab%2Ftree%2Fexamples%2FPython.ipynb and it "just works":

![its-working-bigquery](https://user-images.githubusercontent.com/5832902/125302111-93534300-e323-11eb-8b19-dbc124e0d924.gif)

**Comment by krassowski** [comment]
However, if you want anything more than syntax highlighting you will need to have an sql language server installed which as I mentioned earlier is likely not supporting bigquery-specific constructs.

**Comment by HalfMillennium** [comment]
> However, if you want anything more than syntax highlighting you will need to have an sql language server installed which as I mentioned earlier is likely not supporting bigquery-specific constructs.

Thanks for the response! I'll send out a bug report soon, as I'm still having issues locally.
