### ISSUE TITLE
[help wanted] how do I configure pycodestyle to launch with some cli arguments?

### ISSUE THREAD

**Issue by TTTPOB** [krassowski/jupyterlab-lsp#651]
I want to set pycodestyle to use 2 space indentation, to do so, I need to launch pycodestyle with argument   `--indent-size=2`, and this option seems not available in config file, so how do I set the argument?

**Comment by krassowski** [comment]
I believe it should work from config file ([based on these lines](https://github.com/PyCQA/pycodestyle/pull/970/files#diff-4a4449bebe834e732cefc3ad4314c8ff92c3bfb80c395441ebdb3b3cac6f947aR2541-R2544)), so if it does not work this is a bug and you should report it to https://github.com/PyCQA/pycodestyle. Still if you want to pass it directly, you should consider contributing this option to https://github.com/python-lsp/python-lsp-server (I assume you are using pylsp, but cannot be sure...).

**Comment by TTTPOB** [comment]
thank you for the quick response! I have to admit that I've not noticed these lines, thank you!
