### ISSUE TITLE
Unable to enable custom LSP

### ISSUE THREAD

**Issue by HalfMillennium** [krassowski/jupyterlab-lsp#652]
## Description

I created a new language server based off of the documentation provided here (https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample). I published it as an NPM package here (https://www.npmjs.com/package/elastic-lsp).

## Reproduce

Attempt to install the above language server with jlpm: `jlpm add --dev elastic-lsp`. This LSP does utilize VPN-specific credentials, so the general public cannot be expected to make use of it, but it should be possible to see this server in the list of LSPs initialized in JLab at least, right?

## Expected behavior

As I mentioned above, I can't see the LSP initialized in JLab after installation.

## Context

- Operating System and version: macOS Big Sur
- Browser and version: Safari 14.1
- JupyterLab version: 
- `jupyter-lsp` version:
- `jupyterlab-lsp` version:
- Language Server: elastic-lsp
- Language Server version: 1.0.1
- Language Server installed with: jlpm
- Language Server Spec

```
None
```
My LSP utilizes an internal API to generate autocomplete suggestions, so I didn't believe that any configuration file was required. Was this a correct assumption?

**Comment by krassowski** [comment]
Configuration is needed as we need to know how to start you custom language server. Please read the documentation here https://jupyterlab-lsp.readthedocs.io/en/latest/Language%20Servers.html and here:  https://jupyterlab-lsp.readthedocs.io/en/latest/Configuring.html#language-servers

**Comment by HalfMillennium** [comment]
Okay, I've tried following the sample configuration, and created the file: `/.../jupyter_server_config.d/elastic-lsp.json`:

```
{
  "LanguageServerManager": {
    "language_servers": {
      "elastic-lsp": {
        "version": 1,
        "argv": ["/Users/garrettc/src/elastic-lsp/vscode-extension-samples/elastic-lsp", "--stdio"],
        "languages": ["python"],
        "mime_types": ["text/language", "text/x-language"]
      }
    }
  }
}
```

But whenever I launch JupyterLab, I get this error:

```
jupyter_lsp | extension failed loading with message: schema errors:
    	1 is not one of [2]
    for:
    {'elastic-lsp': {'version': 1, 'argv': ['/Users/garrettc/src/elastic-lsp/vscode-extension-samples/elastic-lsp', '--stdio'], 'languages': ['python'], 'mime_types': ['text/language', 'text/x-language']}}
```

I'm not sure what's wrong with my schema.

**Comment by krassowski** [comment]
You need to use version 2. Do we say version one in docs? This likely needs correcting, sorry!

**Comment by HalfMillennium** [comment]
@krassowski Yes, that was it, thank you! I'm now getting a `Permission denied` error, but I assume this has something to do with my language server.
