### ISSUE TITLE
Doesnt work in the notebook, only in the Jupyterlab

### ISSUE THREAD

**Issue by roboserg** [krassowski/jupyterlab-lsp#664]
Installed versions:

[jupyter info](https://i.imgur.com/3YVov8X.png)
python = 3.8
notebook = 5.7.10 (tried 6.x as well)

Jupyter Lab - [Image of an Error](https://i.imgur.com/AYxP0wH.png)
Advanced Settings - [picture](https://i.imgur.com/dCg6PmN.png)

I don't know what to do else, please help.

**Comment by krassowski** [comment]
Hi @roboserg, this extension indeed does not support notebook.

However you can install [JupyterLab Retro / retrolab](https://github.com/jupyterlab/retrolab) if you prefer the classic, simple interface of notebook and want to use this extension (and many others!).

**Comment by roboserg** [comment]
> Hi @roboserg, this extension indeed does not support notebook.
> 
> However you can install [JupyterLab Retro / retrolab](https://github.com/jupyterlab/retrolab) if you prefer the classic, simple interface of notebook and want to use this extension (and many others!).

Thanks for the quick reply! Your extension is awesome, exactly what I needed. May I suggest two features / ask if you have plans implementing them?

1. mouse over the elements should automatically update the docs on the right (like when using arrow keys)
2. partially typing should also automatically trigger auto complete

See video for examples - https://streamable.com/kro69o

**Comment by krassowski** [comment]
> mouse over the elements should automatically update the docs on the right (like when using arrow keys)

just to make sure, you mean that hovering over the completion suggestions should show the documentation, right? This is an interesting suggestion - thanks!

> partially typing should also automatically trigger auto complete

This is already available as an opt-in - you need to set `"continuousHinting"` to `true` in settings (there are some GIFs showing how to do that on https://stackoverflow.com/a/64233966/6646912 and on https://stackoverflow.com/a/65740365/6646912) - unless you meant something else!

**Comment by roboserg** [comment]
> just to make sure, you mean that hovering over the completion suggestions should show the documentation

Yes, it is much faster to scroll with a mouse wheel then using arrow keys.

**continuousHinting** is exactly what I wanted, thanks!

**Comment by krassowski** [comment]
> Yes, it is much faster to scroll with a mouse wheel then using arrow keys.

Just a quick note, <kbd>PgUp</kbd> and <kbd>PgDn</kbd> keys work well for me, but I did open an issue to remember about implementing it the next time I get to modify this part od the codebase.
