### ISSUE TITLE
Investigate possible issues with jupyterlab 1.2

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#75]
JupyterLab 1.2.0rc0 is up on pip and conda, with the planned release date of 2019-10-29 (doh #65) we should at least take a look at it... i'll give it a minimal look through, and if it seems ok, will look at popping up the dependency strings. It would be great if we could support it transparently. Who knows, might find something useful for upstream!

**Comment by bollwyvl** [comment]
Fails to build with:
```
src/index.ts:97:43 - error TS2345: Argument of type 'import("~/jupyterlab-lsp/node_modules/@jupyterlab/docregistry/lib/registry").IDocumentWidget<import("~/jupyterlab-lsp/node_modules/@jupyterlab/fileeditor/lib/widget").FileEditor, import("~/jupyterlab-lsp/node_modules/@jupyterlab/docregi...' is not assignable to parameter of type 'import("~/jupyterlab-lsp/node_modules/@krassowski/jupyterlab_go_to_definition/node_modules/@jupyterlab/docregistry/lib/registry").IDocumentWidget<import("~/jupyterlab-lsp/node_modules/@krassowski/jupyterlab_go_to_definition/node_modules/@jupyterlab/fileeditor/lib...'.
  Types of property 'content' are incompatible.
    Type 'import("~/jupyterlab-lsp/node_modules/@jupyterlab/fileeditor/lib/widget").FileEditor' is not assignable to type 'import("~/jupyterlab-lsp/node_modules/@krassowski/jupyterlab_go_to_definition/node_modules/@jupyterlab/fileeditor/lib/widget").FileEditor'.
      Property 'onAfterAttach' is protected but type 'FileEditor' is not a class derived from 'FileEditor'.

97         let jumper = new FileEditorJumper(widget, documentManager);
                                             ~~~~~~

src/index.ts:119:39 - error TS2345: Argument of type 'import("~/jupyterlab-lsp/node_modules/@jupyterlab/notebook/lib/panel").NotebookPanel' is not assignable to parameter of type 'import("~/jupyterlab-lsp/node_modules/@krassowski/jupyterlab_go_to_definition/node_modules/@jupyterlab/notebook/lib/panel").NotebookPanel'.
  Property '[Printing.symbol]' is missing in type 'import("~/jupyterlab-lsp/node_modules/@jupyterlab/notebook/lib/panel").NotebookPanel' but required in type 'import("~/jupyterlab-lsp/node_modules/@krassowski/jupyterlab_go_to_definition/node_modules/@jupyterlab/notebook/lib/panel").NotebookPanel'.

119       let jumper = new NotebookJumper(widget, documentManager);
                                          ~~~~~~

  node_modules/@krassowski/jupyterlab_go_to_definition/node_modules/@jupyterlab/notebook/lib/panel.d.ts:57:5
    57     [Printing.symbol](): () => Promise<void>;
           ~~~~~~~~~~~~~~~~~
    '[Printing.symbol]' is declared here.


Found 4 errors.

```

I'll take a look over on `@krassowski/jupyterlab_go_to_definition`...

**Comment by krassowski** [comment]
Property 'onAfterAttach' is protected but type 'FileEditor' is not a class derived from 'FileEditor'.

Could it be a simple dependency version conflict?

**Comment by bollwyvl** [comment]
Yeah, probably a version conflict. Gave it a full go anyway (passes acceptance tests locally).

I won't even bother to PR, as we won't know more until later but here's a binder:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-lsp/deps/lab-1.2?urlpath=tree)

Probably worth at least taking a spin.

So again, one of the big things will be adopting lerna so that packages can be split up... perhaps it will become appropriate to move the jump in as well.

**Comment by bollwyvl** [comment]
Gave it a go on binder, everything seemed cool. I'll keep this open until we figure out what our version pins actually need to be...

**Comment by bollwyvl** [comment]
lab 1.2 is out:
- https://pypi.org/project/jupyterlab/1.2.0/#files
- https://anaconda.org/conda-forge/jupyterlab/files?version=1.2.0

I guess I'd like to see the integrity stuff from #79 land before going after that. If we want to claim back-compat with the 1.1 line, we'd probably need to add a test excursion for it... but probably not a whole extra matrix dimension.

**Comment by krassowski** [comment]
Thanks for the work here, closing as we are on 1.2 for a long time. We will need a similar one for 2.0 soon
