### ISSUE TITLE
Add Github Issue/PR templates

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#96]
We can add multiple [issue and pull request templates](https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/). Spending a few minutes writing these would help reduce our triage burden and get answers out more quickly.

Rather than doing a heavy choose-your-own-adventure, I think we can have a few sane defaults:
- Report a bug
- Request Documentation
- Request Built-in Language Server Support e.g. #95 #93
- Request Bring-your-own Language Server Support e.g. #17
  - ideally, we'd want to help transition these to contributed, testable, built-in specs, if it is at all possible to work up their installation in CI
- Request a Feature
- Announce Intent to Implement

PRs:
- Add a Language Server spec
- Add a Notebook Server feature
- Add a JupyterLab Client feature
- Add Documentation
- Add Tests
- Perform Maintenance (releases, repo organization, etc)

**Comment by bollwyvl** [comment]
Here are the JupyterLab [pr](https://github.com/jupyterlab/jupyterlab/blame/master/.github/pull_request_template.md) and [issue](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) templates.

**Comment by krassowski** [comment]
I very much like the idea of multiple issues templates, especially the categories that you've mentioned. Not sure about the need for so many templates for PRs, but well - why not? :)
