### ISSUE TITLE
R language server reported as available even when language server package is missing (but R is installed)

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#97]
While node modules-based specs check for the package presence, the shell-based specs only check for the command existence:

https://github.com/krassowski/jupyterlab-lsp/blob/e393acec2d7d8444ee8ae56c54e644a53b9a308d/py_src/jupyter_lsp/specs/utils.py#L34-L42

In the case of R, `Rscript` is available whenever R is installed - even if the languageserver package is not installed. We can very easily get a one-liner R script to check if the package is installed. This should probably be a method of `SpecBase` called in `__call__`; it could be named `is_installed(self)` or something like this.

Note: this does not affect python's plys as the checked command (`pyls`) is directly linked to the LSP server installation.

**Comment by krassowski** [comment]
The existing code which checks for installation should probably be moved into this function; the child classes would then be able to call `super().is_installed()` if they need to access the result of command/node existence check.

**Comment by bollwyvl** [comment]
Good catch! Is there any way to check it without actually starting a
process? Will it be somewhere relative to rscript? Can we do a pattern like
the node_modules stuff? I'm pushing towards fewer processes overall, but
especially at launch, as lab already fires up a nodejs process in every
launch to see if its build is up to date, and with kernels also starting
up, this can lead to "too many files open", especially on... wait for it...
Windows. But also in little cloud containers, like where we do ci.

**Comment by krassowski** [comment]
I guess we could look in library paths, but this would be much less reilable than just using a dedicated mechanism.
