### ISSUE TITLE
Listener API

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#99]
A number of issues (#95, #17, probably more) have identified a need for writing 
concrete files to disk in order for language servers to act on them. This is 
sufficient to start the conversation about allowing the pipeline of language 
messages to be intercepted by any number of agents. Currently the flow looks like:

```
                 --> queue --> stdin
                |                |
                |                v
client  <--> handler         language server
                ^                |
                |                v
                 --  queue  <-- stdout

``` 

Proposed is to allow any number of listeners to react to the messages.

```
                 --> listener --> queue --> stdin
                |                            |
                |                            v
client  <--> handler                   language server
                ^                            |
                |                            v
                 --  listener <-- queue <-- stdout

```

Not proposed is to actually _change_ or _prevent_ the delivery of messages, 
nor to encourage direct access to the handlers or servers, but rather to delay
delivery of a message until some external side effect has been completed, in the
initial case, the writing of a file to disk.

This particular case _could_ be achieved through direct use of the existing 
`ContentsManager` API, but in this case, LSP provides a change-based approach
over WebSockets that is likely more performant.

_notional API_

```py
from jupyter_lsp import on_lsp_message, LanguageServerManager

def load_jupyter_server_extension(nbapp):
    # another extension developer might need to IOLoop.call_later
    mgr = nbapp.language_server_manager

    @on_lsp_message(languages=".*", methods=r"textDocument/did(Open|Close)")
    async def do_thing_with_message(
        message: LSPMessage, 
        manager: LanguageServerManager
    ) -> None:
        # do something with a message
```

As these cannot change the message, they can be scheduled to run in "parallel".

_notional manager changes_
```py
import asyncio

class LanguageServerManager
    async write_server_message(message, language):
        await asyncio.gather([
            listener(message, self)
            for listener in listeners
            if listener.should_listen(message, {"language": language})
        ])
        for session in self.get_sessions(language):
            await session.write_message(message)
```

**Comment by krassowski** [comment]
I guess we can close this one?

**Comment by krassowski** [comment]
Please reopen if needed!

**Comment by bollwyvl** [comment]
Oops, yes, thanks. We'll learn more as people think of things to do with
it. Probably need to expose a client-side one, too, at some point...
